import {
  CURRENCY_CLASSNAME,
  FALSE,
  MISSION_GIVER_ID,
  QuestDef,
  TRUE,
} from "../constants/questValues.ts";

// Main chain: 10 quests, gated in sequence via PreQuestIDs, all given out
// and turned in at the single mission-giver NPC. Quest #1 has no
// QuestGiverIDs at all, so it auto-starts for every player on first connect
// (see this file's header comment) - its only job is to get the player to
// walk over and meet Taskmaster Daniels.
const MAIN_QUESTS: QuestDef[] = [
  {
    id: 1000,
    fileName: "DZSurvival_Quest_1000",
    title: "Welcome to Romashka Farm",
    objectiveText: "Make your way to Romashka Farm and speak with Taskmaster Daniels.",
    descriptions: [
      "Word travels fast around here - a new face always does. There's a place called Romashka Farm nearby; go take a look and ask for Taskmaster Daniels.",
      "Romashka Farm is marked on your map. Go for it, it may be the safest place left.",
      "So you made it. Good. I keep track of who comes and goes through here - and I've got work, if you're interested.",
    ],
    questGiverIds: [],
    questTurnInIds: [MISSION_GIVER_ID],
    preQuestIds: [],
    repeatable: FALSE,
    isDailyQuest: FALSE,
    objectives: [{ type: "TRAVEL", id: 1000 }],
    rewards: [{ className: CURRENCY_CLASSNAME, amount: 5000 }, {
      className: "TentMedium_Packed",
      amount: 1,
    }],
  },
  {
    id: 1001,
    fileName: "DZSurvival_Quest_1001",
    title: "Prove You Can Handle Yourself",
    objectiveText: "Kill 15 Infected.",
    descriptions: [
      "This place stays standing because the people in it can handle themselves. Clear out fifteen of those things and I'll know you're not dead weight.",
      "Fifteen Infected. Go on, they're not hard to find.",
      "Not bad. You didn't come back missing any fingers, either.",
    ],
    questGiverIds: [MISSION_GIVER_ID],
    questTurnInIds: [MISSION_GIVER_ID],
    preQuestIds: [1000],
    repeatable: FALSE,
    isDailyQuest: FALSE,
    objectives: [{ type: "TARGET", id: 2000 }],
    rewards: [
      { className: CURRENCY_CLASSNAME, amount: 10000 },
      { className: "TRQ_DecoyGrenade", amount: 1 },
    ],
  },
  {
    id: 1002,
    fileName: "DZSurvival_Quest_1002",
    title: "Thin the Pack",
    objectiveText: "Kill 5 wolves.",
    descriptions: [
      "Wolves have been getting bold near the edges of town. Thin the pack out - five of them ought to send a message.",
      "Five wolves. Watch your back out there, they don't hunt alone.",
      "Good. Quiet nights again, for a while at least.",
    ],
    questGiverIds: [MISSION_GIVER_ID],
    questTurnInIds: [MISSION_GIVER_ID],
    preQuestIds: [1001],
    repeatable: FALSE,
    isDailyQuest: FALSE,
    objectives: [{ type: "TARGET", id: 2001 }],
    rewards: [{ className: CURRENCY_CLASSNAME, amount: 12500 }],
  },
  {
    id: 1003,
    fileName: "DZSurvival_Quest_1003",
    title: "Boar Hunt",
    objectiveText: "Kill 3 wild boar.",
    descriptions: [
      "Boar meat keeps better than most and there's always someone asking for it. Bring me down three of them.",
      "Three wild boar. They're tougher than they look, mind the charge.",
      "That'll keep a few bellies full. Here, take this - you've earned it.",
    ],
    questGiverIds: [MISSION_GIVER_ID],
    questTurnInIds: [MISSION_GIVER_ID],
    preQuestIds: [1002],
    repeatable: FALSE,
    isDailyQuest: FALSE,
    objectives: [{ type: "TARGET", id: 2002 }],
    rewards: [
      { className: CURRENCY_CLASSNAME, amount: 12500 },
      { className: "TaloonBag_Green", amount: 1 },
    ],
  },
  {
    id: 1004,
    fileName: "DZSurvival_Quest_1004",
    title: "Supply Run",
    objectiveText: "Deliver 5x Tuna Can and 5x Water Bottle.",
    descriptions: [
      "We're running low on stock. Bring me five tins of tuna and five bottles of water and I'll make it worth your while.",
      "Five Tuna Cans, five Water Bottles. Scavenge them or trade for them, I don't care which.",
      "That'll do. This place doesn't run itself.",
    ],
    questGiverIds: [MISSION_GIVER_ID],
    questTurnInIds: [MISSION_GIVER_ID],
    preQuestIds: [1003],
    repeatable: FALSE,
    isDailyQuest: FALSE,
    objectives: [{ type: "DELIVERY", id: 3000 }],
    rewards: [{ className: CURRENCY_CLASSNAME, amount: 15000 }],
  },
  {
    id: 1005,
    fileName: "DZSurvival_Quest_1005",
    title: "Fresh off the Vine",
    objectiveText: "Gather 3x Apple, 3x Pear and 3x Plum.",
    descriptions: [
      "Everyone's sick of canned everything. Bring me some real fruit - apples, pears, plums, three of each - and I'll pay well for it.",
      "Three apples, three pears, three plums. Orchards and gardens are your best bet.",
      "Now that's something. First fresh thing I've eaten in weeks.",
    ],
    questGiverIds: [MISSION_GIVER_ID],
    questTurnInIds: [MISSION_GIVER_ID],
    preQuestIds: [1004],
    repeatable: FALSE,
    isDailyQuest: FALSE,
    objectives: [{ type: "COLLECT", id: 4000 }],
    rewards: [{ className: CURRENCY_CLASSNAME, amount: 15000 }],
  },
  {
    id: 1006,
    fileName: "DZSurvival_Quest_1006",
    title: "Scout the Waterworks",
    objectiveText: "Scout the old Water Station north of here.",
    descriptions: [
      "There's an old water station north of here I need eyes on. Go take a look around, make sure it's still standing.",
      "The Water Station is marked on your map. Just get eyes on it.",
      "Good, appreciated. Here - found this on a supplier a while back, figured you could use it.",
    ],
    questGiverIds: [MISSION_GIVER_ID],
    questTurnInIds: [MISSION_GIVER_ID],
    preQuestIds: [1005],
    repeatable: FALSE,
    isDailyQuest: FALSE,
    objectives: [{ type: "TRAVEL", id: 1001 }],
    rewards: [
      { className: CURRENCY_CLASSNAME, amount: 16000 },
      { className: "evg_keycards_Yellow", amount: 1 },
    ],
  },
  {
    id: 1007,
    fileName: "DZSurvival_Quest_1007",
    title: "Into the Hot Zone",
    objectiveText: "Head to Stary Sobor and confirm the radiation reading with your own eyes.",
    descriptions: [
      "Stary Sobor's gone hot - real hot. I need someone to confirm it with their own eyes, not just rumors. Bring protection if you value your bone marrow.",
      "Head for Stary Sobor. If your dosimeter starts climbing, you're close enough.",
      "Confirmed, then. Stay out of there unless you've got a good reason - or good gear.",
    ],
    questGiverIds: [MISSION_GIVER_ID],
    questTurnInIds: [MISSION_GIVER_ID],
    preQuestIds: [1006],
    repeatable: FALSE,
    isDailyQuest: FALSE,
    objectives: [{ type: "TRAVEL", id: 1002 }],
    rewards: [{ className: CURRENCY_CLASSNAME, amount: 20000 }],
  },
  {
    id: 1008,
    fileName: "DZSurvival_Quest_1008",
    title: "The Big Game",
    objectiveText: "Kill 1 bear.",
    descriptions: [
      "Bears are rare out here, and dangerous for it. Bring one down and you'll have proven you belong on this island.",
      "One bear. Don't underestimate it - they don't go down easy.",
      "Now that's a trophy. Not many can say they've done that.",
    ],
    questGiverIds: [MISSION_GIVER_ID],
    questTurnInIds: [MISSION_GIVER_ID],
    preQuestIds: [1007],
    repeatable: FALSE,
    isDailyQuest: FALSE,
    objectives: [{ type: "TARGET", id: 2003 }],
    rewards: [
      { className: CURRENCY_CLASSNAME, amount: 22000 },
      { className: "evg_keycards_Blue", amount: 1 },
    ],
  },
  {
    id: 1009,
    fileName: "DZSurvival_Quest_1009",
    title: "Steady Hands",
    objectiveText: "Craft an Improvised Fishing Rod, then catch 2x Mackerel.",
    descriptions: [
      "You've proven you can fight and hunt. Now show me you can slow down and actually survive out here - craft a fishing rod and bring me back a couple of Mackerel.",
      "Craft an Improvised Fishing Rod first, then go catch two Mackerel with it, we'll need to know if fishing is still viable out here.",
      "There it is. A steady hand catches dinner without wasting a single round. You'll do just fine out here.",
    ],
    questGiverIds: [MISSION_GIVER_ID],
    questTurnInIds: [MISSION_GIVER_ID],
    preQuestIds: [1008],
    repeatable: FALSE,
    isDailyQuest: FALSE,
    objectives: [{ type: "CRAFTING", id: 6000 }, { type: "COLLECT", id: 4001 }],
    rewards: [
      { className: CURRENCY_CLASSNAME, amount: 10000 },
      { className: "ImprovisedFishingRod", amount: 1 },
    ],
  },
  {
    id: 1010,
    fileName: "DZSurvival_Quest_1010",
    title: "Wheels Up",
    objectiveText: "Deliver 1x Car Battery and 2x Spark Plug.",
    descriptions: [
      "Got a vehicle up on blocks that just needs parts. Bring me a battery and a couple of spark plugs and we'll get it running again.",
      "One Car Battery, two Spark Plugs. Garages and gas stations are your best bet.",
      "That'll do it. Give it a week and this thing'll be back on the road.",
    ],
    questGiverIds: [MISSION_GIVER_ID],
    questTurnInIds: [MISSION_GIVER_ID],
    preQuestIds: [1009],
    repeatable: FALSE,
    isDailyQuest: FALSE,
    objectives: [{ type: "DELIVERY", id: 12000 }],
    rewards: [{ className: CURRENCY_CLASSNAME, amount: 950 }],
  },
  {
    id: 1011,
    fileName: "DZSurvival_Quest_1011",
    title: "Key to the Vault",
    objectiveText: "Deliver 1x Green Keycard.",
    descriptions: [
      "I've got a contact who can cut you a better key, but he wants a common one to work from. Bring me a Green Keycard and I'll see what I can arrange.",
      "One Green Keycard. Plenty of those turn up if you know where to look.",
      "Good. Here - this one opens doors that green never could. Don't waste it.",
    ],
    questGiverIds: [MISSION_GIVER_ID],
    questTurnInIds: [MISSION_GIVER_ID],
    preQuestIds: [1010],
    repeatable: FALSE,
    isDailyQuest: FALSE,
    objectives: [{ type: "DELIVERY", id: 3003 }],
    rewards: [
      { className: CURRENCY_CLASSNAME, amount: 10000 },
      { className: "evg_keycards_Violet", amount: 1 },
    ],
  },
  {
    id: 1012,
    fileName: "DZSurvival_Quest_1012",
    title: "Beast of Burden",
    objectiveText: "Kill 10 rabbits or squirrels.",
    descriptions: [
      "Small game's easy pickings if you've got the patience for it. Bring me ten - rabbits, squirrels, don't matter which.",
      "Ten rabbits or squirrels, any mix. Treelines and hedgerows are thick with them.",
      "Not glamorous, but it's meat on the table. Appreciated.",
    ],
    questGiverIds: [MISSION_GIVER_ID],
    questTurnInIds: [MISSION_GIVER_ID],
    preQuestIds: [1011],
    repeatable: FALSE,
    isDailyQuest: FALSE,
    objectives: [{ type: "TARGET", id: 12000 }],
    rewards: [{ className: CURRENCY_CLASSNAME, amount: 850 }],
  },
  {
    id: 1013,
    fileName: "DZSurvival_Quest_1013",
    title: "Camp Cleared",
    objectiveText: "Push into the raider camp at NWAF and hold your ground.",
    descriptions: [
      "There's a raider camp dug in near NWAF that's been picking off scavengers all week. I need someone to walk in there and settle it - permanently, if you can manage it.",
      "Head for NWAF. You'll know the camp when the shooting starts.",
      "Word already got back to me. That camp won't be bothering anyone again. You've more than earned your keep here.",
    ],
    questGiverIds: [MISSION_GIVER_ID],
    questTurnInIds: [MISSION_GIVER_ID],
    preQuestIds: [1012],
    repeatable: FALSE,
    isDailyQuest: FALSE,
    objectives: [{ type: "TRAVEL", id: 1003 }],
    rewards: [
      { className: CURRENCY_CLASSNAME, amount: 35000 },
      { className: "evg_keycards_Red", amount: 1 },
    ],
  },
];

// Side quests: standalone, always available (no PreQuestIDs), repeatable
// currency grinds. A couple are capped once/day (IsDailyQuest); the rest
// have no cooldown at all when Repeatable is true without IsDailyQuest/
// IsWeeklyQuest (confirmed via ExpansionQuestModule::CompleteQuest - the
// cooldown-timestamp block only runs for daily/weekly quests), so those are
// free to grind back-to-back.
const SIDE_QUESTS: QuestDef[] = [
  {
    id: 1100,
    fileName: "DZSurvival_Quest_1100",
    title: "Vermin Control",
    objectiveText: "Kill 20 Infected.",
    descriptions: [
      "Always more of those things than there are of us. Clear out twenty and there's gold in it for you - once a day, mind.",
      "Twenty Infected. Come back tomorrow if you want to do this again.",
      "That's today's batch dealt with. Come back tomorrow.",
    ],
    questGiverIds: [MISSION_GIVER_ID],
    questTurnInIds: [MISSION_GIVER_ID],
    preQuestIds: [],
    repeatable: TRUE,
    isDailyQuest: TRUE,
    objectives: [{ type: "TARGET", id: 2004 }],
    rewards: [{ className: CURRENCY_CLASSNAME, amount: 3000 }],
  },
  {
    id: 1101,
    fileName: "DZSurvival_Quest_1101",
    title: "Deer Season",
    objectiveText: "Kill 3 deer.",
    descriptions: [
      "There's always a buyer for venison. Bring me three deer, any time you've got them - no need to wait between trips.",
      "Three deer, red or roe, doesn't matter which.",
      "Good hunting. Come back whenever you've got more.",
    ],
    questGiverIds: [MISSION_GIVER_ID],
    questTurnInIds: [MISSION_GIVER_ID],
    preQuestIds: [],
    repeatable: TRUE,
    isDailyQuest: FALSE,
    objectives: [{ type: "TARGET", id: 2005 }],
    rewards: [{ className: CURRENCY_CLASSNAME, amount: 8000 }],
  },
  {
    id: 1102,
    fileName: "DZSurvival_Quest_1102",
    title: "Bottled Sunshine",
    objectiveText: "Gather 5x Water Bottle.",
    descriptions: [
      "Clean water's always worth something. Bring me five bottles and I'll pay - once a day, no more.",
      "Five Water Bottles. Any well or pump will do.",
      "That'll keep us going a while longer. Come back tomorrow.",
    ],
    questGiverIds: [MISSION_GIVER_ID],
    questTurnInIds: [MISSION_GIVER_ID],
    preQuestIds: [],
    repeatable: TRUE,
    isDailyQuest: TRUE,
    objectives: [{ type: "COLLECT", id: 4002 }],
    rewards: [{ className: CURRENCY_CLASSNAME, amount: 5000 }],
  },
  {
    id: 1103,
    fileName: "DZSurvival_Quest_1103",
    title: "Rags to Riches",
    objectiveText: "Gather 10x Rag.",
    descriptions: [
      "Cloth's always in short supply. Bring me ten rags whenever you've got them - no waiting between trips.",
      "Ten Rags. Torn shirts, whatever you can find.",
      "Every bit helps. Come back whenever you've got more.",
    ],
    questGiverIds: [MISSION_GIVER_ID],
    questTurnInIds: [MISSION_GIVER_ID],
    preQuestIds: [],
    repeatable: TRUE,
    isDailyQuest: FALSE,
    objectives: [{ type: "COLLECT", id: 4003 }],
    rewards: [{ className: CURRENCY_CLASSNAME, amount: 2500 }],
  },
  {
    id: 1104,
    fileName: "DZSurvival_Quest_1104",
    title: "Firewood for the Fire",
    objectiveText: "Deliver 10x Wooden Log.",
    descriptions: [
      "Nights get cold and the fire doesn't feed itself. Bring me ten wooden logs and I'll pay for the trouble - once a day.",
      "Ten Wooden Logs. Any treeline will do.",
      "That'll keep the fire going a good while. Come back tomorrow.",
    ],
    questGiverIds: [MISSION_GIVER_ID],
    questTurnInIds: [MISSION_GIVER_ID],
    preQuestIds: [],
    repeatable: TRUE,
    isDailyQuest: TRUE,
    objectives: [{ type: "DELIVERY", id: 3001 }],
    rewards: [{ className: CURRENCY_CLASSNAME, amount: 3000 }],
  },
  {
    id: 1105,
    fileName: "DZSurvival_Quest_1105",
    title: "Small Game",
    objectiveText: "Kill 5 rabbits or squirrels.",
    descriptions: [
      "Quick work if you've got a light touch. Five rabbits or squirrels, any mix, whenever you've got them.",
      "Five rabbits or squirrels. No need to wait between trips.",
      "Not much, but it adds up. Come back whenever.",
    ],
    questGiverIds: [MISSION_GIVER_ID],
    questTurnInIds: [MISSION_GIVER_ID],
    preQuestIds: [],
    repeatable: TRUE,
    isDailyQuest: FALSE,
    objectives: [{ type: "TARGET", id: 2007 }],
    rewards: [{ className: CURRENCY_CLASSNAME, amount: 7000 }],
  },
  {
    id: 1106,
    fileName: "DZSurvival_Quest_1106",
    title: "Fuel Run",
    objectiveText: "Deliver 2x Canister Gasoline.",
    descriptions: [
      "Generators and vehicles both drink the stuff faster than we can find it. Bring me two canisters, whenever you've got them - once a day, mind.",
      "Two Canister Gasoline. Gas stations are your best bet.",
      "That'll keep the lights on a while longer. Come back tomorrow.",
    ],
    questGiverIds: [MISSION_GIVER_ID],
    questTurnInIds: [MISSION_GIVER_ID],
    preQuestIds: [],
    repeatable: TRUE,
    isDailyQuest: TRUE,
    objectives: [{ type: "DELIVERY", id: 3004 }],
    rewards: [{ className: CURRENCY_CLASSNAME, amount: 3000 }],
  },
  {
    id: 1107,
    fileName: "DZSurvival_Quest_1107",
    title: "Scrap Drive",
    objectiveText: "Gather 5x Metal Plate.",
    descriptions: [
      "Always building something around here. Bring me five metal plates whenever you've got them - no waiting between trips.",
      "Five Metal Plates. Sheds and garages are worth checking.",
      "Every bit helps. Come back whenever you've got more.",
    ],
    questGiverIds: [MISSION_GIVER_ID],
    questTurnInIds: [MISSION_GIVER_ID],
    preQuestIds: [],
    repeatable: TRUE,
    isDailyQuest: FALSE,
    objectives: [{ type: "COLLECT", id: 4004 }],
    rewards: [{ className: CURRENCY_CLASSNAME, amount: 5000 }],
  },
];

export const ALL_QUESTS = [...MAIN_QUESTS, ...SIDE_QUESTS];
