// Custom trader city: replaces DayZ-Expansion-Market's 6 stock Chernarus
// trader zones (self-generated by the mod into MISSION_DIR/expansion/
// traderzones/ on first world load) with a single custom-designed one.
//
// Roster: one general "Everything" trader plus one "Vehicle" trader.
// DayZ-Expansion-Market's 17 default trader identities (under
// profiles/ExpansionMod/Traders/) are left in place, unreferenced by any
// live NPC, for later use (see ensureCustomTraderIdentities()); only these
// two custom identities are referenced by the actual NPCs below. Their own
// "Categories" still get kept valid against src/market.ts's post-merge
// category names though (see fixDefaultTraderIdentityCategories()) -
// otherwise they'd silently bit-rot into a wall of boot-time "TRADER
// CONFIGURATION ERROR" log spam and be broken the day anyone actually
// wants to stand one up.
//
// This only defines the zone's shape (radius/pricing) and NPC roster. The
// world position must be scouted manually in-game as admin (COT's free cam/
// `INSERT` + position readout) and filled into CUSTOM_POSITION below. Until
// set, this only removes the 6 defaults and leaves the custom zone/NPCs
// disabled (with a warning) rather than writing NPCs to a guessed,
// possibly-underground position.
//
// NPCs are placed via Expansion's plain-text `.map` format (one line each:
// `<TraderEntityClassName>.<TraderFileName>|<Position>|<Orientation>|<Gear>`)
// under MISSION_DIR/expansion/traders/ (see DayZ-Expansion-Core's
// ExpansionWorldObjectsModule.c GetTraderFromMissionFile()/ProcessGear()).
// Individual NPC positions here are *offsets* from CUSTOM_POSITION, so only
// one real-world coordinate ever needs scouting.
//
// The Gear field is a comma-separated token list; the only token used here
// is `loadout:<Name>`, which applies a named gear preset from
// profiles/ExpansionMod/Loadouts/<Name>.json (written by
// ensureCustomTraderGear() below) via ExpansionHumanLoadout.Apply(). That
// preset schema (ExpansionPrefabObject/InventoryAttachments) is NOT the
// same as DayZ-Editor's exported character-preset JSON
// (attachmentSlotItemSets/discreteItemSets) - see TRADER_BLUE_GEAR, which
// was manually converted from the latter to the former.

import {
  EXPANSION_MARKET_DIR,
  EXPANSION_TRADERS_DIR,
  MARKET_SETTINGS,
  MISSION_DIR,
  SAFE_ZONE_SETTINGS,
} from "../constants/paths.ts";
import { log, ok, warn } from "../ui.ts";
import { exists } from "jsr:@std/fs@1.0.24";
import { MANAGED_MARKET_CATEGORIES } from "./market.ts";
import {
  KEYCARD_SELL_ONLY_CLASSNAMES,
  OLD_FOOD_CLASSNAMES,
  WOOD_SELL_ONLY_CLASSNAMES,
} from "./marketGapFill.ts";

const TRADERZONES_DIR = `${MISSION_DIR}/expansion/traderzones`;
const DEFAULT_ZONE_FILES = [
  "Svetloyarsk.json",
  "BalotaAircrafts.json",
  "KamenkaBoats.json",
  "GreenMountain.json",
  "Kamenka.json",
  "Krasnostav.json",
];

const CUSTOM_ZONE_NAME = "CustomTrader";

export const CUSTOM_POSITION: [number, number, number] | null = [7991.59, 221.09, 11312.5];

export const CUSTOM_SAFE_ZONE_RADIUS = 175;

interface TraderIdentity {
  fileName: string;
  displayName: string;
  icon: string;
  categories: string[];
  /**
   * Per-item buy/sell override (ExpansionMarketTrader's own `Items` map,
   * confirmed via unpacking market_scripts.pbo's
   * ExpansionMarketTraderBuySell enum: CanOnlyBuy=0, CanBuyAndSell=1,
   * CanOnlySell=2, CanBuyAndSellAsAttachmentOnly=3). Independent of both
   * stock AND of the item's own MinPriceThreshold/MaxPriceThreshold -
   * CanBuyItem()/CanSellItem() each check only this value, so a
   * CanOnlySell item still sells for its normal (SellPricePercent-scaled)
   * price, it just can never be bought at any price.
   */
  items?: Record<string, number>;
}

// ExpansionMarketTraderBuySell.CanOnlySell - see TraderIdentity.items above.
const CAN_ONLY_SELL = 2;

// Old_ (moldy/expired) canned goods are find-only in the world, not
// buyable, but still sellable back to the trader for a modest price (see
// marketGapFill.ts's OLD_FOOD_CLASSNAMES/FOOD_OLD_CAN_PRICE).
const OLD_FOOD_BUYSELL_OVERRIDES = Object.fromEntries(
  OLD_FOOD_CLASSNAMES.map((c) => [c, CAN_ONLY_SELL]),
);

// WoodenLog/Firewood: same find-only-but-sellable pattern as old food above
// (see marketGapFill.ts's WOOD_SELL_ONLY_CLASSNAMES/WOOD_SELL_ONLY_PRICE_FIXES).
const WOOD_BUYSELL_OVERRIDES = Object.fromEntries(
  WOOD_SELL_ONLY_CLASSNAMES.map((c) => [c, CAN_ONLY_SELL]),
);

// @Custom-Keycards: find-only-but-sellable, same pattern as old food/wood
// above - a card is worth *using* far more than selling it (see
// marketGapFill.ts's KEYCARD_SELL_ONLY_CLASSNAMES/KEYCARD_SELL_PRICE_FIXES
// for the deliberately modest payout scale). evg_keycards_All isn't in this
// list at all - it was never wired into any Market category in the first
// place (see customKeycards.ts), so there's nothing to restrict here.
const KEYCARD_BUYSELL_OVERRIDES = Object.fromEntries(
  KEYCARD_SELL_ONLY_CLASSNAMES.map((c) => [c, CAN_ONLY_SELL]),
);

// Same schema/currency as DayZ-Expansion-Market's own default trader
// identity files. Categories reference Market category names under
// profiles/ExpansionMod/Market/, which stay individually stock-capped by
// src/market.ts (tuneExpansionMarket()) regardless of which trader sells
// them, so lumping everything into one NPC here doesn't bypass tuning.
// Every category name across both identities is exported so
// marketAudit.ts can compute exactly which categories a player can
// actually buy/sell from without hand-reconstructing this list from
// market.ts's separate category exports.
export const CUSTOM_TRADER_IDENTITIES: TraderIdentity[] = [
  {
    fileName: "Everything",
    displayName: "General Store",
    icon: "Trader",
    // See src/market.ts's MERGED_CATEGORIES for what each of these
    // contains and how items are tiered. Vehicles/Vehicle_Parts/Batteries
    // are reserved for the Vehicle Dealer below.
    categories: [
      "Guns_Military",
      "Guns_Civilian",
      "Gun_Ammo",
      "Gun_Attachments_Military",
      "Gun_Attachments_Civilian",
      "Explosives",
      "Clothing_Head_Military",
      "Clothing_Head_Civilian",
      "Clothing_Top_Military",
      "Clothing_Top_Civilian",
      "Clothing_Bottom_Military",
      "Clothing_Bottom_Civilian",
      "Clothing_Back_Military",
      "Clothing_Back_Civilian",
      "Clothing_Misc_Military",
      "Clothing_Misc_Civilian",
      "Ghillies",
      "Consumables",
      "Medical",
      "Base_Building",
      "Utility",
      "Tools_And_Melee",
    ],
    items: {
      ...OLD_FOOD_BUYSELL_OVERRIDES,
      ...WOOD_BUYSELL_OVERRIDES,
      ...KEYCARD_BUYSELL_OVERRIDES,
    },
  },
  {
    fileName: "Vehicle",
    displayName: "Vehicle Dealer",
    icon: "Car",
    // No Boats - no navigable water anywhere near this trader city.
    categories: ["Vehicles_Cars", "Vehicles_Helicopters", "Vehicle_Parts", "Batteries"],
  },
];

interface CustomTraderNpc {
  entity: string;
  traderFile: string;
  /** Offset in meters from CUSTOM_POSITION, so only one coordinate needs scouting. */
  offset: [number, number, number];
  orientation: [number, number, number];
  gear?: string;
}

interface GearSlot {
  slot: string;
  className: string;
}

interface VehicleSpawnPoint {
  /** Offset in meters from CUSTOM_POSITION, same convention as CUSTOM_NPCS. */
  offset: [number, number, number];
  orientation: [number, number, number];
}

// DayZ-Expansion-Market vehicle purchases can only spawn at a position
// listed in MarketSettings.json's LandSpawnPositions/AirSpawnPositions
// (ExpansionTraderBase.HasVehicleSpawnPosition() searches those lists for
// a clear spot within MaxVehicleDistanceToTrader of the buying trader's
// NPC, failing with "no [air/land] spawn space" otherwise). The shipped
// default entries are clustered near the vanilla trader city, nowhere near
// this custom one, hence the scouted positions below.
//
// 3 scouted flat/clear car spots near the Vehicle Dealer NPC (absolute
// positions converted to CUSTOM_POSITION-relative offsets; orientation is
// [yaw, pitch, roll], matching CUSTOM_NPCS/MarketSettings.json's own
// convention).
const CUSTOM_LAND_VEHICLE_SPAWN_POINTS: VehicleSpawnPoint[] = [
  { offset: [45.933, -8.234, -23.132], orientation: [90.03, -11.09, 6.56] },
  { offset: [45.518, -8.663, -29.127], orientation: [90.03, -11.09, 6.56] },
  { offset: [44.929, -8.807, -34.954], orientation: [90.09, -10.57, -0.17] },
];
// 3 scouted helipads near the Vehicle Dealer NPC (absolute positions
// converted to CUSTOM_POSITION-relative offsets; orientation left at 0 to
// match the scouted heading).
const CUSTOM_AIR_VEHICLE_SPAWN_POINTS: VehicleSpawnPoint[] = [
  { offset: [50.68, -2.23, -2.2], orientation: [0, 0, 0] },
  { offset: [68.12, -6.057, 5.5], orientation: [0, 0, 0] },
  { offset: [76.78, -7.993, -14.5], orientation: [0, 0, 0] },
];

async function removeDefaultZones(): Promise<void> {
  if (!(await exists(TRADERZONES_DIR))) {
    log(
      `${TRADERZONES_DIR} not generated yet - DayZ-Expansion-Market will create it on first ` +
        "server start, nothing to remove yet",
    );
    return;
  }

  let removed = 0;
  for (const file of DEFAULT_ZONE_FILES) {
    const path = `${TRADERZONES_DIR}/${file}`;
    if (await exists(path)) {
      await Deno.remove(path);
      removed++;
    }
  }
  if (removed > 0) {
    ok(`Removed ${removed} default DayZ-Expansion-Market trader zone(s) from ${TRADERZONES_DIR}`);
  }
}

// Loadout files are now static overrides in overrides_profile/ExpansionMod/Loadouts/.
// The overrides copy (ensureOverrides()) runs last in doStart(), overwriting
// anything this would generate, so this function is a no-op stub.
async function ensureCustomTraderGear(): Promise<void> {
  // stub - static overrides in overrides_profile/ExpansionMod/Loadouts/
}

// Trader identity files are now static overrides in overrides_profile/ExpansionMod/Traders/.
async function ensureCustomTraderIdentities(): Promise<void> {
  // stub - static overrides in overrides_profile/ExpansionMod/Traders/
}

// DayZ-Expansion-Market ships 17 default trader identities (Weapons,
// Clothing, Consumables, etc. - untouched by ensureCustomTraderIdentities()
// above, kept "for later use" per this file's own header comment) whose own
// "Categories" arrays reference the mod's PRE-MERGE category names
// (Assault_Rifles, Helmets, Food, ...). src/market.ts's category merge
// (MERGED_CATEGORIES) consolidates/renames every one of those into a new
// set (Guns_Military, Clothing_Head_Civilian, Consumables, ...) and
// quarantines the old source file (renamed to ".orphaned-source" - see
// market.ts's quarantineConsumedSourceCategories()), so every one of these
// 17 defaults' old category references now point at a filename that no
// longer exists - confirmed in the RPT log as a wall of "TRADER
// CONFIGURATION ERROR: Category X in Y does not exist!" on every boot.
// None of these 17 are currently referenced by a live NPC (only
// "Everything"/"Vehicle" from CUSTOM_TRADER_IDENTITIES are), so this is
// harmless today, but leaves them broken if ever activated, and spams the
// log every single boot. Fixed by rewriting each stale entry to the new
// merged category name(s) that now contain the same items (a couple of old
// categories split into a Military/Civilian pair post-merge, so those map
// to two new entries instead of one) - restores the "left ready for later
// use" promise instead of leaving it quietly broken.
const ORPHANED_CATEGORY_REPLACEMENTS: Record<string, string[]> = {
  // Weapons
  Assault_Rifles: ["Guns_Military"],
  Submachine_Guns: ["Guns_Military", "Guns_Civilian"],
  Rifles: ["Guns_Military", "Guns_Civilian"],
  Pistols: ["Guns_Military", "Guns_Civilian"],
  Sniper_Rifles: ["Guns_Military", "Guns_Civilian"],
  Shotguns: ["Guns_Military", "Guns_Civilian"],
  Crossbows: ["Guns_Civilian"],
  Melee_Weapons: ["Tools_And_Melee"],
  Ammo: ["Gun_Ammo"],
  Ammo_Boxes: ["Gun_Ammo"],
  Knifes: ["Tools_And_Melee"],
  Magazines: ["Gun_Attachments_Military", "Gun_Attachments_Civilian"],
  Muzzles: ["Gun_Attachments_Military", "Gun_Attachments_Civilian"],
  Bayonets: ["Gun_Attachments_Military", "Gun_Attachments_Civilian"],
  Optics: ["Gun_Attachments_Military", "Gun_Attachments_Civilian"],
  Buttstocks: ["Gun_Attachments_Military", "Gun_Attachments_Civilian"],
  Handguards: ["Gun_Attachments_Military"],
  Explosives_And_Grenades: ["Explosives"],
  // Bulk of Lights'/Electronics' items land in Utility post-merge (a
  // handful of specific classnames - universallight/tlrlight/nvgoggles -
  // were split into Gun_Attachments_Military/Clothing_Head_Military
  // instead, but Utility covers everything else in both categories).
  Lights: ["Utility"],
  Electronics: ["Utility"],
  // Clothing
  Helmets: ["Clothing_Head_Military", "Clothing_Head_Civilian"],
  Caps: ["Clothing_Head_Military", "Clothing_Head_Civilian"],
  Hats_And_Hoods: ["Clothing_Head_Military", "Clothing_Head_Civilian"],
  Masks: ["Clothing_Head_Military", "Clothing_Head_Civilian"],
  Eyewear: ["Clothing_Head_Military", "Clothing_Head_Civilian"],
  Coats_And_Jackets: ["Clothing_Top_Military", "Clothing_Top_Civilian"],
  Shirts_And_TShirts: ["Clothing_Top_Military", "Clothing_Top_Civilian"],
  Sweaters_And_Hoodies: ["Clothing_Top_Military", "Clothing_Top_Civilian"],
  Vests: ["Clothing_Top_Military", "Clothing_Top_Civilian"],
  Blouses_And_Suits: ["Clothing_Top_Civilian"],
  Pants_And_Shorts: ["Clothing_Bottom_Military", "Clothing_Bottom_Civilian"],
  Boots_And_Shoes: ["Clothing_Bottom_Military", "Clothing_Bottom_Civilian"],
  Skirts_And_Dresses: ["Clothing_Bottom_Civilian"],
  Backpacks: ["Clothing_Back_Military", "Clothing_Back_Civilian"],
  Gloves: ["Clothing_Misc_Military", "Clothing_Misc_Civilian"],
  Armbands: ["Clothing_Misc_Military", "Clothing_Misc_Civilian"],
  Belts: ["Clothing_Misc_Military", "Clothing_Misc_Civilian"],
  Holsters_And_Pouches: ["Clothing_Misc_Military", "Clothing_Misc_Civilian"],
  Bandanas: ["Clothing_Misc_Civilian"],
  // Consumables
  Food: ["Consumables"],
  Drinks: ["Consumables"],
  Fruit_And_Vegetables: ["Consumables"],
  Meat: ["Consumables"],
  Fish: ["Consumables"],
  // Base building / utility
  Tents: ["Base_Building"],
  Locks: ["Base_Building"],
  Containers: ["Base_Building"],
  Flags: ["Base_Building"],
  Furnishings: ["Base_Building"],
  // Supplies got split (bulk crafting mats stayed Uncommon in Base_Building,
  // the rest moved to Utility) - list both, same reasoning as Lights above.
  Supplies: ["Base_Building", "Utility"],
  Gardening: ["Utility"],
  Kits: ["Utility"],
  Navigation: ["Utility"],
  Fishing: ["Utility"],
  Spraycans: ["Utility"],
  Liquids: ["Utility"],
  Tools: ["Tools_And_Melee"],
  // Vehicles
  Cars: ["Vehicles_Cars"],
  Helicopters: ["Vehicles_Helicopters"],
  // Dead per marketGapFill.ts's DEAD_MARKET_FILES (Event/Clothing_Military/
  // Clothing_Civilian/Weapon_Attachments) or never shipped by the mod at
  // all in the first place (Launchers - no Launchers.json ever existed
  // here, orphaned or otherwise) - no real items to point at, so these are
  // just dropped rather than invented.
  Event: [],
  Launchers: [],
  Weapon_Attachments: [],
  Clothing_Military: [],
  Clothing_Civilian: [],
};

function splitCategoryEntry(entry: string): [name: string, suffix: string] {
  const i = entry.indexOf(":");
  return i === -1 ? [entry, ""] : [entry.slice(0, i), entry.slice(i)];
}

interface TraderIdentityFile {
  Categories?: string[];
  [key: string]: unknown;
}

async function fixDefaultTraderIdentityCategories(): Promise<void> {
  if (!(await exists(EXPANSION_TRADERS_DIR))) return; // logged by ensureCustomTraderIdentities() already

  let fixedFiles = 0;
  for await (const entry of Deno.readDir(EXPANSION_TRADERS_DIR)) {
    if (!entry.isFile || !entry.name.endsWith(".json")) continue;
    const path = `${EXPANSION_TRADERS_DIR}/${entry.name}`;
    const data: TraderIdentityFile = JSON.parse(await Deno.readTextFile(path));
    if (!data.Categories || data.Categories.length === 0) continue;

    let replacedAny = false;
    const rebuilt: string[] = [];
    for (const rawEntry of data.Categories) {
      const [name, suffix] = splitCategoryEntry(rawEntry);
      const replacements = ORPHANED_CATEGORY_REPLACEMENTS[name];
      if (replacements === undefined) {
        if (!rebuilt.includes(rawEntry)) rebuilt.push(rawEntry);
        continue;
      }
      replacedAny = true;
      for (const replacement of replacements) {
        const replacementEntry = `${replacement}${suffix}`;
        if (!rebuilt.includes(replacementEntry)) rebuilt.push(replacementEntry);
      }
    }
    if (!replacedAny) continue;

    data.Categories = rebuilt;
    await Deno.writeTextFile(path, JSON.stringify(data, null, 4));
    fixedFiles++;
  }

  if (fixedFiles > 0) {
    ok(
      `Repointed ${fixedFiles} default trader identity file(s) in ${EXPANSION_TRADERS_DIR} at ` +
        "post-merge Market category names (see ORPHANED_CATEGORY_REPLACEMENTS)",
    );
  }
}

// Shape of the zone file this CLI owns. Only m_DisplayName/Position/Radius/
// BuyPricePercent/SellPricePercent are ever written here - Stock is the
// live, real running per-item stock map, populated and persisted by the
// game itself as players buy/sell. m_Version is left untouched too.
interface CustomZoneFile {
  m_Version: number;
  m_DisplayName: string;
  Position: [number, number, number];
  Radius: number;
  BuyPricePercent: number;
  SellPricePercent: number;
  Stock: Record<string, number>;
  [key: string]: unknown;
}

// Custom trader zone and map files are now static overrides:
// overrides_server/mpmissions/expansion/traderzones/CustomTrader.json
// overrides_server/mpmissions/expansion/traders/CustomTrader.map
async function ensureCustomZone(): Promise<void> {
  // stub - static overrides in overrides_server/mpmissions/expansion/
}

// DayZ-Expansion-Core's own SafeZoneSettings.json schema (self-generated
// with Chernarus' default city safe zones already in CircleZones/
// PolygonZones). Only the fields this reads/writes are typed; everything
// else round-trips untouched via the index signature.
interface SafeZoneCircleZone {
  Center: [number, number, number];
  Radius: number;
}

interface SafeZoneSettings {
  CircleZones: SafeZoneCircleZone[];
  PolygonZones?: unknown[];
  CylinderZones?: unknown[];
  [key: string]: unknown;
}

// This project only wants ONE safe zone (the custom trader city) - not the
// half-dozen default Expansion city/airfield/boat-trader zones the mod
// ships with. Those defaults are small individually (175-700m) but add up
// to "you keep wandering into a random no-PvP/no-damage bubble far from
// the actual trader", which reads as "the whole map is a safe zone" the
// first few times it happens. So, unlike removeDefaultZones() above (which
// only ever removes Expansion-Market's default trader NPCs/stock zones),
// this strips every CircleZones/PolygonZones/CylinderZones entry that
// isn't this project's own custom trader zone, every start.
async function ensureCustomTraderSafeZone(): Promise<void> {
  if (!CUSTOM_POSITION) return; // same guard as ensureCustomZone() above

  if (!(await exists(SAFE_ZONE_SETTINGS))) {
    log(
      `${SAFE_ZONE_SETTINGS} not generated yet - DayZ-Expansion-Core will create it on first ` +
        "server start, nothing to add yet",
    );
    return;
  }

  const settings: SafeZoneSettings = JSON.parse(await Deno.readTextFile(SAFE_ZONE_SETTINGS));
  let changed = false;

  const otherCircleZones = settings.CircleZones.filter(
    (z) =>
      Math.abs(z.Center[0] - CUSTOM_POSITION[0]) >= 1 ||
      Math.abs(z.Center[2] - CUSTOM_POSITION[2]) >= 1,
  );
  if (otherCircleZones.length > 0) {
    settings.CircleZones = settings.CircleZones.filter((z) => !otherCircleZones.includes(z));
    changed = true;
  }
  if ((settings.PolygonZones?.length ?? 0) > 0) {
    settings.PolygonZones = [];
    changed = true;
  }
  if ((settings.CylinderZones?.length ?? 0) > 0) {
    settings.CylinderZones = [];
    changed = true;
  }

  const existing = settings.CircleZones.find(
    (z) =>
      Math.abs(z.Center[0] - CUSTOM_POSITION[0]) < 1 &&
      Math.abs(z.Center[2] - CUSTOM_POSITION[2]) < 1,
  );

  if (existing) {
    if (existing.Radius !== CUSTOM_SAFE_ZONE_RADIUS) {
      existing.Radius = CUSTOM_SAFE_ZONE_RADIUS;
      changed = true;
    }
  } else {
    settings.CircleZones.push({ Center: CUSTOM_POSITION, Radius: CUSTOM_SAFE_ZONE_RADIUS });
    changed = true;
  }

  if (!changed) return;
  await Deno.writeTextFile(SAFE_ZONE_SETTINGS, JSON.stringify(settings, null, 4));
  ok(
    `${SAFE_ZONE_SETTINGS}: kept only the ${CUSTOM_SAFE_ZONE_RADIUS}m custom trader city safe ` +
      "zone, removed every other default zone",
  );
}

// DayZ-Expansion-Market's global vehicle-spawn registry (self-generated the
// first time the mission loads, with 5-6 default entries all clustered near
// the vanilla trader city). Only the fields this reads/writes are typed;
// everything else (WaterSpawnPositions, distance settings, etc.) round-trips
// untouched via the index signature.
interface MarketSpawnPosition {
  Position: [number, number, number];
  Orientation: [number, number, number];
}

interface MarketSettings {
  LandSpawnPositions: MarketSpawnPosition[];
  AirSpawnPositions: MarketSpawnPosition[];
  [key: string]: unknown;
}

function ensureVehicleSpawnPositionList(
  list: MarketSpawnPosition[],
  points: VehicleSpawnPoint[],
  customPosition: [number, number, number],
  label: string,
): number {
  let added = 0;
  for (const point of points) {
    const absolute: [number, number, number] = [
      customPosition[0] + point.offset[0],
      customPosition[1] + point.offset[1],
      customPosition[2] + point.offset[2],
    ];
    const alreadyThere = list.some(
      (p) => Math.abs(p.Position[0] - absolute[0]) < 1 && Math.abs(p.Position[2] - absolute[2]) < 1,
    );
    if (alreadyThere) continue;
    list.push({ Position: absolute, Orientation: point.orientation });
    added++;
  }
  if (added > 0) {
    ok(`Added ${added} ${label} vehicle spawn position(s) near the custom trader city`);
  }
  return added;
}

async function ensureCustomVehicleSpawnPositions(): Promise<void> {
  if (!CUSTOM_POSITION) return; // same guard as ensureCustomZone() above
  const customPosition = CUSTOM_POSITION;

  if (
    CUSTOM_LAND_VEHICLE_SPAWN_POINTS.length === 0 &&
    CUSTOM_AIR_VEHICLE_SPAWN_POINTS.length === 0
  ) {
    warn(
      "CUSTOM_LAND_VEHICLE_SPAWN_POINTS/CUSTOM_AIR_VEHICLE_SPAWN_POINTS are both empty - " +
        "vehicle purchases at the custom trader city will fail with 'no air/land spawn space' " +
        "until you scout real, clear positions near the Vehicle Dealer NPC and fill them in " +
        "(see the TODO comment above those constants in src/traders.ts)",
    );
    return;
  }

  if (!(await exists(MARKET_SETTINGS))) {
    log(
      `${MARKET_SETTINGS} not generated yet - DayZ-Expansion-Market will create it on first ` +
        "server start, nothing to add yet",
    );
    return;
  }

  const settings: MarketSettings = JSON.parse(await Deno.readTextFile(MARKET_SETTINGS));
  const addedLand = ensureVehicleSpawnPositionList(
    settings.LandSpawnPositions,
    CUSTOM_LAND_VEHICLE_SPAWN_POINTS,
    customPosition,
    "land",
  );
  const addedAir = ensureVehicleSpawnPositionList(
    settings.AirSpawnPositions,
    CUSTOM_AIR_VEHICLE_SPAWN_POINTS,
    customPosition,
    "air",
  );

  if (addedLand > 0 || addedAir > 0) {
    await Deno.writeTextFile(MARKET_SETTINGS, JSON.stringify(settings, null, 4));
  }
}

// Exchange.json (profiles/ExpansionMod/Market/) is DayZ-Expansion-Market's
// dedicated currency category (IsExchange: 1 - market.ts's
// writeMergedCategory() always sets IsExchange: 0 for every other managed
// category, deliberately leaving this one alone).
interface ExchangeCategory {
  m_Version: number;
  DisplayName: string;
  Icon: string;
  Color: string;
  IsExchange: number;
  InitStockPercent: number;
  Items: {
    ClassName: string;
    MaxPriceThreshold: number;
    MinPriceThreshold: number;
    SellPricePercent: number;
    MaxStockThreshold: number;
    MinStockThreshold: number;
    QuantityPercent: number;
    SpawnAttachments: unknown[];
    Variants: unknown[];
  }[];
}

// Makes GOLD_CURRENCY_CLASSNAME the one and only currency, both at the
// trader (Exchange.json) and at the ATM (MarketSettings.json's own
// separate Currencies list) - trader currency and ATM currency are two
// independently-configured lists, not derived from each other.
// Exchange.json is now a static override in overrides_profile/ExpansionMod/Market/.
async function ensureGoldCoinCurrency(): Promise<void> {
  // stub - static override in overrides_profile/ExpansionMod/Market/Exchange.json
}

// SellPricePercent is now set via static overrides that copy after TS code runs.
// Note: this function still modifies MarketSettings.json in the mission dir,
// but the override copy (ensureOverrides()) overwrites it last.
async function ensureHardcoreSellPricePercent(): Promise<void> {
  // stub - static overrides in overrides_server/mpmissions/
}

export async function ensureCustomTrader(): Promise<void> {
  await removeDefaultZones();
  await ensureCustomTraderIdentities();
  await fixDefaultTraderIdentityCategories();
  await ensureCustomTraderGear();
  await ensureCustomZone();
  await ensureCustomTraderSafeZone();
  await ensureCustomVehicleSpawnPositions();
  await ensureGoldCoinCurrency();
  await ensureHardcoreSellPricePercent();
  await clampTraderStockToMarketCaps();
}

// Safety net: rebalancing src/market.ts's tier caps (TIER_MAX_STOCK) only
// ever changes the cap going forward - it never touches the live Stock
// numbers already sitting in the zone file, since those are the game's own
// persisted per-item quantities (see CustomZoneFile's own comment above -
// never rebuilt from scratch on purpose). If a cap is later lowered,
// existing stock can end up sitting above the new cap, which leaves those
// items looking broken/unavailable to buy in-game since the trader UI has
// no defined behavior for stock exceeding its own configured cap. Runs
// after ensureCustomZone() on every server start, clamping any classname
// whose live stock exceeds its current MaxStockThreshold (scanning only
// the real merged categories, MANAGED_MARKET_CATEGORIES from market.ts) -
// a cheap, idempotent no-op once nothing is over-cap.
async function clampTraderStockToMarketCaps(): Promise<void> {
  if (!(await exists(EXPANSION_MARKET_DIR))) return;

  const zonePath = `${TRADERZONES_DIR}/${CUSTOM_ZONE_NAME}.json`;
  if (!(await exists(zonePath))) return;

  const zone: CustomZoneFile = JSON.parse(await Deno.readTextFile(zonePath));
  if (!zone.Stock || Object.keys(zone.Stock).length === 0) return;

  const caps = new Map<string, number>(); // lowercased classname -> current MaxStockThreshold
  for (const categoryName of MANAGED_MARKET_CATEGORIES) {
    const path = `${EXPANSION_MARKET_DIR}/${categoryName}.json`;
    if (!(await exists(path))) continue;
    const data: { Items?: { ClassName?: string; MaxStockThreshold?: number }[] } = JSON.parse(
      await Deno.readTextFile(path),
    );
    for (const item of data.Items ?? []) {
      if (!item.ClassName || item.MaxStockThreshold === undefined) continue;
      // Only these real, merged categories are authoritative - deliberately
      // not scanning every file under EXPANSION_MARKET_DIR, since the raw
      // per-slot source files DayZ-Expansion-Market ships keep their own,
      // unrelated stale default MaxStockThreshold for the same classname.
      caps.set(item.ClassName.toLowerCase(), item.MaxStockThreshold);
    }
  }

  let clamped = 0;
  for (const [key, stock] of Object.entries(zone.Stock)) {
    const cap = caps.get(key);
    if (cap !== undefined && stock > cap) {
      zone.Stock[key] = cap;
      clamped++;
    }
  }

  if (clamped > 0) {
    await Deno.writeTextFile(zonePath, JSON.stringify(zone, null, 4));
    ok(`Clamped ${clamped} trader item(s) whose live stock exceeded their current cap`);
  }
}
