#!/usr/bin/env -S deno run -A

/**
 * Parses `dayz_class_name.xml` (HTML from dayzexplorer.zeroy.com/hierarchy.html)
 * and generates `src/constants/types/classNames.ts` with two union types:
 *
 *   - BaseClassNames: top-level classes (depth 0 in the hierarchy tree)
 *   - ClassNames:     every class, base + inherited
 */

const XML_PATH = new URL("../dayz_class_name.xml", import.meta.url);
const TS_PATH = new URL("../src/constants/types/classNames.ts", import.meta.url);

const xml = await Deno.readTextFile(XML_PATH);
const lines = xml.split("\n");

// Each row is one line:
//   <tr id="row_6_0_12_0_14_1_0_" class="even">
//     <td class="entry">...<a class="el" ...>ActionEat</a></td>...
//   </tr>
//
// Depth = number of segments in the id minus 1 (row_0_ => depth 0)
// Some base classes are <b>Name</b> (no link). Most are <a class="el" ...>Name</a>.

// Engine primitive / type names that aren't real DayZ classes
const SKIP = new Set([
  "array",
  "bool",
  "float",
  "func",
  "map",
  "multiMap",
  "set",
  "string",
  "typename",
  "vector",
  // templated types like "array&lt; Class T &gt;"
]);

// Collect unique class names, keeping the shallowest depth
const seen = new Map<string, number>();

for (const line of lines) {
  // Extract row id to determine depth
  const idMatch = line.match(/id="row_([^"]+)"/);
  if (!idMatch) continue;

  const segments = idMatch[1].split("_").filter(Boolean);
  const depth = segments.length - 1;

  // Extract class name
  // Anchor: <a class="el" ...>Name</a>  (more attrs between class and >)
  const anchorMatch = line.match(/<a[^>]*class="el"[^>]*>([^<]+)<\/a>/);
  // Bold: <b>Name</b> (used for root classes without links)
  const boldMatch = line.match(/<b>([^<]+)<\/b>/);

  const name = anchorMatch?.[1] ?? boldMatch?.[1];
  // Skip templated/generic types (contain `<` or `&lt;`)
  if (name && !SKIP.has(name) && !name.includes("<") && !name.includes("&lt;")) {
    const existing = seen.get(name);
    if (existing === undefined || depth < existing) {
      seen.set(name, depth);
    }
  }
}

const baseClasses = [...seen.entries()]
  .filter(([, depth]) => depth === 0)
  .map(([name]) => name)
  .sort();

const allClasses = [...seen.keys()].sort();

// Action subclasses: names starting with "Action" or "FirearmAction" but NOT at depth 0
// (depth-0 classes like ActionBase, ActionContinuousBase, FirearmActionBase are base roots)
const actionClasses = [...seen.entries()]
  .filter(([, depth]) => depth > 0)
  .filter(([name]) => name.startsWith("Action") || name.startsWith("FirearmAction"))
  .map(([name]) => name)
  .sort();

// Generate the TypeScript file
const joinUnion = (names: string[]) => ' =\n  "' + names.join('" |\n  "') + '"';

const tsContent = `// Auto-generated by src/dayz-classnames.ts
// Source: dayz_class_name.xml (from https://dayzexplorer.zeroy.com/hierarchy.html)

export type BaseClassName${joinUnion(baseClasses)};

export type ClassName${joinUnion(allClasses)};

export type ClassNameAction${joinUnion(actionClasses)};
`;

await Deno.writeTextFile(TS_PATH, tsContent);

console.log(`✅ Generated classNames.ts`);
console.log(`   BaseClassName:   ${baseClasses.length} classes`);
console.log(`   ClassName:       ${allClasses.length} classes`);
console.log(`   ClassNameAction: ${actionClasses.length} classes`);
