// Admin access for quickly testing AI in-game:
//   1) DayZ-Expansion-AI's own admin menu (T key) - spawn companions, set
//      waypoints, export patrols. Gated by SteamID64 in AISettings.json.
//   2) Community Online Tools (COT) - teleport, free camera, spawn
//      vehicles/items. Gated per-player by a JSON file under
//      PermissionsFramework/Players/, named after the player's internal
//      identity id (NOT their SteamID64).
//
// Both files are self-regenerated by their respective mods, so we only ever
// merge into them once they exist - never overwrite an admin's own tuning.
//
// COT keybinds once admin in-game: Y = toolbar menu, INSERT = free camera,
// H = teleport to where you're looking, END = toggle keybindings.

import { AI_SETTINGS, COT_PLAYERS_DIR, PROFILE_DIR } from "./paths.ts";
import { ask, log, ok, warn } from "./ui.ts";
import { exists } from "./steam.ts";

interface AISettingsFile {
  Admins?: string[];
  [key: string]: unknown;
}

/** Add a SteamID64 to DayZ-Expansion-AI's admin menu allowlist. */
export async function grantAIMenuAdmin(steamId64: string): Promise<void> {
  if (!(await exists(AI_SETTINGS))) {
    log(
      `AISettings.json not generated yet at ${AI_SETTINGS} — start the server once first`,
    );
    return;
  }
  const settings: AISettingsFile = JSON.parse(
    await Deno.readTextFile(AI_SETTINGS),
  );
  settings.Admins ??= [];
  if (settings.Admins.includes(steamId64)) {
    ok(`${steamId64} is already an AI-menu admin`);
    return;
  }
  settings.Admins.push(steamId64);
  await Deno.writeTextFile(AI_SETTINGS, JSON.stringify(settings, null, 4));
  ok(`Added ${steamId64} to Admins in ${AI_SETTINGS} — press T in-game to open the AI menu`);
}

interface ConnectedPlayer {
  name: string;
  steamId64?: string;
  cotId?: string;
}

const STEAM_ID_RE = /^\d{17}$/;

/**
 * Scan every `.ADM` admin log in the profile dir for player connect lines
 * and group the ids seen by player name (requires `-adminlog`). The `id=`
 * field isn't a consistent format: some lines carry the raw SteamID64,
 * others carry COT's internal identity hash. We bucket by shape so callers
 * get whichever id(s) each mod actually needs.
 */
export async function findConnectedPlayers(): Promise<ConnectedPlayer[]> {
  const byName = new Map<string, ConnectedPlayer>();
  const re = /Player "([^"]+)" \(id=([A-Za-z0-9+/]+)=*[\s)]/g;
  for await (const entry of Deno.readDir(PROFILE_DIR)) {
    if (!entry.isFile || !entry.name.endsWith(".ADM")) continue;
    let text: string;
    try {
      text = await Deno.readTextFile(`${PROFILE_DIR}/${entry.name}`);
    } catch {
      continue;
    }
    for (const m of text.matchAll(re)) {
      const name = m[1];
      const id = m[2];
      const player = byName.get(name) ?? { name };
      if (STEAM_ID_RE.test(id)) player.steamId64 = id;
      else player.cotId = id;
      byName.set(name, player);
    }
  }
  return [...byName.values()];
}

interface CotPlayerFile {
  Roles: string[];
}

/** Whether `id` currently has the COT "admin" role. */
async function cotIsAdmin(id: string): Promise<boolean> {
  const path = `${COT_PLAYERS_DIR}/${id}.json`;
  if (!(await exists(path))) return false;
  try {
    const file: CotPlayerFile = JSON.parse(await Deno.readTextFile(path));
    return (file.Roles ?? []).includes("admin");
  } catch {
    return false;
  }
}

/** Grant a player the COT "admin" role (creates/merges their Players/ file). */
export async function grantCotAdmin(id: string): Promise<void> {
  await Deno.mkdir(COT_PLAYERS_DIR, { recursive: true });
  const path = `${COT_PLAYERS_DIR}/${id}.json`;
  let file: CotPlayerFile = { Roles: ["everyone"] };
  if (await exists(path)) {
    file = JSON.parse(await Deno.readTextFile(path));
    file.Roles ??= [];
  }
  if (file.Roles.includes("admin")) {
    ok(`${id} is already a COT admin`);
    return;
  }
  file.Roles.push("admin");
  await Deno.writeTextFile(path, JSON.stringify(file, null, 4));
  ok(`Granted COT admin to ${id} — press Y in-game to open the admin toolbar`);
}

/**
 * Interactive helper: `deno task admin` — grant yourself (or another
 * player) admin access to test AI quickly, via both AI-menu and COT.
 */
export async function doAdmin(): Promise<void> {
  const players = await findConnectedPlayers();
  if (players.length === 0) {
    warn(
      "No players found in any .ADM log yet. Join the server once first " +
        "(with -adminlog, on by default), then re-run 'deno task admin'.",
    );
    return;
  }

  log("Players seen in admin logs:");
  for (const [i, p] of players.entries()) {
    const isAdmin = p.cotId ? await cotIsAdmin(p.cotId) : false;
    const bits: string[] = [];
    if (p.steamId64) bits.push(`SteamID64=${p.steamId64}`);
    if (p.cotId) bits.push(`COT id=${p.cotId}`);
    if (isAdmin) bits.push("already COT admin");
    console.log(`  ${i + 1}) ${p.name}  (${bits.join(", ")})`);
  }

  const choice = await ask("Grant admin to which # (blank to cancel)", "");
  if (!choice) return;
  const idx = Number(choice) - 1;
  const player = players[idx];
  if (!player) {
    warn(`Not a valid choice: ${choice}`);
    return;
  }

  if (player.cotId) {
    await grantCotAdmin(player.cotId);
  } else {
    warn(
      `No COT identity id seen yet for ${player.name} — join once more with ` +
        "@Community-Online-Tools active, then re-run to grant COT admin too.",
    );
  }

  const steamId64 = player.steamId64 ||
    (await ask(
      `${player.name}'s SteamID64, for the Expansion AI menu too (blank to skip)`,
      "",
    ));
  if (steamId64) await grantAIMenuAdmin(steamId64);
}
