// Makes the world colder the further north-west you travel on Chernarus,
// via DDP Server Climate Zones (@DDP-Climate-Zones) - a server-side-only mod
// that overrides WorldData.GetTemperature() for any circular zone defined in
// its own self-generated Config.json (confirmed via its own Steam page:
// supports multiple overlapping circular zones, each with a Priority - higher
// wins on overlap, tie-broken by smaller Radius - a BlendDistance for a
// smooth transition at its own outer edge, and either an absolute
// Temperature or a relative TemperatureOffset added to vanilla weather).
//
// The mod only supports circles, not an arbitrary line/diagonal, so a true
// "north-west half is one temperature, south-east half is another" hard
// split isn't something its schema can express. Instead, this lays down 3
// concentric rings all centered on the same point deep in the NW quadrant,
// each larger and milder than the last (highest Priority/coldest innermost,
// down to lowest Priority/mildest outermost) - overlapping circles plus
// per-zone BlendDistance approximates a radial gradient that reads as
// "colder the further NW you go" and fades back to unmodified vanilla
// temperature (the map's natural summer baseline) once you're outside all
// three rings, i.e. through the middle of the map and into the SE.
//
// Chernarus/Chernarus+ is a 15360x15360m terrain (well-established map fact,
// not mod-specific) - the NW quadrant's geometric center is (3840, 11520)
// (X in [0, 7680], Z in [7680, 15360]). Nudged slightly further NW from that
// exact quadrant-center toward the Tisy/Zub Castle high country (a real,
// already-used-elsewhere-in-this-project landmark - see ai/
// AIPatrolSettings.json's own Roaming_Bandits_Tisy waypoint) so the coldest
// point lands somewhere recognizable rather than an arbitrary empty-map
// coordinate.
//
// Self-generated by the mod on first world load (with its own default
// example zones) - like the other AI-event mods in aiWorldEvents.ts, this
// waits for that file to exist and only ever appends zones by name, never
// touching an existing entry (including the mod's own shipped examples or
// anything an admin has since hand-edited).

import { CLIMATE_ZONES_SETTINGS } from "./paths.ts";
import { log, ok } from "./ui.ts";
import { exists } from "./steam.ts";

interface ClimateZone {
  Name: string;
  Enabled: number;
  Priority: number;
  Center: [number, number, number];
  Radius: number;
  BlendDistance: number;
  UseAbsoluteTemperature: number;
  Temperature: number;
  TemperatureOffset: number;
}

interface ClimateZonesConfig {
  ConfigVersion?: number;
  EnableDebugLogs?: boolean;
  Zones?: ClimateZone[];
  [key: string]: unknown;
}

// Coldest point: NW quadrant center (3840, 11520), nudged toward the
// Tisy/Zub Castle high country. Must be a 3-element numeric array, not a
// "x y z" string - confirmed via the mod's own pre-populated example zones
// (TisyColdZone/WarmSwamp) and the hard way via a live crash: passing a
// string here reaches CustomMission.ReadFromString expecting a vector and
// throws an unhandled exception in DDP_ServerClimateZones's own
// LoadClimateConfig on the very next boot, killing the whole server before
// it can finish loading.
const NW_COLD_CENTER: [number, number, number] = [3200, 0, 12300];

const NW_GRADIENT_ZONES: ClimateZone[] = [
  {
    Name: "DZSurvival_NW_ColdCore",
    Enabled: 1,
    Priority: 100,
    Center: NW_COLD_CENTER,
    Radius: 3000,
    BlendDistance: 1500,
    UseAbsoluteTemperature: 0,
    Temperature: 0,
    TemperatureOffset: -14,
  },
  {
    Name: "DZSurvival_NW_ColdMid",
    Enabled: 1,
    Priority: 60,
    Center: NW_COLD_CENTER,
    Radius: 6500,
    BlendDistance: 2500,
    UseAbsoluteTemperature: 0,
    Temperature: 0,
    TemperatureOffset: -8,
  },
  {
    Name: "DZSurvival_NW_ColdOuter",
    Enabled: 1,
    Priority: 20,
    Center: NW_COLD_CENTER,
    Radius: 10500,
    BlendDistance: 3000,
    UseAbsoluteTemperature: 0,
    Temperature: 0,
    TemperatureOffset: -3,
  },
];

export async function ensureClimateZones(): Promise<void> {
  if (!(await exists(CLIMATE_ZONES_SETTINGS))) {
    log(
      `${CLIMATE_ZONES_SETTINGS} not generated yet - DDP Server Climate Zones will create it ` +
        "on first server start",
    );
    return;
  }

  const data: ClimateZonesConfig = JSON.parse(await Deno.readTextFile(CLIMATE_ZONES_SETTINGS));
  data.Zones ??= [];
  const existingNames = new Set(data.Zones.map((z) => z.Name));

  const toAdd = NW_GRADIENT_ZONES.filter((z) => !existingNames.has(z.Name));
  if (toAdd.length === 0) return;

  data.Zones.push(...toAdd);
  await Deno.writeTextFile(CLIMATE_ZONES_SETTINGS, JSON.stringify(data, null, 4));
  ok(
    `Added ${toAdd.length} NW-cold-gradient zone(s) to ${CLIMATE_ZONES_SETTINGS} ` +
      "(coldest deep in the NW quadrant, fading to unmodified vanilla temperature by the SE)",
  );
}
