// Makes the world colder the further north-west you travel on Chernarus,
// via DDP Server Climate Zones (@DDP-Climate-Zones), a server-side-only mod
// that overrides temperature within circular zones defined in its own
// self-generated Config.json (Priority breaks overlap ties, BlendDistance
// smooths the outer edge).
//
// The mod only supports circles, not an arbitrary line/diagonal, so this
// lays down 3 concentric rings centered on the same NW point, each larger
// and milder than the last, approximating a radial "colder the further NW
// you go" gradient that fades to unmodified vanilla temperature outside all
// three rings.
//
// Self-generated by the mod on first world load (with its own default
// example zones) - this waits for that file to exist and only ever appends
// zones by name, never touching an existing entry.

import { CLIMATE_ZONES_SETTINGS } from "./paths.ts";
import { log, ok } from "./ui.ts";
import { exists } from "./steam.ts";

interface ClimateZone {
  Name: string;
  Enabled: number;
  Priority: number;
  Center: [number, number, number];
  Radius: number;
  BlendDistance: number;
  UseAbsoluteTemperature: number;
  Temperature: number;
  TemperatureOffset: number;
}

interface ClimateZonesConfig {
  ConfigVersion?: number;
  EnableDebugLogs?: boolean;
  Zones?: ClimateZone[];
  [key: string]: unknown;
}

// Coldest point: NW quadrant, nudged toward the Tisy/Zub Castle high
// country. Must be a 3-element numeric array, not a "x y z" string - a
// string here crashes DDP_ServerClimateZones's LoadClimateConfig on boot.
const NW_COLD_CENTER: [number, number, number] = [3200, 0, 12300];

const NW_GRADIENT_ZONES: ClimateZone[] = [
  {
    Name: "DZSurvival_NW_ColdCore",
    Enabled: 1,
    Priority: 100,
    Center: NW_COLD_CENTER,
    Radius: 3000,
    BlendDistance: 1500,
    UseAbsoluteTemperature: 0,
    Temperature: 0,
    TemperatureOffset: -14,
  },
  {
    Name: "DZSurvival_NW_ColdMid",
    Enabled: 1,
    Priority: 60,
    Center: NW_COLD_CENTER,
    Radius: 6500,
    BlendDistance: 2500,
    UseAbsoluteTemperature: 0,
    Temperature: 0,
    TemperatureOffset: -8,
  },
  {
    Name: "DZSurvival_NW_ColdOuter",
    Enabled: 1,
    Priority: 20,
    Center: NW_COLD_CENTER,
    Radius: 10500,
    BlendDistance: 3000,
    UseAbsoluteTemperature: 0,
    Temperature: 0,
    TemperatureOffset: -3,
  },
];

export async function ensureClimateZones(): Promise<void> {
  if (!(await exists(CLIMATE_ZONES_SETTINGS))) {
    log(
      `${CLIMATE_ZONES_SETTINGS} not generated yet - DDP Server Climate Zones will create it ` +
        "on first server start",
    );
    return;
  }

  const data: ClimateZonesConfig = JSON.parse(await Deno.readTextFile(CLIMATE_ZONES_SETTINGS));
  data.Zones ??= [];
  const existingNames = new Set(data.Zones.map((z) => z.Name));

  const toAdd = NW_GRADIENT_ZONES.filter((z) => !existingNames.has(z.Name));
  if (toAdd.length === 0) return;

  data.Zones.push(...toAdd);
  await Deno.writeTextFile(CLIMATE_ZONES_SETTINGS, JSON.stringify(data, null, 4));
  ok(
    `Added ${toAdd.length} NW-cold-gradient zone(s) to ${CLIMATE_ZONES_SETTINGS} ` +
      "(coldest deep in the NW quadrant, fading to unmodified vanilla temperature by the SE)",
  );
}
