// DayZ-Expansion-Market tuning: reshapes trader stock across every category
// the custom trader city sells into a hand-classified rarity system
// (Common/Uncommon/Rare/Legendary) instead of DayZ-Expansion-Market's own
// flat per-category defaults (every category ships InitStockPercent: 75.0
// and MaxStockThreshold: 100 regardless of what it sells).
//
// Source categories (Assault_Rifles.json, Helmets.json, etc. - generated by
// DayZ-Expansion-Market and never modified here) are merged/reorganized
// into a curated set (see MERGED_CATEGORIES) with per-item rarity tiers
// driving MaxStockThreshold, BUY_PRICE_MULTIPLIER, and
// SELL_PRICE_PERCENT_OVERRIDE. The companion EnforceScript addon
// (DZSurvivalTraderRestock) infers an item's tier at runtime purely from
// its live MaxStockThreshold (see that addon's TierForCap()) - keep
// TIER_MAX_STOCK below and that addon's thresholds in sync.
//
// Merging reads each source category's still-pristine JSON and writes a
// brand new category file, copying every item's price fields verbatim -
// only MaxStockThreshold (and price, via BUY_PRICE_MULTIPLIER/
// priceOverrides) is ever changed. Source files are never touched directly
// (just quarantined, see quarantineConsumedSourceCategories()), so
// re-running this on every server start regenerates the same output.
//
// IMPORTANT: DayZ-Expansion-Market's LoadCategories() scans its whole
// folder and loads every "*.json" file into one shared global
// classname->item map, independent of whether any trader identity
// references that category - whichever category loads a given classname
// *second* has it silently rejected, not merged. Leaving an old source
// file (e.g. Assault_Rifles.json) in place after merging it into
// MERGED_CATEGORIES would quietly steal its own items back out of the real
// merged category on every boot. quarantineConsumedSourceCategories()
// (called at the end of tuneExpansionMarket()) renames every fully-absorbed
// source file away from ".json" so the folder scan skips it, while
// readCategory() below still reads that same renamed file as this merge's
// data source.
//
// This only ever edits the category *template* files
// (profiles/ExpansionMod/Market/<Category>.json) - used to seed a brand new
// trader zone's starting stock. It never touches the live, per-zone
// running stock (expansion/traderzones/<Zone>.json's own Stock map, written
// by the game itself - see src/traders.ts's ensureCustomZone()), which is
// keyed purely by classname independent of category file, so re-running
// this never resets or lowers anything a player has actually sold in.
//
// Two categories are deliberately left OUT of the merge/tier system:
//   - Ghillies: sale-only (0% init stock, low cap, never auto-restocked) -
//     the only way this ever has stock is a player selling one in.
//   - Vehicle_Parts/Batteries: buying a vehicle also spawns its default
//     attachments (wheels, doors, battery, etc.), drawn from these
//     categories' own per-classname stock, so they need to stay generously
//     stocked - a functional necessity, not a "coveted power" category.

import { EXPANSION_MARKET_DIR } from "./paths.ts";
import { log, ok } from "./ui.ts";
import { exists } from "./steam.ts";
import { DEAD_MARKET_FILES } from "./marketGapFill.ts";

type Tier = "Common" | "Uncommon" | "Rare" | "Legendary";

// Absolute stock cap per tier - also what the companion restock addon
// reverse-engineers an item's tier from at runtime (see this file's header
// comment). Keep these thresholds and that addon's TierForCap() in sync.
export const TIER_MAX_STOCK: Record<Tier, number> = {
  Common: 20,
  Uncommon: 8,
  Rare: 3,
  Legendary: 1,
};

// Buy-price multiplier applied on top of whatever price (DayZ-Expansion-
// Market's own shipped default, or this file's own priceOverride) an item
// would otherwise land on. Buying is unaffected by MarketSettings.json's
// SellPricePercent (the buy path always uses modifier=1.0 -
// ExpansionMarketItem.CalculatePrice()), so this is the only lever for
// making purchases expensive; selling is controlled separately via
// SellPricePercent (see traders.ts's ensureHardcoreSellPricePercent()).
// Common stays at 1.0x since that tier covers the baseline survival loop
// (ammo/food/meds/basic clothes), which is deliberately not penalized.
export const BUY_PRICE_MULTIPLIER: Record<Tier, number> = {
  Common: 1.0,
  Uncommon: 1.5,
  Rare: 2.5,
  Legendary: 3.5,
};

// Per-item sell-price-percent override, layered on top of the global
// SellPricePercent (MarketSettings.json, see traders.ts's
// HARDCORE_SELL_PRICE_PERCENT). Each item's own SellPricePercent takes
// priority over the trader zone's, which takes priority over the global
// setting - all three use -1 as an "inherit the next level up" sentinel
// (ExpansionMarketTrader.GetSellPricePercent()). This project's custom
// zone leaves its own SellPricePercent at -1 (see ensureCustomZone() in
// traders.ts), so a real value here is the only way to make one item sell
// for a different percentage than another. Common/Uncommon inherit the
// 20% global default via -1; Rare/Legendary get an explicit bump so a
// lucky find is worth cashing in.
export const SELL_PRICE_PERCENT_OVERRIDE: Record<Tier, number> = {
  Common: -1,
  Uncommon: -1,
  Rare: 40,
  Legendary: 60,
};

interface SourceGroup {
  source: string;
  tier: Tier;
  only?: string[];
  exclude?: string[];
  overrides?: Record<string, Tier>;
  // Per-classname price correction for items whose DayZ-Expansion-Market
  // default price doesn't match the rarity tier they landed in here (e.g.
  // a reskin that kept a stray generic default instead of matching its
  // base item's real price).
  priceOverrides?: Record<string, { min: number; max: number }>;
  /**
   * Flat SellPricePercent applied to every item in THIS group only, taking
   * priority over both MergedCategory.sellPricePercent and the per-tier
   * SELL_PRICE_PERCENT_OVERRIDE lookup. Use when only one source group in
   * an otherwise mixed category needs its own rate.
   */
  sellPricePercent?: number;
}

interface MergedCategory {
  fileName: string;
  displayName: string;
  icon: string;
  initStockPercent: number;
  groups: SourceGroup[];
  /**
   * Flat SellPricePercent applied to every item in this merged category,
   * overriding the per-tier SELL_PRICE_PERCENT_OVERRIDE lookup entirely.
   * Use for a whole-category rule that isn't tier-dependent.
   */
  sellPricePercent?: number;
}

// ---------------------------------------------------------------------
// Military/Civilian classname splits - hand-classified by actually
// reading profiles/ExpansionMod/Market/<Category>.json. Anything NOT
// listed here for a given source category falls through to the Civilian
// side of that same body-slot/attachment-type category.
// ---------------------------------------------------------------------

const RIFLES_MIL_DMR = ["svd_wooden", "m14"];
const SNIPER_RIFLES_CIVILIAN = ["b95", "scout_chernarus"];
// cz61 (CR-61 Skorpion) is deliberately kept Civilian despite being a
// genuine submachine gun - every other Submachine_Guns item is Military.
const SUBMACHINE_GUNS_CIVILIAN = ["cz61"];

const MIL_HELMETS = [
  "tankerhelmet",
  "zsh3pilothelmet",
  "zsh3pilothelmet_green",
  "zsh3pilothelmet_black",
  "mich2001helmet",
  "gorkahelmetvisor",
  "gorkahelmet",
  "ssh68helmet",
  "ballistichelmet_un",
  "ballistichelmet_navy",
  "ballistichelmet_winter",
];
const MIL_CAPS = ["pilotkacap"];
const MIL_HATS = [
  "militaryberet_chdkz",
  "militaryberet_un",
  "militaryberet_nz",
  "booniehat_dpm",
  "booniehat_dubok",
  "booniehat_flecktran",
  "budenovkahat_gray",
  "officerhat",
  "nbchoodgray",
  "okzkcap_beige",
];
const MIL_MASKS = ["shemag_brown", "balaclavamask_bdu", "gasmask", "gp5gasmask", "airbornemask"];
const MIL_EYEWEAR = ["tacticalgoggles", "nvgheadstrap"];
const MIL_COATS = [
  "ttskojacket_camo",
  "bdujacket",
  "m65jacket_black",
  "m65jacket_olive",
  "gorkaejacket_summer",
  "usmcjacket_desert",
  "nbcjacketgray",
  "omkjacket_navy",
  "navyuniformjacket",
  "pilotjacket_black",
  "wintermilitarycoat_brown",
];
const MIL_SHIRTS = ["telnyashkashirt", "tacticalshirt_grey", "tacticalshirt_black"];
const MIL_SWEATERS = ["militarysweater_chernarus"];
const MIL_VESTS = [
  "ukassvest_black",
  "ukassvest_camo",
  "ukassvest_winter",
  "smershvest",
  "highcapacityvest_black",
  "highcapacityvest_olive",
  "platecarriervest",
  "platecarriervest_camo",
  "platecarriervest_winter",
  "chestplate",
];
const MIL_PANTS = [
  "ttskopants",
  "bdupants",
  "usmcpants_desert",
  "gorkapants_summer",
  "nbcpantsgray",
  "omkpants_navy",
  "navyuniformpants",
];
const MIL_BOOTS = [
  "combatboots_beige",
  "jungleboots_beige",
  "ttskoboots",
  "militaryboots_redpunk",
  "militaryboots_bluerock",
  "militaryboots_beige",
  "militaryboots_black",
  "militaryboots_brown",
  "nbcbootsgray",
  "coldoperationboots_camo",
];
const MIL_BACKPACKS = [
  "smershbag",
  "assaultbag_black",
  "assaultbag_winter",
  "coyotebag_brown",
  "coyotebag_winter",
  "alicebag_green",
  "duffelbagsmall_camo",
  "armypouch_beige",
  "attack2bag_black",
];
const MIL_GLOVES = ["tacticalgloves_black", "nbcglovesgray"];
const MIL_ARMBANDS = ["armband_apa"];
const MIL_BELTS = ["militarybelt"];
const MIL_HOLSTERS = [
  "platecarrierholster",
  "platecarrierholster_camo",
  "platecarrierholster_winter",
  "platecarrierpouches",
  "platecarrierpouches_camo",
  "platecarrierpouches_winter",
];

const MAGAZINES_MIL = [
  "mag_cz61_20rnd",
  "mag_pp19_64rnd",
  "mag_ump_25rnd",
  "mag_mp5_15rnd",
  "mag_mp5_30rnd",
  "mag_fal_20rnd",
  "mag_akm_30rnd",
  "mag_akm_palm30rnd",
  "mag_akm_drum75rnd",
  "mag_ak101_30rnd",
  "mag_ak74_30rnd",
  "mag_ak74_45rnd",
  "mag_stanag_30rnd",
  "mag_stanagcoupled_30rnd",
  "mag_stanag_60rnd",
  "mag_cmag_10rnd",
  "mag_cmag_20rnd",
  "mag_cmag_30rnd",
  "mag_cmag_40rnd",
  "mag_vss_10rnd",
  "mag_val_20rnd",
  "mag_vikhr_30rnd",
  "mag_svd_10rnd",
  "mag_sv98_10rnd",
  "mag_famas_25rnd",
  "mag_aug_30rnd",
  "mag_m14_10rnd",
  "mag_m14_20rnd",
];
const MUZZLES_MIL = ["mp5_compensator", "m4_suppressor", "ak_suppressor"];

// Vanilla magazine prices track their compatible weapon's price, not the
// magazine's own value (e.g. mag_akm_drum75rnd cost more than the akm
// rifle itself) - re-priced below purely by round capacity instead, since
// a magazine is a cheap accessory, never a fraction of buying a whole gun.
// NOTE: these bands are pre-multiplier BASE prices - this group's tier is
// Uncommon (BUY_PRICE_MULTIPLIER 1.5x), so real in-trader prices are 1.5x
// each number below (e.g. TINY's 200-367 base becomes a real 300-550).
const MAGAZINE_BAND_TINY = { min: 200, max: 367 }; // <=10rnd -> real 300-550
const MAGAZINE_BAND_SMALL = { min: 300, max: 500 }; // 11-20rnd -> real 450-750
const MAGAZINE_BAND_MEDIUM = { min: 400, max: 667 }; // 21-30rnd -> real 600-1000
const MAGAZINE_BAND_LARGE = { min: 533, max: 867 }; // 31-45rnd -> real 800-1300
const MAGAZINE_BAND_XLARGE = { min: 733, max: 1200 }; // 46-64rnd -> real 1100-1800
const MAGAZINE_BAND_DRUM = { min: 1000, max: 1667 }; // 65rnd+ -> real 1500-2500
// TGK-WeaponPack's own Sobr_Mag_*/SM_Magazine_*/SM_Mag_* reskins are
// deliberately NOT included here - already flat-priced by
// marketGapFill.ts's TGK_MAGAZINE_PRICE, a separate pricing decision.
const MAGAZINE_PRICE_OVERRIDES: Record<string, { min: number; max: number }> = {
  // Military
  mag_cz61_20rnd: MAGAZINE_BAND_SMALL,
  mag_pp19_64rnd: MAGAZINE_BAND_XLARGE,
  mag_ump_25rnd: MAGAZINE_BAND_MEDIUM,
  mag_mp5_15rnd: MAGAZINE_BAND_SMALL,
  mag_mp5_30rnd: MAGAZINE_BAND_MEDIUM,
  mag_fal_20rnd: MAGAZINE_BAND_SMALL,
  mag_akm_30rnd: MAGAZINE_BAND_MEDIUM,
  mag_akm_palm30rnd: MAGAZINE_BAND_MEDIUM,
  mag_akm_drum75rnd: MAGAZINE_BAND_DRUM,
  mag_ak101_30rnd: MAGAZINE_BAND_MEDIUM,
  mag_ak74_30rnd: MAGAZINE_BAND_MEDIUM,
  mag_ak74_45rnd: MAGAZINE_BAND_LARGE,
  mag_stanag_30rnd: MAGAZINE_BAND_MEDIUM,
  // "coupled" mags (two mags taped together for a fast reload) are priced
  // the same as one 30rnd STANAG mag - the reload convenience isn't worth
  // double the price.
  mag_stanagcoupled_30rnd: MAGAZINE_BAND_MEDIUM,
  mag_stanag_60rnd: MAGAZINE_BAND_XLARGE,
  mag_cmag_10rnd: MAGAZINE_BAND_TINY,
  mag_cmag_20rnd: MAGAZINE_BAND_SMALL,
  mag_cmag_30rnd: MAGAZINE_BAND_MEDIUM,
  mag_cmag_40rnd: MAGAZINE_BAND_LARGE,
  mag_vss_10rnd: MAGAZINE_BAND_TINY,
  mag_val_20rnd: MAGAZINE_BAND_SMALL,
  mag_vikhr_30rnd: MAGAZINE_BAND_MEDIUM,
  mag_svd_10rnd: MAGAZINE_BAND_TINY,
  mag_sv98_10rnd: MAGAZINE_BAND_TINY,
  mag_famas_25rnd: MAGAZINE_BAND_MEDIUM,
  mag_aug_30rnd: MAGAZINE_BAND_MEDIUM,
  mag_m14_10rnd: MAGAZINE_BAND_TINY,
  mag_m14_20rnd: MAGAZINE_BAND_SMALL,
  // Civilian
  mag_pm73_15rnd: MAGAZINE_BAND_SMALL,
  mag_pm73_25rnd: MAGAZINE_BAND_MEDIUM,
  mag_deagle_9rnd: MAGAZINE_BAND_TINY,
  mag_ruger1022_30rnd: MAGAZINE_BAND_MEDIUM,
  mag_p1_8rnd: MAGAZINE_BAND_TINY,
  mag_ij70_8rnd: MAGAZINE_BAND_TINY,
  mag_ruger1022_15rnd: MAGAZINE_BAND_SMALL,
  mag_mkii_10rnd: MAGAZINE_BAND_TINY,
  mag_glock_15rnd: MAGAZINE_BAND_SMALL,
  mag_cz75_15rnd: MAGAZINE_BAND_SMALL,
  mag_cz527_5rnd: MAGAZINE_BAND_TINY,
  mag_scout_5rnd: MAGAZINE_BAND_TINY,
  mag_1911_7rnd: MAGAZINE_BAND_TINY,
  mag_cz550_10rnd: MAGAZINE_BAND_TINY,
  mag_saiga_5rnd: MAGAZINE_BAND_TINY,
  mag_saiga_8rnd: MAGAZINE_BAND_TINY,
  mag_ssg82_5rnd: MAGAZINE_BAND_TINY,
  mag_fnx45_15rnd: MAGAZINE_BAND_SMALL,
  // Actual capacity is 20rnd despite the "drum" name - priced by real
  // capacity, not the name.
  mag_saiga_drum20rnd: MAGAZINE_BAND_SMALL,
};

// m4_suppressor/ak_suppressor (the plain vanilla suppressors) were priced
// higher than every one of their own TGK-WeaponPack reskinned variants
// (already 3500-6000 via marketGapFill.ts's TGK price fixes) - re-priced
// to match, since a plain item costing more than every skin of itself
// makes no sense.
const MUZZLE_PRICE_OVERRIDES: Record<string, { min: number; max: number }> = {
  m4_suppressor: { min: 2334, max: 4000 },
  ak_suppressor: { min: 2334, max: 4000 },
};
const HANDGUARDS_MIL = [
  "mp5_plastichndgrd",
  "mp5_railhndgrd",
  "ak74_hndgrd",
  "ak_woodhndgrd",
  "ak_railhndgrd",
  "ak_plastichndgrd",
  "m4_plastichndgrd",
  "m4_rishndgrd",
  "m4_mphndgrd",
];
const BUTTSTOCKS_MIL = [
  "mp5k_stockbttstck",
  "fal_oebttstck",
  "fal_foldingbttstck",
  "aks74u_bttstck",
  "ak74_woodbttstck",
  "ak_plasticbttstck",
  "ak_woodbttstck",
  "ak_foldingbttstck",
  "m4_oebttstck",
  "m4_mpbttstck",
  "m4_cqbbttstck",
  "pp19_bttstck",
];
const BAYONETS_MIL = ["m9a1_bayonet", "ak_bayonet"];
const OPTICS_MIL = [
  "m4_carryhandleoptic",
  "buisoptic",
  "m4_t3nrdsoptic",
  "m68optic",
  "acogoptic",
  "acogoptic_6x",
  "kobraoptic",
  "kashtanoptic",
  "pso1optic",
  "pso11optic",
  "pso6optic",
  "kazuaroptic",
  "mk4optic_black",
  "starlightoptic",
];

const SUPPLIES_BASE_BUILDING = [
  "rope",
  "metalwire",
  "epoxyputty",
  "ducttape",
  "woodenplank",
  "metalplate",
  "nailbox",
  "nail",
  "barbedwire",
  "camonet",
  "hescobox",
  "powergenerator",
  "tripod",
];

// ---------------------------------------------------------------------
// Merged/reorganized categories. src/traders.ts's CUSTOM_TRADER_IDENTITIES
// should reference these fileNames (not the ~50 original source
// categories).
// ---------------------------------------------------------------------
const MERGED_CATEGORIES: MergedCategory[] = [
  {
    fileName: "Guns_Military",
    displayName: "Guns - Military",
    icon: "Deliver",
    // Guns start with zero stock, no exceptions - the trader should never
    // be a free/repeatable source of weapons after a death; everything a
    // player buys here has to first be restocked (slowly, capped low) or
    // sold in by another player.
    initStockPercent: 0,
    groups: [
      {
        source: "Assault_Rifles",
        tier: "Rare",
        // ak101/m16a2/famas/augshort and m4a1/aug shared accidental low
        // default prices that put them below several civilian pistols
        // (e.g. fnx45 alone: 7058-11768) - re-based to sit solidly above
        // every pistol/SMG in the trader, in line with this group's own
        // ak74/akm/fal. sawedofffamas is deliberately left untouched - like
        // every other "sawed off" variant in this trader, it's meant to be
        // its family's cheapest, junk-tier novelty.
        priceOverrides: {
          ak101: { min: 5500, max: 9200 },
          m16a2: { min: 5500, max: 9200 },
          famas: { min: 5500, max: 9200 },
          augshort: { min: 5500, max: 9200 },
          m4a1: { min: 5300, max: 8800 },
          aug: { min: 5300, max: 8800 },
        },
      },
      { source: "Submachine_Guns", tier: "Uncommon", exclude: SUBMACHINE_GUNS_CIVILIAN },
      { source: "Sniper_Rifles", tier: "Legendary", exclude: SNIPER_RIFLES_CIVILIAN },
      { source: "Rifles", tier: "Rare", only: RIFLES_MIL_DMR },
      // deagle and saiga moved here from Guns_Civilian - relocated via
      // only/exclude on the shared Pistols/Shotguns source groups rather
      // than duplicating those groups' full item lists. deagle also gets
      // an explicit priceOverride since its DayZ-Expansion-Market default
      // made it the single cheapest civilian pistol in the whole trader,
      // nowhere near its intended value. saiga is a separate group at its
      // own original Uncommon tier, unchanged - only its category moves.
      {
        source: "Pistols",
        tier: "Rare",
        only: ["deagle"],
        priceOverrides: { deagle: { min: 10000, max: 10000 } },
      },
      { source: "Shotguns", tier: "Uncommon", only: ["saiga"] },
    ],
  },
  {
    fileName: "Guns_Civilian",
    displayName: "Guns - Civilian",
    icon: "Deliver",
    // See Guns_Military's own comment - zero starting stock applies to
    // every gun, civilian or military.
    initStockPercent: 0,
    groups: [
      { source: "Rifles", tier: "Uncommon", exclude: RIFLES_MIL_DMR },
      // Common tier deliberately removed from guns entirely - even the
      // most basic civilian shotgun can kill a player, so no gun should
      // regenerate as freely as a t-shirt. Every gun in the trader now
      // caps out at 10 (Uncommon) at most.
      // saiga excluded - moved to Guns_Military (see that category's own
      // comment).
      { source: "Shotguns", tier: "Uncommon", exclude: ["saiga"] },
      { source: "Crossbows", tier: "Uncommon" },
      // deagle excluded - moved to Guns_Military (see that category's own
      // comment). engraved1911 ("engraved Kolt") re-priced: its real
      // default put it above several rifles at this tier's 1.5x multiplier.
      {
        source: "Pistols",
        tier: "Uncommon",
        exclude: ["deagle"],
        priceOverrides: { engraved1911: { min: 3333, max: 3333 } },
      },
      { source: "Sniper_Rifles", tier: "Uncommon", only: SNIPER_RIFLES_CIVILIAN },
      { source: "Submachine_Guns", tier: "Uncommon", only: SUBMACHINE_GUNS_CIVILIAN },
    ],
  },
  {
    fileName: "Gun_Ammo",
    displayName: "Gun Ammo",
    icon: "Deliver",
    initStockPercent: 40,
    groups: [
      {
        source: "Ammo",
        tier: "Common",
        // 40mm underslung grenade launcher rounds are far more dangerous
        // than other Common-tier ammo - Rare tier matches both their real
        // lethality and existing default price.
        overrides: { ammo_40mm_explosive: "Rare", Ammo_40mm_Chemgas: "Rare" },
      },
      { source: "Ammo_Boxes", tier: "Uncommon" },
    ],
  },
  {
    fileName: "Gun_Attachments_Military",
    displayName: "Gun Attachments - Military",
    icon: "Deliver",
    initStockPercent: 20,
    // Attachments sell for a flat 50% of buy price, overriding the
    // per-tier sell percents (20/40/60) this category would otherwise
    // inherit.
    sellPricePercent: 50,
    groups: [
      {
        source: "Magazines",
        tier: "Uncommon",
        only: MAGAZINES_MIL,
        priceOverrides: MAGAZINE_PRICE_OVERRIDES,
      },
      {
        source: "Muzzles",
        tier: "Uncommon",
        only: MUZZLES_MIL,
        priceOverrides: MUZZLE_PRICE_OVERRIDES,
      },
      { source: "Handguards", tier: "Uncommon", only: HANDGUARDS_MIL },
      { source: "Buttstocks", tier: "Uncommon", only: BUTTSTOCKS_MIL },
      { source: "Bayonets", tier: "Uncommon", only: BAYONETS_MIL },
      {
        source: "Optics",
        tier: "Uncommon",
        only: OPTICS_MIL,
        overrides: {
          acogoptic: "Rare",
          acogoptic_6x: "Rare",
          pso1optic: "Rare",
          pso11optic: "Rare",
          pso6optic: "Rare",
          kashtanoptic: "Rare",
          kazuaroptic: "Rare",
          mk4optic_black: "Rare",
          starlightoptic: "Legendary",
        },
      },
      // universallight/tlrlight are real weapon rail-mounted flashlight/
      // laser combos, moved here from Utility's own Lights group - priced/
      // tiered like every other Uncommon attachment here (and covered by
      // this category's flat 50% sell rule above).
      { source: "Lights", tier: "Uncommon", only: ["universallight", "tlrlight"] },
    ],
  },
  {
    fileName: "Gun_Attachments_Civilian",
    displayName: "Gun Attachments - Civilian",
    icon: "Deliver",
    initStockPercent: 30,
    // Same flat "sell for half of buy price" rule as Gun_Attachments_
    // Military above.
    sellPricePercent: 50,
    groups: [
      {
        source: "Magazines",
        tier: "Uncommon",
        exclude: MAGAZINES_MIL,
        priceOverrides: MAGAZINE_PRICE_OVERRIDES,
      },
      { source: "Muzzles", tier: "Uncommon", exclude: MUZZLES_MIL },
      { source: "Buttstocks", tier: "Uncommon", exclude: BUTTSTOCKS_MIL },
      { source: "Bayonets", tier: "Uncommon", exclude: BAYONETS_MIL },
      { source: "Optics", tier: "Uncommon", exclude: OPTICS_MIL },
    ],
  },
  {
    fileName: "Explosives",
    displayName: "Explosives",
    icon: "Deliver",
    initStockPercent: 10,
    groups: [{ source: "Explosives_And_Grenades", tier: "Rare" }],
  },
  {
    fileName: "Clothing_Head_Military",
    displayName: "Clothing Head - Military",
    icon: "Deliver",
    initStockPercent: 15,
    groups: [
      {
        source: "Helmets",
        tier: "Rare",
        only: MIL_HELMETS,
        overrides: {
          mich2001helmet: "Legendary",
          ballistichelmet_un: "Legendary",
          ballistichelmet_navy: "Legendary",
          ballistichelmet_winter: "Legendary",
        },
        // Color variants of the base zsh3pilothelmet kept a stray old/
        // generic default price instead of matching their own base item -
        // repriced to match.
        priceOverrides: {
          zsh3pilothelmet_green: { min: 6925, max: 11545 },
          zsh3pilothelmet_black: { min: 6925, max: 11545 },
        },
      },
      {
        source: "Caps",
        tier: "Uncommon",
        only: MIL_CAPS,
      },
      {
        source: "Hats_And_Hoods",
        tier: "Uncommon",
        only: MIL_HATS,
        // Underpriced relative to every other Uncommon-tier military hat
        // here - repriced to match militaryberet_un/nz, a comparable
        // plain-cloth military headwear item in the same tier.
        priceOverrides: { budenovkahat_gray: { min: 1060, max: 1770 } },
      },
      {
        source: "Masks",
        tier: "Uncommon",
        only: MIL_MASKS,
        overrides: { gasmask: "Legendary", gp5gasmask: "Legendary" },
        // Underpriced relative to every other Uncommon-tier face covering
        // here - repriced to match airbornemask, a comparable cloth/fabric
        // face covering in the same tier.
        priceOverrides: { shemag_brown: { min: 460, max: 765 } },
      },
      {
        source: "Eyewear",
        tier: "Uncommon",
        only: MIL_EYEWEAR,
        overrides: { nvgheadstrap: "Legendary" },
      },
      // nvgoggles moved from Utility's own Electronics group to sit
      // alongside its sibling nvgheadstrap above - same Legendary tier,
      // since standalone NVG goggles are at least as capable a
      // night-vision item as the head-strap version.
      { source: "Electronics", tier: "Legendary", only: ["nvgoggles"] },
    ],
  },
  {
    fileName: "Clothing_Head_Civilian",
    displayName: "Clothing Head - Civilian",
    icon: "Deliver",
    initStockPercent: 35,
    groups: [
      { source: "Helmets", tier: "Common", exclude: MIL_HELMETS },
      { source: "Caps", tier: "Common", exclude: MIL_CAPS },
      { source: "Hats_And_Hoods", tier: "Common", exclude: MIL_HATS },
      { source: "Masks", tier: "Common", exclude: MIL_MASKS },
      { source: "Eyewear", tier: "Common", exclude: MIL_EYEWEAR },
    ],
  },
  {
    fileName: "Clothing_Top_Military",
    displayName: "Clothing Top - Military",
    icon: "Deliver",
    initStockPercent: 15,
    groups: [
      { source: "Coats_And_Jackets", tier: "Rare", only: MIL_COATS },
      { source: "Shirts_And_TShirts", tier: "Uncommon", only: MIL_SHIRTS },
      { source: "Sweaters_And_Hoodies", tier: "Uncommon", only: MIL_SWEATERS },
      {
        source: "Vests",
        tier: "Rare",
        only: MIL_VESTS,
        overrides: {
          platecarriervest: "Legendary",
          platecarriervest_camo: "Legendary",
          platecarriervest_winter: "Legendary",
          chestplate: "Legendary",
        },
      },
    ],
  },
  {
    fileName: "Clothing_Top_Civilian",
    displayName: "Clothing Top - Civilian",
    icon: "Deliver",
    initStockPercent: 35,
    groups: [
      { source: "Coats_And_Jackets", tier: "Common", exclude: MIL_COATS },
      { source: "Shirts_And_TShirts", tier: "Common", exclude: MIL_SHIRTS },
      { source: "Sweaters_And_Hoodies", tier: "Common", exclude: MIL_SWEATERS },
      { source: "Vests", tier: "Common", exclude: MIL_VESTS },
      { source: "Blouses_And_Suits", tier: "Common" },
    ],
  },
  {
    fileName: "Clothing_Bottom_Military",
    displayName: "Clothing Bottom - Military",
    icon: "Deliver",
    initStockPercent: 15,
    groups: [
      { source: "Pants_And_Shorts", tier: "Rare", only: MIL_PANTS },
      { source: "Boots_And_Shoes", tier: "Uncommon", only: MIL_BOOTS },
    ],
  },
  {
    fileName: "Clothing_Bottom_Civilian",
    displayName: "Clothing Bottom - Civilian",
    icon: "Deliver",
    initStockPercent: 35,
    groups: [
      { source: "Pants_And_Shorts", tier: "Common", exclude: MIL_PANTS },
      { source: "Boots_And_Shoes", tier: "Common", exclude: MIL_BOOTS },
      { source: "Skirts_And_Dresses", tier: "Common" },
    ],
  },
  {
    fileName: "Clothing_Back_Military",
    displayName: "Clothing Back - Military",
    icon: "Deliver",
    initStockPercent: 15,
    groups: [
      {
        source: "Backpacks",
        tier: "Rare",
        only: MIL_BACKPACKS,
        overrides: { alicebag_green: "Legendary", attack2bag_black: "Legendary" },
      },
    ],
  },
  {
    fileName: "Clothing_Back_Civilian",
    displayName: "Clothing Back - Civilian",
    icon: "Deliver",
    initStockPercent: 30,
    groups: [{ source: "Backpacks", tier: "Uncommon", exclude: MIL_BACKPACKS }],
  },
  {
    fileName: "Clothing_Misc_Military",
    displayName: "Clothing Misc - Military",
    icon: "Deliver",
    initStockPercent: 20,
    groups: [
      { source: "Gloves", tier: "Uncommon", only: MIL_GLOVES },
      { source: "Armbands", tier: "Uncommon", only: MIL_ARMBANDS },
      { source: "Belts", tier: "Common", only: MIL_BELTS },
      { source: "Holsters_And_Pouches", tier: "Rare", only: MIL_HOLSTERS },
    ],
  },
  {
    fileName: "Clothing_Misc_Civilian",
    displayName: "Clothing Misc - Civilian",
    icon: "Deliver",
    initStockPercent: 35,
    groups: [
      { source: "Gloves", tier: "Common", exclude: MIL_GLOVES },
      { source: "Armbands", tier: "Common", exclude: MIL_ARMBANDS },
      { source: "Bandanas", tier: "Common" },
      { source: "Belts", tier: "Common", exclude: MIL_BELTS },
      { source: "Holsters_And_Pouches", tier: "Common", exclude: MIL_HOLSTERS },
    ],
  },
  {
    fileName: "Consumables",
    displayName: "Food & Drink",
    icon: "Deliver",
    initStockPercent: 35,
    groups: [
      { source: "Food", tier: "Common" },
      {
        source: "Drinks",
        tier: "Common",
        // filteringbottle (Canteen with built-in filter) and
        // expansionmilkbottle (Milk Bottle) were still at DayZ-Expansion-
        // Market's own low shipped defaults - repriced up.
        priceOverrides: {
          filteringbottle: { min: 1000, max: 1000 },
          expansionmilkbottle: { min: 500, max: 500 },
        },
      },
      { source: "Fruit_And_Vegetables", tier: "Common" },
      {
        source: "Meat",
        tier: "Common",
        // DayZ-Expansion-Market's own shipped default priced every raw
        // butchered steak/leg cut barely above a wild apple, despite
        // requiring an actual kill + successful butchering to obtain.
        // Re-priced and split into 4 difficulty tiers, each selling for a
        // flat 75% of buy price (`sellPricePercent` below - Food/Drinks/
        // Fruit_And_Vegetables above are unaffected, still the normal 20%
        // global rate): Tier 1 is small game/livestock that's easy to find
        // and safely kill (rabbit, chicken, goat, sheep); Tier 2 is bigger
        // livestock/common wild game needing a real weapon (pig, cow, deer,
        // fox); Tier 3 is genuinely dangerous or scarce wild game (boar,
        // mouflon, reindeer); Tier 4 is the two apex predators that can
        // kill you back (bear, wolf).
        sellPricePercent: 75,
        priceOverrides: {
          // Tier 1 - easy/common (buy 534-700, sell 400-525)
          rabbitlegmeat: { min: 534, max: 700 },
          chickenbreastmeat: { min: 534, max: 700 },
          goatsteakmeat: { min: 534, max: 700 },
          sheepsteakmeat: { min: 534, max: 700 },
          // Tier 2 - moderate (buy 700-900, sell 525-675)
          pigsteakmeat: { min: 700, max: 900 },
          cowsteakmeat: { min: 700, max: 900 },
          deersteakmeat: { min: 700, max: 900 },
          foxsteakmeat: { min: 700, max: 900 },
          // Tier 3 - hard/dangerous wild game (buy 900-1150, sell 675-863)
          boarsteakmeat: { min: 900, max: 1150 },
          mouflonsteakmeat: { min: 900, max: 1150 },
          reindeersteakmeat: { min: 900, max: 1150 },
          // Tier 4 - apex predators (buy 1150-1450, sell 863-1088)
          bearsteakmeat: { min: 1150, max: 1450 },
          wolfsteakmeat: { min: 1150, max: 1450 },
        },
      },
      {
        source: "Fish",
        tier: "Common",
        // Same "hunting/fishing as a subtle income source" pricing pass
        // as the Meat group above: flat 75% sell price, with progressively
        // higher prices for harder-to-catch species instead of one flat
        // band for everything. Tier 1 is the smallest/most common catches
        // needing the least effort (sardines, trap-caught shrimp); Tier 2
        // is common coastal/freshwater fish (mackerel, carp); Tier 3 is
        // larger/less common catches (steelhead trout, walleye pollock);
        // Tier 4 is caviar - a processed byproduct, priced above every
        // whole fish. Fillets (cleaned cuts, real butchering effort) are
        // priced above their species' whole-fish tier, same relationship
        // the Meat group's steaks have over a raw carcass.
        sellPricePercent: 75,
        priceOverrides: {
          // Tier 1 - easiest/most common (buy 534-700, sell 400-525)
          sardines: { min: 534, max: 700 },
          shrimp: { min: 534, max: 700 },
          // Tier 2 - common (buy 700-900, sell 525-675)
          mackerel: { min: 700, max: 900 },
          carp: { min: 700, max: 900 },
          // Tier 3 - larger/less common (buy 900-1150, sell 675-863)
          steelheadtrout: { min: 900, max: 1150 },
          walleyepollock: { min: 900, max: 1150 },
          // Tier 4 - processed byproduct, rarest (buy 1150-1450, sell 863-1088)
          redcaviar: { min: 1150, max: 1450 },
          // Fillets - cleaned cuts, priced above their species' whole-fish
          // tier (carp/mackerel are Tier 2, steelheadtrout is Tier 3)
          carpfilletmeat: { min: 1000, max: 1300 },
          mackerelfilletmeat: { min: 1000, max: 1300 },
          steelheadtroutfilletmeat: { min: 1250, max: 1600 },
        },
      },
    ],
  },
  {
    fileName: "Medical",
    displayName: "Medical",
    icon: "Deliver",
    initStockPercent: 25,
    groups: [
      {
        source: "Medical",
        tier: "Common",
        overrides: {
          charcoaltablets: "Uncommon",
          purificationtablets: "Uncommon",
          chelatingtablets: "Uncommon",
          disinfectantspray: "Uncommon",
          iodinetincture: "Uncommon",
          gasmask_filter: "Uncommon",
          tetracyclineantibiotics: "Uncommon",
          anticheminjector: "Uncommon",
          bloodtestkit: "Uncommon",
          salinebag: "Rare",
          bloodbagempty: "Rare",
          epinephrine: "Rare",
          morphine: "Rare",
          startkitiv: "Rare",
        },
      },
    ],
  },
  {
    fileName: "Base_Building",
    displayName: "Base Building",
    icon: "Deliver",
    initStockPercent: 25,
    groups: [
      { source: "Tents", tier: "Uncommon" },
      { source: "Locks", tier: "Uncommon" },
      { source: "Containers", tier: "Uncommon" },
      { source: "Flags", tier: "Uncommon" },
      { source: "Furnishings", tier: "Uncommon" },
      {
        source: "Supplies",
        tier: "Uncommon",
        only: SUPPLIES_BASE_BUILDING,
        // Plain bulk crafting materials (as opposed to the more
        // substantial defense/utility items left at Uncommon: barbedwire,
        // camonet, hescobox, powergenerator, tripod) - a hardcore survival
        // server still needs base building to be achievable without
        // trickling in one nail at a time from a 10-cap Uncommon stock.
        overrides: {
          rope: "Common",
          metalwire: "Common",
          epoxyputty: "Common",
          ducttape: "Common",
          woodenplank: "Common",
          metalplate: "Common",
          nailbox: "Common",
          nail: "Common",
        },
      },
    ],
  },
  {
    fileName: "Utility",
    displayName: "Utility",
    icon: "Deliver",
    initStockPercent: 30,
    groups: [
      { source: "Gardening", tier: "Uncommon" },
      { source: "Kits", tier: "Uncommon" },
      { source: "Navigation", tier: "Uncommon" },
      // nvgoggles moved to Clothing_Head_Military instead, alongside the
      // other military headgear/eyewear (see that category's own Eyewear
      // group, matching its sibling nvgheadstrap).
      { source: "Electronics", tier: "Uncommon", exclude: ["nvgoggles"] },
      // universallight/tlrlight are real weapon rail-mounted flashlight/
      // laser attachments, not handheld tools - moved to
      // Gun_Attachments_Military below (flashlight/headtorch/spotlight/
      // chemlights/lighters etc. all stay here, they're genuinely handheld).
      { source: "Lights", tier: "Uncommon", exclude: ["universallight", "tlrlight"] },
      { source: "Fishing", tier: "Uncommon" },
      { source: "Spraycans", tier: "Uncommon" },
      { source: "Liquids", tier: "Uncommon" },
      { source: "Supplies", tier: "Uncommon", exclude: SUPPLIES_BASE_BUILDING },
    ],
  },
  {
    fileName: "Tools_And_Melee",
    displayName: "Tools & Melee",
    icon: "Deliver",
    initStockPercent: 30,
    groups: [
      { source: "Tools", tier: "Uncommon" },
      { source: "Knifes", tier: "Uncommon" },
      { source: "Melee_Weapons", tier: "Common" },
    ],
  },
  {
    fileName: "Vehicles_Cars",
    displayName: "Vehicles - Cars",
    icon: "Car",
    initStockPercent: 10,
    groups: [
      {
        source: "Cars",
        tier: "Rare",
        // Every car/truck/SUV/pickup here (85 classnames total) sat within
        // one narrow buy band regardless of real capability, except the
        // two already correct: expansiontractor (lowest tier, untouched)
        // and expansionvodnik (top tier, untouched). Every other family
        // below gets its own priceOverride (pre-multiplier base - this
        // group is Rare tier, 2.5x - see BUY_PRICE_MULTIPLIER) so the whole
        // lineup climbs smoothly from the tractor up to the Vodnik. Every
        // reskin/color variant of a base vehicle gets the same price as its
        // base (same physical vehicle, cosmetic-only difference).
        priceOverrides: {
          ...Object.fromEntries(
            [
              "hatchback_02",
              "Hatchback_02_Black",
              "Hatchback_02_Blue",
              "Hatchback_02_Cab",
              "Hatchback_02_Pizzapresto",
              "Hatchback_02_cat",
              "Hatchback_02_fat",
              "Hatchback_02_icegem",
              "Hatchback_02_mtconstruction",
              "Hatchback_02_purplebomb",
              "Hatchback_02_purplesmoke",
              "Hatchback_02_rustbeige",
              "Hatchback_02_stripes1",
            ].map((c) => [c, { min: 12800, max: 22400 }] as const), // final 32000-56000
          ),
          ...Object.fromEntries(
            [
              "sedan_02",
              "Sedan_02_Grey",
              "Sedan_02_Medic01",
              "Sedan_02_Red",
              "Sedan_02_peacebird",
            ].map((c) => [c, { min: 15200, max: 25600 }] as const), // final 38000-64000
          ),
          ...Object.fromEntries(
            ["civiliansedan", "CivilianSedan_Black", "CivilianSedan_Wine"].map(
              (c) => [c, { min: 18400, max: 30400 }] as const, // final 46000-76000
            ),
          ),
          ...Object.fromEntries(
            [
              "offroadhatchback",
              "OffroadHatchback_5000ca",
              "OffroadHatchback_Blue",
              "OffroadHatchback_Cab",
              "OffroadHatchback_Firefighter",
              "OffroadHatchback_PoliceRus",
              "OffroadHatchback_White",
              "OffroadHatchback_chernarusarmy",
              "OffroadHatchback_wineblue",
            ].map((c) => [c, { min: 22000, max: 36000 }] as const), // final 55000-90000
          ),
          offroad_02: { min: 24000, max: 38000 }, // final 60000-95000
          ...Object.fromEntries(
            ["truck_01_covered", "Truck_01_Covered_Blue", "Truck_01_Covered_Orange"].map(
              (c) => [c, { min: 28000, max: 44000 }] as const, // final 70000-110000
            ),
          ),
          // NOTE: TP_Apoc_Suv/TP_ApocPickup_Truck/TP_Apoc_M1025 (the Apoc
          // SUV/pickup/Humvee families) deliberately have NO priceOverride
          // here - they don't exist in the raw "Cars" source file at all
          // (each is its own "category": "Vehicles_Cars" manifest group in
          // src/data/marketGapFill.json, cloned entirely by
          // marketGapFill.ts, never touched by this group's own
          // priceOverrides). Their prices are instead fixed directly in
          // marketGapFill.ts's VEHICLE_MANIFEST_CAR_PRICE_FIXES - see that
          // file.
          expansionuaz: { min: 46000, max: 62000 }, // final 115000-155000
          expansionbus: { min: 66000, max: 90000 }, // final 165000-225000
          expansion_landrover: { min: 70000, max: 94000 }, // final 175000-235000
        },
      },
    ],
  },
  {
    fileName: "Vehicles_Helicopters",
    displayName: "Vehicles - Helicopters",
    icon: "Car",
    initStockPercent: 10,
    groups: [{ source: "Helicopters", tier: "Legendary" }],
  },
  {
    // Deliberately NOT referenced by any CUSTOM_TRADER_IDENTITIES category
    // list yet - there's no navigable water anywhere near the trader city.
    // Built and tuned so it's ready to hand to a trader identity once
    // there's water access; also deliberately left out of
    // DZSurvivalTraderRestock_Module.c's s_ManagedCategories for the same
    // reason - no point auto-restocking stock nobody can buy yet.
    fileName: "Boats",
    displayName: "Vehicles - Boats",
    icon: "Car",
    initStockPercent: 10,
    groups: [
      {
        source: "Boats",
        tier: "Rare",
        // expansionlhd is a massive naval landing craft, priced orders of
        // magnitude above every other boat here - Legendary tier (cap 1)
        // fits it far better than Rare (cap 4).
        overrides: { expansionlhd: "Legendary" },
      },
    ],
  },
];

export const RARE_CATEGORIES = ["Ghillies"];
export const RARE_MAX_STOCK_CAP = 3;
const RARE_INIT_STOCK_PERCENT_TARGET = 0.0;

export const VEHICLE_PARTS_CATEGORIES = ["Vehicle_Parts", "Batteries"];
// Every classname in these two categories is now individually scarce (cap
// 1), matching every other Legendary-tier item's cap elsewhere in this
// economy.
export const VEHICLE_PARTS_MAX_STOCK_CAP = 1;
// Kept at 100% (full, i.e. exactly the new cap of 1) rather than dropping
// to 0% like RARE_CATEGORIES above: this category is still a functional
// necessity, not a "coveted power" one (see this file's header comment) -
// a vehicle purchase spawns its default attachments (wheels, doors,
// battery, ...) drawing from these same per-classname stock pools, and
// starting every part at 0 would make the very first vehicle purchase
// after this change fail outright for lack of parts. With a cap of only 1,
// "start full" already gives the intended scarcity - it just means the
// FIRST unit of each part is available immediately, and every purchase
// after that has to wait on DZSurvivalTraderRestock_Module.c's own daily
// vehicle-parts trickle or a player selling one in.
const VEHICLE_PARTS_INIT_STOCK_PERCENT_TARGET = 100.0;

interface MarketItem {
  ClassName?: string;
  MaxStockThreshold?: number;
  [key: string]: unknown;
}

interface MarketCategory {
  InitStockPercent?: number;
  Items?: MarketItem[];
  [key: string]: unknown;
}

// Extension a raw source category file is renamed to once fully absorbed
// into a MERGED_CATEGORIES entry (or dead per DEAD_MARKET_FILES) - see this
// file's header comment and quarantineConsumedSourceCategories() below.
// Deliberately does NOT end in ".json" - DayZ-Expansion-Market's folder
// scan filters strictly by that suffix.
const ORPHAN_SUFFIX = ".orphaned-source";

async function readCategory(name: string): Promise<MarketCategory | null> {
  const orphanPath = `${EXPANSION_MARKET_DIR}/${name}${ORPHAN_SUFFIX}`;
  const path = (await exists(orphanPath)) ? orphanPath : `${EXPANSION_MARKET_DIR}/${name}.json`;
  if (!(await exists(path))) return null;
  return JSON.parse(await Deno.readTextFile(path));
}

// Defense-in-depth hard ceiling on any computed price. The Enforce script
// engine's JSON loader parses MinPriceThreshold/MaxPriceThreshold as int32
// (max ~2.147 billion) - anything above that hard-crashes the whole server
// on next load with "Cannot convert to int", not just a bad price for one
// item (see buildMergedItems()'s own comment on the Boats self-merge
// compounding bug that first triggered this). Kept comfortably below the
// true int32 ceiling.
const MAX_SAFE_PRICE = 2_000_000_000;

function clampPrice(value: number): number {
  return Math.min(value, MAX_SAFE_PRICE);
}

async function buildMergedItems(def: MergedCategory): Promise<MarketItem[] | null> {
  const items: MarketItem[] = [];
  const seen = new Set<string>();

  for (const group of def.groups) {
    const source = await readCategory(group.source);
    if (!source) continue;

    // Self-merging categories (Boats, Medical - source name equals their
    // own fileName) read AND write the exact same live file, unlike every
    // other group here which reads an untouched, quarantined-away pristine
    // copy (see quarantineConsumedSourceCategories()). Applying the price
    // multiplier here would re-multiply an already-multiplied price on
    // every single server boot, compounding forever until it overflows the
    // Enforce script engine's int32 price fields and hard-crashes the
    // server. Self-merging groups therefore never re-price - tier
    // assignment still fully controls MaxStockThreshold, just never
    // touches price again after whatever's already on disk.
    const selfMerging = group.source === def.fileName;

    for (const item of source.Items ?? []) {
      const className = item.ClassName;
      if (!className) continue;
      if (group.only && !group.only.includes(className)) continue;
      if (group.exclude && group.exclude.includes(className)) continue;
      if (seen.has(className)) continue;
      seen.add(className);

      const tier = group.overrides?.[className] ?? group.tier;

      if (selfMerging) {
        const clamped: MarketItem = {
          ...item,
          MaxStockThreshold: TIER_MAX_STOCK[tier],
          // DayZ-Expansion-Market treats an item as "static stock" (never
          // decremented on purchase) whenever MinStockThreshold ==
          // MaxStockThreshold (ExpansionMarketItem.IsStaticStock()). Every
          // Legendary-tier item (cap 1) shipped with a default
          // MinStockThreshold of 1, which already equals that cap - so all
          // of them were silently always-in-stock regardless of the real
          // cap. Forcing MinStockThreshold to 0 here guarantees it's never
          // equal to a non-zero MaxStockThreshold, so real scarcity
          // actually applies.
          MinStockThreshold: 0,
          SellPricePercent: group.sellPricePercent ?? def.sellPricePercent ??
            SELL_PRICE_PERCENT_OVERRIDE[tier],
        };
        if (typeof clamped.MinPriceThreshold === "number") {
          clamped.MinPriceThreshold = clampPrice(clamped.MinPriceThreshold);
        }
        if (typeof clamped.MaxPriceThreshold === "number") {
          clamped.MaxPriceThreshold = clampPrice(clamped.MaxPriceThreshold);
        }
        items.push(clamped);
        continue;
      }

      const priceOverride = group.priceOverrides?.[className];
      const multiplier = BUY_PRICE_MULTIPLIER[tier];
      const baseMin = priceOverride ? priceOverride.min : Number(item.MinPriceThreshold);
      const baseMax = priceOverride ? priceOverride.max : Number(item.MaxPriceThreshold);
      items.push({
        ...item,
        MaxStockThreshold: TIER_MAX_STOCK[tier],
        // See the selfMerging branch above for the full "static stock"
        // bug writeup - same fix applies here for every non-self-merging
        // item.
        MinStockThreshold: 0,
        MinPriceThreshold: clampPrice(Math.round(baseMin * multiplier)),
        MaxPriceThreshold: clampPrice(Math.round(baseMax * multiplier)),
        SellPricePercent: group.sellPricePercent ?? def.sellPricePercent ??
          SELL_PRICE_PERCENT_OVERRIDE[tier],
      });
    }
  }

  return items.length > 0 ? items : null;
}

async function writeMergedCategory(def: MergedCategory): Promise<boolean> {
  const items = await buildMergedItems(def);
  if (!items) return false;

  const body: MarketCategory = {
    m_Version: 12,
    DisplayName: def.displayName,
    Icon: def.icon,
    Color: "FBFCFEFF",
    IsExchange: 0,
    InitStockPercent: def.initStockPercent,
    Items: items,
  };

  const path = `${EXPANSION_MARKET_DIR}/${def.fileName}.json`;
  await Deno.writeTextFile(path, JSON.stringify(body, null, 4));
  return true;
}

async function tuneCategory(
  name: string,
  maxStockCap: number,
  initStockPercentTarget: number,
  exact = false,
): Promise<boolean> {
  const path = `${EXPANSION_MARKET_DIR}/${name}.json`;
  if (!(await exists(path))) return false;

  const data: MarketCategory = JSON.parse(await Deno.readTextFile(path));
  let changed = false;

  if (
    typeof data.InitStockPercent === "number" &&
    (exact
      ? data.InitStockPercent !== initStockPercentTarget
      : data.InitStockPercent > initStockPercentTarget)
  ) {
    data.InitStockPercent = initStockPercentTarget;
    changed = true;
  }

  for (const item of data.Items ?? []) {
    if (
      typeof item.MaxStockThreshold === "number" &&
      (exact ? item.MaxStockThreshold !== maxStockCap : item.MaxStockThreshold > maxStockCap)
    ) {
      item.MaxStockThreshold = maxStockCap;
      changed = true;
    }
  }

  if (!changed) return false;
  await Deno.writeTextFile(path, JSON.stringify(data, null, 4));
  return true;
}

// The real, live merged categories (as opposed to the ~50 raw per-slot
// source files and the 3 confirmed-dead catch-all files they get merged
// from/alongside - see marketGapFill.ts's DEAD_MARKET_FILES) - exported so
// anything else that needs to know an item's *current, authoritative*
// MaxStockThreshold (e.g. traders.ts's clampTraderStockToMarketCaps()) only
// ever looks at these, never a stale/irrelevant raw source file's own
// snapshot value for the same classname.
export const MANAGED_MARKET_CATEGORIES: readonly string[] = MERGED_CATEGORIES.map((c) =>
  c.fileName
);

// Renames every raw source category file this merge has fully absorbed (see
// this file's header comment) away from ".json", so DayZ-Expansion-Market's
// folder scan (LoadCategories()) stops double-loading it alongside the real
// merged category it feeds - fixing the silent classname-duplicate-rejection
// data loss that caused. Self-merging entries (Medical, Boats - source name
// equals their own fileName) are deliberately excluded: they read/write the
// exact same file in place, so there's no separate orphaned copy to hide.
// Must run AFTER the merge loop, since readCategory() needs the plain
// ".json" source to still exist the first time a category is merged -
// subsequent runs then transparently read the quarantined copy instead (see
// readCategory()'s own ORPHAN_SUFFIX check).
async function quarantineConsumedSourceCategories(): Promise<number> {
  const consumedSources = new Set<string>();
  for (const def of MERGED_CATEGORIES) {
    for (const group of def.groups) {
      if (MANAGED_MARKET_CATEGORIES.includes(group.source)) continue;
      consumedSources.add(group.source);
    }
  }
  for (const deadFile of DEAD_MARKET_FILES) consumedSources.add(deadFile);

  let quarantined = 0;
  for (const name of consumedSources) {
    const rawPath = EXPANSION_MARKET_DIR + "/" + name + ".json";
    const orphanPath = EXPANSION_MARKET_DIR + "/" + name + ORPHAN_SUFFIX;

    if (await exists(orphanPath)) {
      if (await exists(rawPath)) await Deno.remove(rawPath);
      continue;
    }

    if (await exists(rawPath)) {
      await Deno.rename(rawPath, orphanPath);
      quarantined++;
    }
  }

  return quarantined;
}

export async function tuneExpansionMarket(): Promise<void> {
  if (!(await exists(EXPANSION_MARKET_DIR))) {
    log(
      `${EXPANSION_MARKET_DIR} not generated yet - DayZ-Expansion-Market will create it ` +
        "(with its own defaults) on first server start",
    );
    return;
  }

  let mergedCount = 0;
  for (const def of MERGED_CATEGORIES) {
    if (await writeMergedCategory(def)) mergedCount++;
  }

  let tunedCount = 0;
  for (const name of RARE_CATEGORIES) {
    if (await tuneCategory(name, RARE_MAX_STOCK_CAP, RARE_INIT_STOCK_PERCENT_TARGET, true)) {
      tunedCount++;
    }
  }
  for (const name of VEHICLE_PARTS_CATEGORIES) {
    if (
      await tuneCategory(
        name,
        VEHICLE_PARTS_MAX_STOCK_CAP,
        VEHICLE_PARTS_INIT_STOCK_PERCENT_TARGET,
        true,
      )
    ) {
      tunedCount++;
    }
  }

  const quarantinedCount = await quarantineConsumedSourceCategories();

  if (mergedCount === 0 && tunedCount === 0 && quarantinedCount === 0) return;
  const quarantineNote = quarantinedCount > 0
    ? ", quarantined " + quarantinedCount + " orphaned raw source categor" +
      (quarantinedCount === 1 ? "y" : "ies") + " so DayZ-Expansion-Market stops double-loading them"
    : "";
  ok(
    `Rebuilt ${mergedCount} merged DayZ-Expansion-Market categor${
      mergedCount === 1 ? "y" : "ies"
    } ` +
      `and tuned ${tunedCount} other categor${
        tunedCount === 1 ? "y" : "ies"
      } in ${EXPANSION_MARKET_DIR}` +
      quarantineNote,
  );
}
