// serverDZ.cfg generation and launching the server under steam-run.

import { MISSION_TEMPLATE, PROFILE_DIR, SERVER_DIR } from "./paths.ts";
import { log, ok, warn } from "./ui.ts";
import { requireTools } from "./proc.ts";
import { ensureServer, serverBinary } from "./steam.ts";
import { ensureMods } from "./install.ts";
import { backupWorldState, pruneOldLogs } from "./maintenance.ts";
import { ensureAIPatrols } from "./ai.ts";
import { ensureAIBanditsDensity } from "./aiBanditsDensity.ts";
import { ensureSpatialAI } from "./spatial.ts";
import { ensureDynamicMissions } from "./dynamicMissions.ts";
import { ensureModTypesMerged } from "./modTypes.ts";
import { ensureNamalskClothingMerged } from "./namalskClothing.ts";
import { ensureMoreCarsTypesMerged } from "./moreCars.ts";
import { ensureNCPRTypesMerged } from "./ncpr.ts";
import { ensureVehicle3PPWhitelist } from "./vehicle3pp.ts";
import { ensureCustomVehicleSpawns } from "./vehicleSpawns.ts";

import { ensureFuelSystemVehicles } from "./fuelSystem.ts";
import { LIGHTING_PRESET, tuneLightingConfig } from "./lighting.ts";
import { tuneMapAccess } from "./mapAccess.ts";
import { tuneWeather } from "./weather.ts";
import { tuneHazardZones } from "./hazards.ts";
import { ensureClimateZones } from "./climateZones.ts";
import { tuneNoBuildZones } from "./noBuildZones.ts";
import { ensureWildlifeTerritories } from "./wildlifeTerritories.ts";
import { ensureYuretskiyWired } from "./yuretskiy.ts";
import { ensureBmmChemicalZombieWired } from "./bmmChemicalZombie.ts";
import { ensureCustomZombiesTchcWired } from "./customZombiesTchc.ts";
import { ensureNecromutantWired } from "./necromutant.ts";
import { ensureForeverBurningCampfireWired } from "./foreverBurningCampfire.ts";
import { ensureOpticsWired } from "./optics.ts";
import { ensureTgkWeaponPackWired } from "./tgkWeaponPack.ts";
import { ensureMilitaryMonsterGarrisons } from "./militaryMonsters.ts";
import { tuneExpansionMarket } from "./market.ts";
import { ensureMarketGapFill } from "./marketGapFill.ts";
import { ensureCustomTrader } from "./traders.ts";
import { tuneNewAIEventMods } from "./aiWorldEvents.ts";
import {
  tuneAirdropLoot,
  tuneMissionRewards,
  tuneRespawnPoints,
  tuneStartingKit,
  tuneStartingLoadouts,
  tuneStartScreenSettings,
} from "./loot.ts";
import {
  tuneAIBanditsDifficulty,
  tuneAIDifficulty,
  tuneInediaInfectedAIDifficulty,
  tuneMissionDifficulty,
  tuneSpatialAIDifficulty,
} from "./difficulty.ts";
import { tuneAnimalSpawns, tuneFoodScarcity, tuneMoneyScarcity } from "./economy.ts";
import { loadMods, modParam, serverModParam } from "./mods.ts";
import { ensureConfig, type Settings } from "./config.ts";
import { primeModConfigsIfNeeded } from "./prime.ts";
import { ensureLocalServerPack } from "./localServerPacks.ts";
import { SERVERPACK_SERVERONLY } from "./paths.ts";
import { listAddons } from "./modBuild.ts";

export async function genConfig(s: Settings): Promise<void> {
  const cfg = `${SERVER_DIR}/serverDZ.cfg`;
  await Deno.mkdir(SERVER_DIR, { recursive: true });
  const body = `// Generated by the CLI — edit values via 'deno task config' or here directly.
hostname       = "${s.SERVER_NAME}";
password       = "${s.JOIN_PASSWORD}";
passwordAdmin  = "${s.ADMIN_PASSWORD}";
maxPlayers     = ${s.MAXPLAYERS};

verifySignatures = 2;
forceSameBuild   = 1;

disableVoN        = 0;
vonCodecQuality   = 20;
disable3rdPerson  = 0;
disableCrosshair  = 0;

serverTime                  = "SystemTime";
serverTimeAcceleration      = 8;
serverNightTimeAcceleration = 2;
serverTimePersistent        = 0;
lightingConfig              = ${LIGHTING_PRESET};

guaranteedUpdates = 1;
loginQueueConcurrentPlayers = 5;
loginQueueMaxPlayers        = 500;

instanceId     = 1;
storageAutoFix = 1;
respawnTime    = 5;

steamQueryPort = ${s.QUERY_PORT};

class Missions
{
    class DayZ
    {
        template = "${MISSION_TEMPLATE}";
    };
};

motd[] = { "Welcome to ${s.SERVER_NAME}" };
motdInterval = 30;

timeStampFormat = "Short";
logAverageFps   = 30;
logMemory       = 30;
logPlayers      = 30;
logFile         = "server_console.log";
adminLogPlayerHitsOnly = 0;
adminLogPlacement      = 1;
adminLogBuildActions   = 1;
adminLogPlayerList     = 1;
`;
  await Deno.writeTextFile(cfg, body);
  ok(`Wrote ${cfg}`);
}

// Crash-recovery watchdog for the actual server launch (the very last step
// of doStart()). Previously the server ran once via runInherit() and, on
// ANY exit - a clean admin shutdown or a genuine crash - the whole CLI
// process exited with it, so an unattended crash (e.g. overnight) just left
// the server down until someone noticed and reran the CLI by hand. This
// wraps the launch in a loop that auto-restarts on an unexpected exit, with
// a short backoff, while still stopping cleanly (no restart) on an
// intentional Ctrl-C/SIGTERM.
const CRASH_LOG = `${PROFILE_DIR}/crashes.log`;
// Below this much runtime, an exit counts as a "fast crash" for the
// give-up logic below rather than a normal shutdown after a real play
// session.
const FAST_CRASH_THRESHOLD_MS = 60_000;
const RESTART_BACKOFF_MS = 15_000;
const MAX_CONSECUTIVE_FAST_CRASHES = 5;

let stopRequested = false;
let currentChild: Deno.ChildProcess | null = null;

function requestStop(): void {
  if (stopRequested) {
    warn("Second stop signal received - killing the server immediately.");
    try {
      currentChild?.kill("SIGKILL");
    } catch {
      // already exited - nothing to kill
    }
    Deno.exit(1);
  }
  stopRequested = true;
  log(
    "Stop requested - waiting for the server to shut down gracefully " +
      "(Ctrl-C again to force-kill)...",
  );
  try {
    currentChild?.kill("SIGTERM");
  } catch {
    // already exited - the watchdog loop will notice via child.status
  }
}

async function logCrash(code: number, ranMs: number): Promise<void> {
  const line = `${new Date().toISOString()}  exit=${code}  ranMs=${ranMs}\n`;
  await Deno.writeTextFile(CRASH_LOG, line, { append: true }).catch(() => {});
}

async function runServerWithWatchdog(args: string[]): Promise<never> {
  Deno.addSignalListener("SIGINT", requestStop);
  Deno.addSignalListener("SIGTERM", requestStop);

  let consecutiveFastCrashes = 0;
  while (true) {
    const startedAt = Date.now();
    // setsid detaches the server into its own session/process group, so a
    // terminal Ctrl+C only ever signals *this* CLI process (via the
    // Deno.addSignalListener above), not the server directly and
    // uncontrolled in parallel - requestStop() is then the only thing that
    // ever signals it (SIGTERM, escalating to SIGKILL on a second Ctrl+C),
    // matching the same fix applied to prime.ts's headless priming run for
    // the identical underlying issue. stdin/stdout/stderr stay inherited -
    // detaching the session doesn't affect already-open file descriptors,
    // so the console (including admin commands typed into stdin) keeps
    // working exactly as before.
    currentChild = new Deno.Command("setsid", {
      args: ["steam-run", ...args],
      cwd: SERVER_DIR,
      env: {
        LD_LIBRARY_PATH: `${SERVER_DIR}:${Deno.env.get("LD_LIBRARY_PATH") ?? ""}`,
      },
      stdin: "inherit",
      stdout: "inherit",
      stderr: "inherit",
    }).spawn();
    const { code } = await currentChild.status;
    const ranMs = Date.now() - startedAt;
    currentChild = null;

    if (stopRequested) Deno.exit(code);

    if (code === 0) {
      warn("Server exited cleanly (code 0) without a stop request - restarting anyway.");
    } else {
      warn(`Server crashed (exit code ${code}) after running for ${Math.round(ranMs / 1000)}s.`);
    }
    await logCrash(code, ranMs);

    if (ranMs < FAST_CRASH_THRESHOLD_MS) {
      consecutiveFastCrashes++;
      if (consecutiveFastCrashes >= MAX_CONSECUTIVE_FAST_CRASHES) {
        warn(
          `${consecutiveFastCrashes} crashes in a row within ` +
            `${FAST_CRASH_THRESHOLD_MS / 1000}s of starting each time - giving up rather than ` +
            `crash-looping. Check ${CRASH_LOG} and the latest profiles/DayZServer_*.RPT for the ` +
            `real error before restarting manually.`,
        );
        Deno.exit(code || 1);
      }
    } else {
      consecutiveFastCrashes = 0;
    }

    log(`Restarting in ${RESTART_BACKOFF_MS / 1000}s...`);
    await new Promise<void>((resolve) => setTimeout(resolve, RESTART_BACKOFF_MS));
  }
}

export async function doStart(s: Settings): Promise<void> {
  await requireTools();
  await ensureConfig(s);
  await ensureServer(s);
  await ensureMods(s);
  // DZSurvivalServerOnly (server-side-only custom logic with NO client-
  // visible behavior AND no COT/permission-system integration - see
  // paths.ts's own comment on SERVERPACK_SERVERONLY for why that specific
  // combination matters) is deliberately never published to Steam Workshop -
  // it's built and signed locally, then staged straight into the server's
  // own mod folder every start, so it's never listed in mods.txt and never
  // downloaded by anyone, including this server itself. See
  // localServerPacks.ts. Currently empty (DZSurvivalBaseDecay, its only
  // former occupant, had to move into the shared serverpack/ - see that
  // addon's own DZSurvivalBaseDecay_COTCommand.c for why) - skipped
  // entirely whenever it has no addons, rather than staging/loading an
  // empty mod, so this stays a no-op until something genuinely server-only
  // (and COT-free) needs it again.
  const hasServerOnlyAddons = (await listAddons(SERVERPACK_SERVERONLY)).length > 0;
  if (hasServerOnlyAddons) {
    await ensureLocalServerPack(SERVERPACK_SERVERONLY);
  }
  const allMods = await loadMods();
  await genConfig(s);

  const mods = modParam(allMods);
  let serverMods = serverModParam(allMods);
  if (hasServerOnlyAddons) {
    serverMods = serverMods
      ? `${serverMods};@${SERVERPACK_SERVERONLY.name}`
      : `@${SERVERPACK_SERVERONLY.name}`;
  }
  await Deno.mkdir(PROFILE_DIR, { recursive: true });
  const extra = s.EXTRA_PARAMS.trim() ? s.EXTRA_PARAMS.trim().split(/\s+/) : [];
  const args = [
    await serverBinary(),
    "-config=serverDZ.cfg",
    `-port=${s.PORT}`,
    `-mod=${mods}`,
    ...(serverMods ? [`-servermod=${serverMods}`] : []),
    `-BEpath=${PROFILE_DIR}/battleye`,
    `-profiles=${PROFILE_DIR}`,
    `-cpuCount=${navigator.hardwareConcurrency}`,
    ...extra,
  ];

  // On a brand-new install, none of the mod-generated files the ensure/tune
  // pipeline below edits exist yet - this runs the server headless once so
  // they do, before we tune anything. No-op on every later start.
  await primeModConfigsIfNeeded(args);

  await ensureModTypesMerged(allMods);
  await ensureNamalskClothingMerged(allMods);
  await ensureMoreCarsTypesMerged(allMods);
  await ensureCustomVehicleSpawns(allMods);
  await ensureNCPRTypesMerged(allMods);
  await ensureVehicle3PPWhitelist(allMods);
  await ensureWildlifeTerritories(allMods);
  await ensureYuretskiyWired(allMods);
  await ensureBmmChemicalZombieWired(allMods);
  await ensureCustomZombiesTchcWired(allMods);
  await ensureNecromutantWired(allMods);
  await ensureOpticsWired(allMods);
  await ensureTgkWeaponPackWired(allMods);
  await ensureMilitaryMonsterGarrisons(allMods);
  await ensureAIPatrols();
  await ensureAIBanditsDensity();
  await ensureSpatialAI();
  await ensureDynamicMissions();
  await tuneAirdropLoot();
  await tuneMissionRewards();
  await tuneStartingLoadouts();
  await tuneStartingKit();
  await tuneRespawnPoints();
  await tuneStartScreenSettings();
  await tuneAIDifficulty();
  await tuneSpatialAIDifficulty();
  await tuneMissionDifficulty();
  await tuneInediaInfectedAIDifficulty();
  await tuneAIBanditsDifficulty();
  await tuneFoodScarcity();
  await tuneAnimalSpawns();
  await tuneMoneyScarcity();
  await tuneExpansionMarket();
  await ensureMarketGapFill();
  await ensureCustomTrader();
  await ensureForeverBurningCampfireWired(allMods);
  await tuneLightingConfig();
  await tuneMapAccess();
  await tuneWeather();
  await tuneHazardZones();
  await tuneNoBuildZones();
  await ensureClimateZones();
  await ensureFuelSystemVehicles(allMods);
  await tuneNewAIEventMods();

  await pruneOldLogs();
  await backupWorldState();

  log(`Starting DayZ server on UDP ${s.PORT}`);
  log(`Mods: ${mods}`);
  if (serverMods) log(`Server-only mods: ${serverMods}`);

  // steam-run provides the prebuilt DayZServer an FHS environment on NixOS.
  await runServerWithWatchdog(args);
}
