// serverDZ.cfg generation and launching the server under steam-run.

import { MISSION_TEMPLATE, PROFILE_DIR, SERVER_DIR } from "./paths.ts";
import { log, ok } from "./ui.ts";
import { requireTools, runInherit } from "./proc.ts";
import { ensureServer, serverBinary } from "./steam.ts";
import { ensureMods } from "./install.ts";
import { ensureAIPatrols } from "./ai.ts";
import { ensureSpatialAI } from "./spatial.ts";
import { ensureDynamicMissions } from "./dynamicMissions.ts";
import { ensureModTypesMerged } from "./modTypes.ts";
import { ensureMoreCarsTypesMerged } from "./moreCars.ts";
import { ensureNCPRTypesMerged } from "./ncpr.ts";
import { ensureVehicle3PPWhitelist } from "./vehicle3pp.ts";
import { tuneDynamicScavenging } from "./scavenging.ts";
import { ensureFuelSystemVehicles } from "./fuelSystem.ts";
import { LIGHTING_PRESET, tuneLightingConfig } from "./lighting.ts";
import { ensureWildlifeTerritories } from "./wildlifeTerritories.ts";
import { ensureYuretskiyWired } from "./yuretskiy.ts";
import { tuneExpansionMarket } from "./market.ts";
import {
  tuneAirdropLoot,
  tuneMissionRewards,
  tuneRespawnPoints,
  tuneStartingKit,
  tuneStartingLoadouts,
  tuneStartScreenSettings,
} from "./loot.ts";
import {
  tuneAIBanditsDifficulty,
  tuneAIDifficulty,
  tuneInediaInfectedAIDifficulty,
  tuneMissionDifficulty,
  tuneSpatialAIDifficulty,
} from "./difficulty.ts";
import { tuneAnimalSpawns, tuneFoodScarcity, tuneMoneyScarcity } from "./economy.ts";
import { loadMods, modParam, serverModParam } from "./mods.ts";
import { ensureConfig, type Settings } from "./config.ts";
import { primeModConfigsIfNeeded } from "./prime.ts";

export async function genConfig(s: Settings): Promise<void> {
  const cfg = `${SERVER_DIR}/serverDZ.cfg`;
  await Deno.mkdir(SERVER_DIR, { recursive: true });
  const body = `// Generated by the CLI — edit values via 'deno task config' or here directly.
hostname       = "${s.SERVER_NAME}";
password       = "${s.JOIN_PASSWORD}";
passwordAdmin  = "${s.ADMIN_PASSWORD}";
maxPlayers     = ${s.MAXPLAYERS};

verifySignatures = 2;
forceSameBuild   = 1;

disableVoN        = 0;
vonCodecQuality   = 20;
disable3rdPerson  = 0;
disableCrosshair  = 0;

serverTime                  = "SystemTime";
serverTimeAcceleration      = 8;
serverNightTimeAcceleration = 2;
serverTimePersistent        = 0;
lightingConfig              = ${LIGHTING_PRESET};

guaranteedUpdates = 1;
loginQueueConcurrentPlayers = 5;
loginQueueMaxPlayers        = 500;

instanceId     = 1;
storageAutoFix = 1;
respawnTime    = 5;

steamQueryPort = ${s.QUERY_PORT};

class Missions
{
    class DayZ
    {
        template = "${MISSION_TEMPLATE}";
    };
};

motd[] = { "Welcome to ${s.SERVER_NAME}" };
motdInterval = 30;

timeStampFormat = "Short";
logAverageFps   = 30;
logMemory       = 30;
logPlayers      = 30;
logFile         = "server_console.log";
adminLogPlayerHitsOnly = 0;
adminLogPlacement      = 1;
adminLogBuildActions   = 1;
adminLogPlayerList     = 1;
`;
  await Deno.writeTextFile(cfg, body);
  ok(`Wrote ${cfg}`);
}

export async function doStart(s: Settings): Promise<never> {
  await requireTools();
  await ensureConfig(s);
  await ensureServer(s);
  await ensureMods(s);
  const allMods = await loadMods();
  await genConfig(s);

  const mods = modParam(allMods);
  const serverMods = serverModParam(allMods);
  await Deno.mkdir(PROFILE_DIR, { recursive: true });
  const extra = s.EXTRA_PARAMS.trim() ? s.EXTRA_PARAMS.trim().split(/\s+/) : [];
  const args = [
    await serverBinary(),
    "-config=serverDZ.cfg",
    `-port=${s.PORT}`,
    `-mod=${mods}`,
    ...(serverMods ? [`-servermod=${serverMods}`] : []),
    `-BEpath=${PROFILE_DIR}/battleye`,
    `-profiles=${PROFILE_DIR}`,
    `-cpuCount=${navigator.hardwareConcurrency}`,
    ...extra,
  ];

  // On a brand-new install, none of the mod-generated files the ensure/tune
  // pipeline below edits exist yet - this runs the server headless once so
  // they do, before we tune anything. No-op on every later start.
  await primeModConfigsIfNeeded(args);

  await ensureModTypesMerged(allMods);
  await ensureMoreCarsTypesMerged(allMods);
  await ensureNCPRTypesMerged(allMods);
  await ensureVehicle3PPWhitelist(allMods);
  await ensureWildlifeTerritories(allMods);
  await ensureYuretskiyWired(allMods);
  await ensureAIPatrols();
  await ensureSpatialAI();
  await ensureDynamicMissions();
  await tuneAirdropLoot();
  await tuneMissionRewards();
  await tuneStartingLoadouts();
  await tuneStartingKit();
  await tuneRespawnPoints();
  await tuneStartScreenSettings();
  await tuneAIDifficulty();
  await tuneSpatialAIDifficulty();
  await tuneMissionDifficulty();
  await tuneInediaInfectedAIDifficulty();
  await tuneAIBanditsDifficulty();
  await tuneFoodScarcity();
  await tuneAnimalSpawns();
  await tuneMoneyScarcity();
  await tuneDynamicScavenging();
  await tuneExpansionMarket();
  await tuneLightingConfig();
  await ensureFuelSystemVehicles(allMods);

  log(`Starting DayZ server on UDP ${s.PORT}`);
  log(`Mods: ${mods}`);
  if (serverMods) log(`Server-only mods: ${serverMods}`);

  // steam-run provides the prebuilt DayZServer an FHS environment on NixOS.
  const code = await runInherit("steam-run", args, {
    cwd: SERVER_DIR,
    env: {
      LD_LIBRARY_PATH: `${SERVER_DIR}:${Deno.env.get("LD_LIBRARY_PATH") ?? ""}`,
    },
  });
  Deno.exit(code);
}
