// Custom trader city: replaces DayZ-Expansion-Market's 6 stock Chernarus
// trader zones (self-generated by the mod into MISSION_DIR/expansion/
// traderzones/ on first world load) with a single custom-designed one.
//
// Roster: one general "Everything" trader plus one "Vehicle" trader.
// DayZ-Expansion-Market's 17 default trader identities (under
// profiles/ExpansionMod/Traders/) ship untouched for later use (see
// ensureCustomTraderIdentities()); only these two custom identities are
// referenced by the actual NPCs below.
//
// This only defines the zone's shape (radius/pricing) and NPC roster. The
// world position must be scouted manually in-game as admin (COT's free cam/
// `INSERT` + position readout) and filled into CUSTOM_POSITION below. Until
// set, this only removes the 6 defaults and leaves the custom zone/NPCs
// disabled (with a warning) rather than writing NPCs to a guessed,
// possibly-underground position.
//
// NPCs are placed via Expansion's plain-text `.map` format (one line each:
// `<TraderEntityClassName>.<TraderFileName>|<Position>|<Orientation>|<Gear>`)
// under MISSION_DIR/expansion/traders/ (see DayZ-Expansion-Core's
// ExpansionWorldObjectsModule.c GetTraderFromMissionFile()/ProcessGear()).
// Individual NPC positions here are *offsets* from CUSTOM_POSITION, so only
// one real-world coordinate ever needs scouting.
//
// The Gear field is a comma-separated token list; the only token used here
// is `loadout:<Name>`, which applies a named gear preset from
// profiles/ExpansionMod/Loadouts/<Name>.json (written by
// ensureCustomTraderGear() below) via ExpansionHumanLoadout.Apply(). That
// preset schema (ExpansionPrefabObject/InventoryAttachments) is NOT the
// same as DayZ-Editor's exported character-preset JSON
// (attachmentSlotItemSets/discreteItemSets) - see TRADER_BLUE_GEAR, which
// was manually converted from the latter to the former.

import {
  EXPANSION_LOADOUTS_DIR,
  EXPANSION_MARKET_DIR,
  EXPANSION_TRADERS_DIR,
  MARKET_SETTINGS,
  MISSION_DIR,
  SAFE_ZONE_SETTINGS,
} from "./paths.ts";
import { log, ok, warn } from "./ui.ts";
import { exists } from "./steam.ts";
import { MANAGED_MARKET_CATEGORIES } from "./market.ts";
import { OLD_FOOD_CLASSNAMES, WOOD_SELL_ONLY_CLASSNAMES } from "./marketGapFill.ts";

const TRADERZONES_DIR = `${MISSION_DIR}/expansion/traderzones`;
const TRADERS_DIR = `${MISSION_DIR}/expansion/traders`;

const DEFAULT_ZONE_FILES = [
  "Svetloyarsk.json",
  "BalotaAircrafts.json",
  "KamenkaBoats.json",
  "GreenMountain.json",
  "Kamenka.json",
  "Krasnostav.json",
];

const CUSTOM_ZONE_NAME = "CustomTrader";

// TODO: fill in with a real, scouted position ([x, y, z] - y is elevation,
// not optional) before this zone/its NPCs will be generated. e.g.:
//   const CUSTOM_POSITION: [number, number, number] | null = [7500, 20, 9600];
export const CUSTOM_POSITION: [number, number, number] | null = [7991.59, 221.09, 11312.5];
const CUSTOM_RADIUS = 150;

// A DayZ-Expansion-Core SafeZone (no PvP/vehicle damage) centered on
// CUSTOM_POSITION. Deliberately a separate, larger radius than
// CUSTOM_RADIUS above (which only governs Market buy/sell pricing/stock).
// Also used by serverpack/addons/DZSurvivalTraderRestock's
// ActionCheckTraderBoard.c for its trader-proximity check, and by
// aiWorldEvents.ts to keep AI-mod safe zones from spawning threats on top
// of the trader city - keep in sync if this is ever changed.
export const CUSTOM_SAFE_ZONE_RADIUS = 175;

// Real, physical gold currency used as the trader city's (and ATM's) only
// currency - DayZ-Expansion-Core's own ExpansionGoldNugget. Like the stock
// expansionbanknotehryvnia it replaces, this item has no types.xml entry -
// it's created purely from mod config on demand for trader/ATM purchases.
//
// IMPORTANT - do NOT use ExpansionGoldNugget_InsanityStack here: its
// LoadMoneyPrice() keys the classname->price map using the unstripped
// classname, but GetMoneyPrice() unconditionally strips any
// "_insanitystack" suffix before every lookup - so this variant can never
// find its own price and SpawnMoneyInCurrency() silently spawns zero
// currency on sale/purchase. Plain ExpansionGoldNugget's native 50,000
// stack cap is still more than enough for this project's economy.
const GOLD_CURRENCY_CLASSNAME = "ExpansionGoldNugget";

interface TraderIdentity {
  fileName: string;
  displayName: string;
  icon: string;
  categories: string[];
  /**
   * Per-item buy/sell override (ExpansionMarketTrader's own `Items` map,
   * confirmed via unpacking market_scripts.pbo's
   * ExpansionMarketTraderBuySell enum: CanOnlyBuy=0, CanBuyAndSell=1,
   * CanOnlySell=2, CanBuyAndSellAsAttachmentOnly=3). Independent of both
   * stock AND of the item's own MinPriceThreshold/MaxPriceThreshold -
   * CanBuyItem()/CanSellItem() each check only this value, so a
   * CanOnlySell item still sells for its normal (SellPricePercent-scaled)
   * price, it just can never be bought at any price.
   */
  items?: Record<string, number>;
}

// ExpansionMarketTraderBuySell.CanOnlySell - see TraderIdentity.items above.
const CAN_ONLY_SELL = 2;

// Old_ (moldy/expired) canned goods are find-only in the world, not
// buyable, but still sellable back to the trader for a modest price (see
// marketGapFill.ts's OLD_FOOD_CLASSNAMES/FOOD_OLD_CAN_PRICE).
const OLD_FOOD_BUYSELL_OVERRIDES = Object.fromEntries(
  OLD_FOOD_CLASSNAMES.map((c) => [c, CAN_ONLY_SELL]),
);

// WoodenLog/Firewood: same find-only-but-sellable pattern as old food above
// (see marketGapFill.ts's WOOD_SELL_ONLY_CLASSNAMES/WOOD_SELL_ONLY_PRICE_FIXES).
const WOOD_BUYSELL_OVERRIDES = Object.fromEntries(
  WOOD_SELL_ONLY_CLASSNAMES.map((c) => [c, CAN_ONLY_SELL]),
);

// Same schema/currency as DayZ-Expansion-Market's own default trader
// identity files. Categories reference Market category names under
// profiles/ExpansionMod/Market/, which stay individually stock-capped by
// src/market.ts (tuneExpansionMarket()) regardless of which trader sells
// them, so lumping everything into one NPC here doesn't bypass tuning.
// Every category name across both identities is exported so
// marketAudit.ts can compute exactly which categories a player can
// actually buy/sell from without hand-reconstructing this list from
// market.ts's separate category exports.
export const CUSTOM_TRADER_IDENTITIES: TraderIdentity[] = [
  {
    fileName: "Everything",
    displayName: "General Store",
    icon: "Trader",
    // See src/market.ts's MERGED_CATEGORIES for what each of these
    // contains and how items are tiered. Vehicles/Vehicle_Parts/Batteries
    // are reserved for the Vehicle Dealer below.
    categories: [
      "Guns_Military",
      "Guns_Civilian",
      "Gun_Ammo",
      "Gun_Attachments_Military",
      "Gun_Attachments_Civilian",
      "Explosives",
      "Clothing_Head_Military",
      "Clothing_Head_Civilian",
      "Clothing_Top_Military",
      "Clothing_Top_Civilian",
      "Clothing_Bottom_Military",
      "Clothing_Bottom_Civilian",
      "Clothing_Back_Military",
      "Clothing_Back_Civilian",
      "Clothing_Misc_Military",
      "Clothing_Misc_Civilian",
      "Ghillies",
      "Consumables",
      "Medical",
      "Base_Building",
      "Utility",
      "Tools_And_Melee",
    ],
    items: {
      ...OLD_FOOD_BUYSELL_OVERRIDES,
      ...WOOD_BUYSELL_OVERRIDES,
    },
  },
  {
    fileName: "Vehicle",
    displayName: "Vehicle Dealer",
    icon: "Car",
    // No Boats - no navigable water anywhere near this trader city.
    categories: ["Vehicles_Cars", "Vehicles_Helicopters", "Vehicle_Parts", "Batteries"],
  },
];

interface CustomTraderNpc {
  entity: string;
  traderFile: string;
  /** Offset in meters from CUSTOM_POSITION, so only one coordinate needs scouting. */
  offset: [number, number, number];
  orientation: [number, number, number];
  gear?: string;
}

interface GearSlot {
  slot: string;
  className: string;
}

// Converted from a DayZ-Editor-exported outfit preset (schema:
// attachmentSlotItemSets/discreteItemSets) into DayZ-Expansion-Core's own,
// unrelated "loadout" schema (ExpansionPrefabObject/InventoryAttachments -
// see ensureCustomTraderGear() below). Only the single itemType from each
// slot was kept; the editor's spawnWeight/health/quantity fields don't
// carry over to this format and aren't needed for a fixed NPC outfit.
const TRADER_BLUE_GEAR: GearSlot[] = [
  { slot: "Headgear", className: "BaseballCap_Blue" },
  { slot: "Gloves", className: "LeatherGloves_Natural" },
  { slot: "Armband", className: "Armband_Blue" },
  { slot: "Back", className: "BaseRadio" },
  { slot: "Body", className: "Hoodie_Blue" },
  { slot: "Feet", className: "AthleticShoes_Blue" },
  { slot: "Hips", className: "HipPack_Black" },
  { slot: "Legs", className: "CanvasPants_Blue" },
  { slot: "Vest", className: "PressVest_Blue" },
  { slot: "Melee", className: "Izh18Shotgun" },
];

// Vehicle Dealer's own outfit: same idea (blue armband, per request), but
// distinct dark colorway plus a different weapon so the two NPCs don't look
// identical at a glance. No "Back" slot here (unlike the general trader's
// BaseRadio) since that read as a duplicate backpack on both NPCs. Every
// classname below double-checked against db/types.xml - "CanvasPants_Black"
// and "PressVest_Black"/"FireAxe" (first draft) don't actually exist as
// items, which is why the pants silently failed to spawn in-game.
const TRADER_VEHICLE_GEAR: GearSlot[] = [
  { slot: "Headgear", className: "BaseballCap_Black" },
  { slot: "Gloves", className: "LeatherGloves_Black" },
  { slot: "Armband", className: "Armband_Blue" },
  { slot: "Body", className: "Hoodie_Black" },
  { slot: "Feet", className: "AthleticShoes_Black" },
  { slot: "Hips", className: "HipPack_Black" },
  { slot: "Legs", className: "CanvasPants_Grey" },
  { slot: "Vest", className: "LeatherStorageVest_Black" },
  { slot: "Melee", className: "FirefighterAxe_Black" },
];

const CUSTOM_LOADOUTS: { name: string; gear: GearSlot[] }[] = [
  { name: "TraderBlueLoadout", gear: TRADER_BLUE_GEAR },
  { name: "TraderVehicleLoadout", gear: TRADER_VEHICLE_GEAR },
];

// Small starting roster - one general trader, one vehicle trader. More
// specific/themed NPCs (referencing the untouched default trader files
// under profiles/ExpansionMod/Traders/) can be added here later.
const CUSTOM_NPCS: CustomTraderNpc[] = [
  {
    entity: "ExpansionTraderDenis",
    traderFile: "Everything",
    offset: [0, 0, 0],
    orientation: [176, 0, 0],
    gear: "loadout:TraderBlueLoadout",
  },
  {
    entity: "ExpansionTraderCyril",
    traderFile: "Vehicle",
    offset: [34.46, -5.34, -6.1],
    orientation: [-171.359, 0, 0],
    gear: "loadout:TraderVehicleLoadout",
  },
];

interface VehicleSpawnPoint {
  /** Offset in meters from CUSTOM_POSITION, same convention as CUSTOM_NPCS. */
  offset: [number, number, number];
  orientation: [number, number, number];
}

// DayZ-Expansion-Market vehicle purchases can only spawn at a position
// listed in MarketSettings.json's LandSpawnPositions/AirSpawnPositions
// (ExpansionTraderBase.HasVehicleSpawnPosition() searches those lists for
// a clear spot within MaxVehicleDistanceToTrader of the buying trader's
// NPC, failing with "no [air/land] spawn space" otherwise). The shipped
// default entries are clustered near the vanilla trader city, nowhere near
// this custom one, hence the scouted positions below.
//
// 3 scouted flat/clear car spots near the Vehicle Dealer NPC (absolute
// positions converted to CUSTOM_POSITION-relative offsets; orientation is
// [yaw, pitch, roll], matching CUSTOM_NPCS/MarketSettings.json's own
// convention).
const CUSTOM_LAND_VEHICLE_SPAWN_POINTS: VehicleSpawnPoint[] = [
  { offset: [45.933, -8.234, -23.132], orientation: [90.03, -11.09, 6.56] },
  { offset: [45.518, -8.663, -29.127], orientation: [90.03, -11.09, 6.56] },
  { offset: [44.929, -8.807, -34.954], orientation: [90.09, -10.57, -0.17] },
];
// 3 scouted helipads near the Vehicle Dealer NPC (absolute positions
// converted to CUSTOM_POSITION-relative offsets; orientation left at 0 to
// match the scouted heading).
const CUSTOM_AIR_VEHICLE_SPAWN_POINTS: VehicleSpawnPoint[] = [
  { offset: [50.68, -2.23, -2.2], orientation: [0, 0, 0] },
  { offset: [68.12, -6.057, 5.5], orientation: [0, 0, 0] },
  { offset: [76.78, -7.993, -14.5], orientation: [0, 0, 0] },
];

async function removeDefaultZones(): Promise<void> {
  if (!(await exists(TRADERZONES_DIR))) {
    log(
      `${TRADERZONES_DIR} not generated yet - DayZ-Expansion-Market will create it on first ` +
        "server start, nothing to remove yet",
    );
    return;
  }

  let removed = 0;
  for (const file of DEFAULT_ZONE_FILES) {
    const path = `${TRADERZONES_DIR}/${file}`;
    if (await exists(path)) {
      await Deno.remove(path);
      removed++;
    }
  }
  if (removed > 0) {
    ok(`Removed ${removed} default DayZ-Expansion-Market trader zone(s) from ${TRADERZONES_DIR}`);
  }
}

// A single, empty-slotted ExpansionPrefabObject - matches
// DayZ-Expansion-Core's own JsonFileLoader-serialized shape
// (ExpansionPrefabObject.c) so its JsonFileLoader<ExpansionLoadout> can
// parse these files back out with no further defaults needed.
function gearItemJson(className: string): Record<string, unknown> {
  return {
    ClassName: className,
    Include: "",
    Chance: 1.0,
    Quantity: { Min: 0, Max: 0 },
    Health: [],
    InventoryAttachments: [],
    InventoryCargo: [],
    ConstructionPartsBuilt: [],
    Sets: [],
  };
}

function loadoutJson(gear: GearSlot[]): string {
  return JSON.stringify(
    {
      ClassName: "",
      Include: "",
      Chance: 1.0,
      Quantity: { Min: 0, Max: 0 },
      Health: [],
      InventoryAttachments: gear.map((g) => ({
        SlotName: g.slot,
        Items: [gearItemJson(g.className)],
      })),
      InventoryCargo: [],
      ConstructionPartsBuilt: [],
      Sets: [],
    },
    null,
    4,
  );
}

async function ensureCustomTraderGear(): Promise<void> {
  await Deno.mkdir(EXPANSION_LOADOUTS_DIR, { recursive: true });

  let changed = 0;
  for (const loadout of CUSTOM_LOADOUTS) {
    const path = `${EXPANSION_LOADOUTS_DIR}/${loadout.name}.json`;
    const body = loadoutJson(loadout.gear);
    const existing = (await exists(path)) ? await Deno.readTextFile(path) : null;
    if (existing !== body) {
      await Deno.writeTextFile(path, body);
      changed++;
    }
  }
  if (changed > 0) {
    ok(`Wrote ${changed} custom trader gear loadout(s) to ${EXPANSION_LOADOUTS_DIR}`);
  }
}

async function ensureCustomTraderIdentities(): Promise<void> {
  if (!(await exists(EXPANSION_TRADERS_DIR))) {
    log(
      `${EXPANSION_TRADERS_DIR} not generated yet - DayZ-Expansion-Market will create it on ` +
        "first server start, nothing to add yet",
    );
    return;
  }

  let changed = 0;
  for (const identity of CUSTOM_TRADER_IDENTITIES) {
    const path = `${EXPANSION_TRADERS_DIR}/${identity.fileName}.json`;
    const body = JSON.stringify(
      {
        m_Version: 13,
        DisplayName: identity.displayName,
        MinRequiredReputation: 0,
        MaxRequiredReputation: 2147483647,
        RequiredFaction: "",
        RequiredCompletedQuestID: -1,
        TraderIcon: identity.icon,
        // Real, physical currency (see GOLD_CURRENCY_CLASSNAME below) -
        // DayZ-Expansion-Core ships this item by default. Matches
        // MarketSettings.json's own CurrencyIcon, a gold coin stack
        // graphic (coinstack2_64x64.edds).
        Currencies: [GOLD_CURRENCY_CLASSNAME],
        DisplayCurrencyValue: 1,
        DisplayCurrencyName: "Gold Coin",
        UseCategoryOrder: 0,
        Categories: identity.categories,
        Items: identity.items ?? {},
      },
      null,
      4,
    );
    const existing = (await exists(path)) ? await Deno.readTextFile(path) : null;
    if (existing !== body) {
      await Deno.writeTextFile(path, body);
      changed++;
    }
  }
  if (changed > 0) {
    ok(`Wrote ${changed} custom trader identity file(s) to ${EXPANSION_TRADERS_DIR}`);
  }
}

function traderMapLine(npc: CustomTraderNpc, origin: [number, number, number]): string {
  const pos = origin.map((v, i) => v + npc.offset[i]).map((n) => n.toFixed(3)).join(" ");
  const orientation = npc.orientation.join(" ");
  return `${npc.entity}.${npc.traderFile}|${pos}|${orientation}|${npc.gear ?? ""}`;
}

// Shape of the zone file this CLI owns. Only m_DisplayName/Position/Radius/
// BuyPricePercent/SellPricePercent are ever written here - Stock is the
// live, real running per-item stock map, populated and persisted by the
// game itself as players buy/sell. m_Version is left untouched too.
interface CustomZoneFile {
  m_Version: number;
  m_DisplayName: string;
  Position: [number, number, number];
  Radius: number;
  BuyPricePercent: number;
  SellPricePercent: number;
  Stock: Record<string, number>;
  [key: string]: unknown;
}

async function ensureCustomZone(): Promise<void> {
  if (!CUSTOM_POSITION) {
    warn(
      "Custom trader position not set yet (CUSTOM_POSITION in src/traders.ts) - skipping custom " +
        "trader zone/NPC setup. Scout a real position in-game as admin (COT's free cam/`INSERT` " +
        "+ position readout), fill it in, then re-run.",
    );
    return;
  }

  await Deno.mkdir(TRADERZONES_DIR, { recursive: true });
  const zonePath = `${TRADERZONES_DIR}/${CUSTOM_ZONE_NAME}.json`;

  const existing: CustomZoneFile | null = (await exists(zonePath))
    ? JSON.parse(await Deno.readTextFile(zonePath))
    : null;

  // Only patch the specific fields this CLI owns onto the existing
  // object; never rebuild it from scratch. Rebuilding with a hardcoded
  // Stock: {} was a real bug - it silently wiped every player's sold-in
  // trader stock on every server restart (this runs on every start via
  // ensureCustomTrader()).
  const zone: CustomZoneFile = existing ?? {
    m_Version: 6,
    m_DisplayName: "Custom Trading Zone",
    Position: CUSTOM_POSITION,
    Radius: CUSTOM_RADIUS,
    BuyPricePercent: 100.0,
    SellPricePercent: -1.0,
    Stock: {},
  };

  let changed = !existing;
  if (zone.m_DisplayName !== "Custom Trading Zone") {
    zone.m_DisplayName = "Custom Trading Zone";
    changed = true;
  }
  if (JSON.stringify(zone.Position) !== JSON.stringify(CUSTOM_POSITION)) {
    zone.Position = CUSTOM_POSITION;
    changed = true;
  }
  if (zone.Radius !== CUSTOM_RADIUS) {
    zone.Radius = CUSTOM_RADIUS;
    changed = true;
  }
  if (zone.BuyPricePercent !== 100.0) {
    zone.BuyPricePercent = 100.0;
    changed = true;
  }
  if (zone.SellPricePercent !== -1.0) {
    zone.SellPricePercent = -1.0;
    changed = true;
  }
  if (!zone.Stock) {
    zone.Stock = {};
    changed = true;
  }

  if (changed) {
    await Deno.writeTextFile(zonePath, JSON.stringify(zone, null, 4));
    ok(`Wrote ${zonePath}`);
  }

  await Deno.mkdir(TRADERS_DIR, { recursive: true });
  const mapPath = `${TRADERS_DIR}/${CUSTOM_ZONE_NAME}.map`;
  const mapBody = CUSTOM_NPCS.map((npc) => traderMapLine(npc, CUSTOM_POSITION)).join("\n") + "\n";
  const existingMap = (await exists(mapPath)) ? await Deno.readTextFile(mapPath) : null;
  if (existingMap !== mapBody) {
    await Deno.writeTextFile(mapPath, mapBody);
    ok(`Wrote ${mapPath} (${CUSTOM_NPCS.length} trader NPCs)`);
  }
}

// DayZ-Expansion-Core's own SafeZoneSettings.json schema (self-generated
// with Chernarus' default city safe zones already in CircleZones). Only
// the fields this reads/writes are typed; everything else round-trips
// untouched via the index signature.
interface SafeZoneCircleZone {
  Center: [number, number, number];
  Radius: number;
}

interface SafeZoneSettings {
  CircleZones: SafeZoneCircleZone[];
  [key: string]: unknown;
}

async function ensureCustomTraderSafeZone(): Promise<void> {
  if (!CUSTOM_POSITION) return; // same guard as ensureCustomZone() above

  if (!(await exists(SAFE_ZONE_SETTINGS))) {
    log(
      `${SAFE_ZONE_SETTINGS} not generated yet - DayZ-Expansion-Core will create it on first ` +
        "server start, nothing to add yet",
    );
    return;
  }

  const settings: SafeZoneSettings = JSON.parse(await Deno.readTextFile(SAFE_ZONE_SETTINGS));
  const existing = settings.CircleZones.find(
    (z) =>
      Math.abs(z.Center[0] - CUSTOM_POSITION[0]) < 1 &&
      Math.abs(z.Center[2] - CUSTOM_POSITION[2]) < 1,
  );

  if (existing) {
    if (existing.Radius === CUSTOM_SAFE_ZONE_RADIUS) return;
    const oldRadius = existing.Radius;
    existing.Radius = CUSTOM_SAFE_ZONE_RADIUS;
    await Deno.writeTextFile(SAFE_ZONE_SETTINGS, JSON.stringify(settings, null, 4));
    ok(
      `Updated the custom trader city safe zone radius from ${oldRadius}m to ` +
        `${CUSTOM_SAFE_ZONE_RADIUS}m in ${SAFE_ZONE_SETTINGS}`,
    );
    return;
  }

  settings.CircleZones.push({ Center: CUSTOM_POSITION, Radius: CUSTOM_SAFE_ZONE_RADIUS });
  await Deno.writeTextFile(SAFE_ZONE_SETTINGS, JSON.stringify(settings, null, 4));
  ok(
    `Added a ${CUSTOM_SAFE_ZONE_RADIUS}m safe zone at the custom trader city to ` +
      SAFE_ZONE_SETTINGS,
  );
}

// DayZ-Expansion-Market's global vehicle-spawn registry (self-generated the
// first time the mission loads, with 5-6 default entries all clustered near
// the vanilla trader city). Only the fields this reads/writes are typed;
// everything else (WaterSpawnPositions, distance settings, etc.) round-trips
// untouched via the index signature.
interface MarketSpawnPosition {
  Position: [number, number, number];
  Orientation: [number, number, number];
}

interface MarketSettings {
  LandSpawnPositions: MarketSpawnPosition[];
  AirSpawnPositions: MarketSpawnPosition[];
  [key: string]: unknown;
}

function ensureVehicleSpawnPositionList(
  list: MarketSpawnPosition[],
  points: VehicleSpawnPoint[],
  customPosition: [number, number, number],
  label: string,
): number {
  let added = 0;
  for (const point of points) {
    const absolute: [number, number, number] = [
      customPosition[0] + point.offset[0],
      customPosition[1] + point.offset[1],
      customPosition[2] + point.offset[2],
    ];
    const alreadyThere = list.some(
      (p) => Math.abs(p.Position[0] - absolute[0]) < 1 && Math.abs(p.Position[2] - absolute[2]) < 1,
    );
    if (alreadyThere) continue;
    list.push({ Position: absolute, Orientation: point.orientation });
    added++;
  }
  if (added > 0) {
    ok(`Added ${added} ${label} vehicle spawn position(s) near the custom trader city`);
  }
  return added;
}

async function ensureCustomVehicleSpawnPositions(): Promise<void> {
  if (!CUSTOM_POSITION) return; // same guard as ensureCustomZone() above
  const customPosition = CUSTOM_POSITION;

  if (
    CUSTOM_LAND_VEHICLE_SPAWN_POINTS.length === 0 &&
    CUSTOM_AIR_VEHICLE_SPAWN_POINTS.length === 0
  ) {
    warn(
      "CUSTOM_LAND_VEHICLE_SPAWN_POINTS/CUSTOM_AIR_VEHICLE_SPAWN_POINTS are both empty - " +
        "vehicle purchases at the custom trader city will fail with 'no air/land spawn space' " +
        "until you scout real, clear positions near the Vehicle Dealer NPC and fill them in " +
        "(see the TODO comment above those constants in src/traders.ts)",
    );
    return;
  }

  if (!(await exists(MARKET_SETTINGS))) {
    log(
      `${MARKET_SETTINGS} not generated yet - DayZ-Expansion-Market will create it on first ` +
        "server start, nothing to add yet",
    );
    return;
  }

  const settings: MarketSettings = JSON.parse(await Deno.readTextFile(MARKET_SETTINGS));
  const addedLand = ensureVehicleSpawnPositionList(
    settings.LandSpawnPositions,
    CUSTOM_LAND_VEHICLE_SPAWN_POINTS,
    customPosition,
    "land",
  );
  const addedAir = ensureVehicleSpawnPositionList(
    settings.AirSpawnPositions,
    CUSTOM_AIR_VEHICLE_SPAWN_POINTS,
    customPosition,
    "air",
  );

  if (addedLand > 0 || addedAir > 0) {
    await Deno.writeTextFile(MARKET_SETTINGS, JSON.stringify(settings, null, 4));
  }
}

// Exchange.json (profiles/ExpansionMod/Market/) is DayZ-Expansion-Market's
// dedicated currency category (IsExchange: 1 - market.ts's
// writeMergedCategory() always sets IsExchange: 0 for every other managed
// category, deliberately leaving this one alone).
interface ExchangeCategory {
  m_Version: number;
  DisplayName: string;
  Icon: string;
  Color: string;
  IsExchange: number;
  InitStockPercent: number;
  Items: {
    ClassName: string;
    MaxPriceThreshold: number;
    MinPriceThreshold: number;
    SellPricePercent: number;
    MaxStockThreshold: number;
    MinStockThreshold: number;
    QuantityPercent: number;
    SpawnAttachments: unknown[];
    Variants: unknown[];
  }[];
}

const EXCHANGE_FILE = `${EXPANSION_MARKET_DIR}/Exchange.json`;

// Makes GOLD_CURRENCY_CLASSNAME the one and only currency, both at the
// trader (Exchange.json) and at the ATM (MarketSettings.json's own
// separate Currencies list) - trader currency and ATM currency are two
// independently-configured lists, not derived from each other.
async function ensureGoldCoinCurrency(): Promise<void> {
  if (await exists(EXCHANGE_FILE)) {
    const data: ExchangeCategory = JSON.parse(await Deno.readTextFile(EXCHANGE_FILE));
    const alreadyGold = data.Items.length === 1 &&
      data.Items[0].ClassName === GOLD_CURRENCY_CLASSNAME;
    if (!alreadyGold) {
      data.Items = [
        {
          ClassName: GOLD_CURRENCY_CLASSNAME,
          MaxPriceThreshold: 1,
          MinPriceThreshold: 1,
          SellPricePercent: -1,
          MaxStockThreshold: 1,
          MinStockThreshold: 1,
          QuantityPercent: -1,
          SpawnAttachments: [],
          Variants: [],
        },
      ];
      await Deno.writeTextFile(EXCHANGE_FILE, JSON.stringify(data, null, 4));
      ok(`Switched trader currency to ${GOLD_CURRENCY_CLASSNAME} in ${EXCHANGE_FILE}`);
    }
  } else {
    log(
      `${EXCHANGE_FILE} not generated yet - DayZ-Expansion-Market will create it (with its ` +
        `own defaults) on first server start; re-run after that to switch it to ` +
        `${GOLD_CURRENCY_CLASSNAME}`,
    );
  }

  if (await exists(MARKET_SETTINGS)) {
    const settings: MarketSettings = JSON.parse(await Deno.readTextFile(MARKET_SETTINGS));
    const currencies = Array.isArray(settings.Currencies) ? settings.Currencies as string[] : [];
    const alreadyGold = currencies.length === 1 && currencies[0] === GOLD_CURRENCY_CLASSNAME;
    if (!alreadyGold) {
      settings.Currencies = [GOLD_CURRENCY_CLASSNAME];
      await Deno.writeTextFile(MARKET_SETTINGS, JSON.stringify(settings, null, 4));
      ok(`Switched ATM currency to ${GOLD_CURRENCY_CLASSNAME} in ${MARKET_SETTINGS}`);
    }
  }
}

// How much of an item's sale price a player actually gets when selling to
// the trader (ExpansionMarketModule.c's sell path multiplies the
// stock-interpolated price by this / 100). Buying is unaffected by this
// setting (buy path always uses a fixed 1.0 modifier) - so this is the
// "earning money should be hard" lever, paired with market.ts's
// BUY_PRICE_MULTIPLIER for the "spending money should be hard" side.
// DayZ-Expansion-Market's default is 75; see market.ts's
// SELL_PRICE_PERCENT_OVERRIDE, which bumps Rare/Legendary above this
// global value (40/60) instead of inheriting it uniformly.
const HARDCORE_SELL_PRICE_PERCENT = 20;

async function ensureHardcoreSellPricePercent(): Promise<void> {
  if (!(await exists(MARKET_SETTINGS))) return;

  const settings: MarketSettings = JSON.parse(await Deno.readTextFile(MARKET_SETTINGS));
  if (settings.SellPricePercent === HARDCORE_SELL_PRICE_PERCENT) return;

  settings.SellPricePercent = HARDCORE_SELL_PRICE_PERCENT;
  await Deno.writeTextFile(MARKET_SETTINGS, JSON.stringify(settings, null, 4));
  ok(`Set global SellPricePercent to ${HARDCORE_SELL_PRICE_PERCENT} in ${MARKET_SETTINGS}`);
}

export async function ensureCustomTrader(): Promise<void> {
  await removeDefaultZones();
  await ensureCustomTraderIdentities();
  await ensureCustomTraderGear();
  await ensureCustomZone();
  await ensureCustomTraderSafeZone();
  await ensureCustomVehicleSpawnPositions();
  await ensureGoldCoinCurrency();
  await ensureHardcoreSellPricePercent();
  await clampTraderStockToMarketCaps();
}

// Safety net: rebalancing src/market.ts's tier caps (TIER_MAX_STOCK) only
// ever changes the cap going forward - it never touches the live Stock
// numbers already sitting in the zone file, since those are the game's own
// persisted per-item quantities (see CustomZoneFile's own comment above -
// never rebuilt from scratch on purpose). If a cap is later lowered,
// existing stock can end up sitting above the new cap, which leaves those
// items looking broken/unavailable to buy in-game since the trader UI has
// no defined behavior for stock exceeding its own configured cap. Runs
// after ensureCustomZone() on every server start, clamping any classname
// whose live stock exceeds its current MaxStockThreshold (scanning only
// the real merged categories, MANAGED_MARKET_CATEGORIES from market.ts) -
// a cheap, idempotent no-op once nothing is over-cap.
async function clampTraderStockToMarketCaps(): Promise<void> {
  if (!(await exists(EXPANSION_MARKET_DIR))) return;

  const zonePath = `${TRADERZONES_DIR}/${CUSTOM_ZONE_NAME}.json`;
  if (!(await exists(zonePath))) return;

  const zone: CustomZoneFile = JSON.parse(await Deno.readTextFile(zonePath));
  if (!zone.Stock || Object.keys(zone.Stock).length === 0) return;

  const caps = new Map<string, number>(); // lowercased classname -> current MaxStockThreshold
  for (const categoryName of MANAGED_MARKET_CATEGORIES) {
    const path = `${EXPANSION_MARKET_DIR}/${categoryName}.json`;
    if (!(await exists(path))) continue;
    const data: { Items?: { ClassName?: string; MaxStockThreshold?: number }[] } = JSON.parse(
      await Deno.readTextFile(path),
    );
    for (const item of data.Items ?? []) {
      if (!item.ClassName || item.MaxStockThreshold === undefined) continue;
      // Only these real, merged categories are authoritative - deliberately
      // not scanning every file under EXPANSION_MARKET_DIR, since the raw
      // per-slot source files DayZ-Expansion-Market ships keep their own,
      // unrelated stale default MaxStockThreshold for the same classname.
      caps.set(item.ClassName.toLowerCase(), item.MaxStockThreshold);
    }
  }

  let clamped = 0;
  for (const [key, stock] of Object.entries(zone.Stock)) {
    const cap = caps.get(key);
    if (cap !== undefined && stock > cap) {
      zone.Stock[key] = cap;
      clamped++;
    }
  }

  if (clamped > 0) {
    await Deno.writeTextFile(zonePath, JSON.stringify(zone, null, 4));
    ok(`Clamped ${clamped} trader item(s) whose live stock exceeded their current cap`);
  }
}
