// Custom trader city: replaces DayZ-Expansion-Market's 6 stock Chernarus
// trader zones (Svetloyarsk, BalotaAircrafts, KamenkaBoats, GreenMountain,
// Kamenka, Krasnostav - self-generated by the mod into MISSION_DIR/
// expansion/traderzones/ on first world load, confirmed live - see
// MODS.md) with a single custom-designed one, per TODO.md's world-crafting
// checklist ("decide whether to keep/relocate/replace these zones... once
// custom traders are designed").
//
// Starting roster (deliberately small, per project decision): one general
// "Everything" trader plus one "Vehicle" trader, covering the essentials
// without needing to design/theme a dozen NPCs up front. Neither is one of
// DayZ-Expansion-Market's 17 default trader identities (Weapons, Clothing,
// Consumables, etc. under profiles/ExpansionMod/Traders/) - those ship
// untouched (see ensureCustomTraderIdentities()) for later use once more
// specific/themed traders are wanted; only these two custom identities are
// referenced by the actual NPCs below.
//
// This only defines the *shape* of the zone (radius/pricing) and its NPC
// roster. The actual world position is a one-time, hands-on decision this
// file deliberately refuses to guess at: scout a real spot in-game as admin
// (see MODS.md's "Admin tools" section - COT's free cam/`INSERT` plus its
// position readout, or `H` to teleport back to it), then fill in
// CUSTOM_POSITION below. Until that's set, this only removes the 6 defaults
// and leaves the custom zone/NPCs disabled (with a warning) rather than
// writing NPCs to a guessed, possibly-underground position.
//
// NPCs are placed via Expansion's plain-text `.map` format (one line each:
// `<TraderEntityClassName>.<TraderFileName>|<Position>|<Orientation>|<Gear>`)
// under MISSION_DIR/expansion/traders/ - confirmed directly from
// DayZ-Expansion-Core's own script source (unpacked ai_scripts/core_scripts
// PBOs; the wiki page describing this is gone from GitHub), specifically
// ExpansionWorldObjectsModule.c's GetTraderFromMissionFile()/ProcessGear().
// Individual NPC positions here are *offsets* from CUSTOM_POSITION (baked in
// at generation time), so only one real-world coordinate ever needs
// scouting.
//
// The Gear field is a comma-separated token list (NOT a filename by itself);
// the only token used here is `loadout:<Name>`, which applies a named gear
// preset from profiles/ExpansionMod/Loadouts/<Name>.json (written by
// ensureCustomTraderGear() below) via ExpansionHumanLoadout.Apply(). That
// preset file's schema (ExpansionPrefabObject/InventoryAttachments) is
// DayZ-Expansion-Core's own and is NOT the same as DayZ-Editor's exported
// character-preset JSON (attachmentSlotItemSets/discreteItemSets) - the
// latter had to be manually converted into the former (see TRADER_BLUE_GEAR).

import {
  EXPANSION_LOADOUTS_DIR,
  EXPANSION_MARKET_DIR,
  EXPANSION_TRADERS_DIR,
  MARKET_SETTINGS,
  MISSION_DIR,
  SAFE_ZONE_SETTINGS,
} from "./paths.ts";
import { log, ok, warn } from "./ui.ts";
import { exists } from "./steam.ts";
import { MANAGED_MARKET_CATEGORIES } from "./market.ts";

const TRADERZONES_DIR = `${MISSION_DIR}/expansion/traderzones`;
const TRADERS_DIR = `${MISSION_DIR}/expansion/traders`;

const DEFAULT_ZONE_FILES = [
  "Svetloyarsk.json",
  "BalotaAircrafts.json",
  "KamenkaBoats.json",
  "GreenMountain.json",
  "Kamenka.json",
  "Krasnostav.json",
];

const CUSTOM_ZONE_NAME = "CustomTrader";

// TODO: fill in with a real, scouted position ([x, y, z] - y is elevation,
// not optional) before this zone/its NPCs will be generated. e.g.:
//   const CUSTOM_POSITION: [number, number, number] | null = [7500, 20, 9600];
export const CUSTOM_POSITION: [number, number, number] | null = [7991.59, 221.09, 11312.5];
const CUSTOM_RADIUS = 150;

// A DayZ-Expansion-Core SafeZone (no PvP damage/vehicle damage) centered on
// the same spot as CUSTOM_POSITION (the General Trader, basically the
// trader city's center) - deliberately a separate, larger radius than
// CUSTOM_RADIUS above (which only governs Market buy/sell pricing/stock,
// nothing to do with combat). Also the radius serverpack/addons/
// DZSurvivalTraderRestock's ActionCheckTraderBoard.c uses for its own
// trader-proximity check - keep both in sync if this is ever changed. Also
// reused by aiWorldEvents.ts to keep the various AI-mod "safe zone" fields
// (Knock Knock Zombies/Airborne AI/hSF Zombie Horde) from spawning threats
// on top of the trader city.
export const CUSTOM_SAFE_ZONE_RADIUS = 175;

// Real, physical gold currency used as the trader city's (and ATM's) only
// currency - DayZ-Expansion-Core's own ExpansionGoldNugget. No new mod
// needed (Core is already required for the whole Expansion Market/trader
// system). Earlier considered @CJ187-MoreMoney's "Coin" item instead (a
// real gold-coin model) but its varStackMax is only 50 - not what "feel
// free to stack this up for convenience" needs - so that mod was dropped
// again; its items stay in marketGapFill.ts's MANUAL_EXCLUSIONS regardless,
// on the same defense-in-depth basis as every other permanently-denylisted
// classname there (harmless no-op unless the mod is ever reinstalled).
// Like the stock expansionbanknotehryvnia it replaces, this item has no
// types.xml entry - it's created purely from its own mod config on demand
// for trader/ATM purchases, not spawned via the CE.
//
// IMPORTANT - do NOT use ExpansionGoldNugget_InsanityStack here (its
// "_InsanityStack" variant bumps varStackMax/varQuantityMax from 50,000 to
// 16,777,216 and was tried first for that reason): confirmed via unpacking
// market_scripts.pbo that this variant is actually broken as an
// Exchange.json denomination. ExpansionMarketModule.LoadMoneyPrice() keys
// its classname->price map using the *unstripped* classname straight from
// Exchange.json, but GetMoneyPrice() unconditionally strips any
// "_insanitystack" suffix (MapInsanityStackToMoneyType()) before every
// lookup - so a denomination whose own configured classname already ends
// in "_InsanityStack" can never find its own price (always resolves to 0).
// SpawnMoneyInCurrency() then computes remainingAmount/0 for that
// denomination and skips spawning entirely - the sale/purchase still
// completes (stock/notification fire normally) but zero currency is ever
// actually created. Confirmed by reading the source, not simulated. Plain
// ExpansionGoldNugget's own native 50,000 stack cap (ExpansionMoneyNugget_
// Base, confirmed via core_objects_currencies.pbo) is still more than
// enough headroom for any realistic payout in this project's economy (a
// handful of stacks at most even for a Legendary-tier sale) without the
// InsanityStack lookup bug.
const GOLD_CURRENCY_CLASSNAME = "ExpansionGoldNugget";

interface TraderIdentity {
  fileName: string;
  displayName: string;
  icon: string;
  categories: string[];
}

// Same schema/currency as DayZ-Expansion-Market's own 17 default trader
// identity files (confirmed live, e.g. profiles/ExpansionMod/Traders/
// Weapons.json) - Categories reference Market category names under
// profiles/ExpansionMod/Market/, which are still individually stock-capped
// by src/market.ts (tuneExpansionMarket()) regardless of which trader
// sells them, so lumping everything into one NPC here doesn't bypass the
// "not everything can be bought" tuning.
// Every category name across both custom trader identities - exported so
// marketAudit.ts can compute exactly which category files a player can
// actually buy/sell from, without hand-reconstructing this list from
// market.ts's separate MANAGED_MARKET_CATEGORIES/RARE_CATEGORIES/
// VEHICLE_PARTS_CATEGORIES exports (which would silently drift out of sync
// if a category were ever added to one trader identity but not the other).
export const CUSTOM_TRADER_IDENTITIES: TraderIdentity[] = [
  {
    fileName: "Everything",
    displayName: "General Store",
    icon: "Trader",
    // See src/market.ts's MERGED_CATEGORIES for what each of these actually
    // contains and how items within them are tiered - these replace the
    // ~50 narrow categories DayZ-Expansion-Market ships by default.
    // Vehicles/Vehicle_Parts/Batteries are reserved for the Vehicle Dealer
    // below.
    categories: [
      "Guns_Military",
      "Guns_Civilian",
      "Gun_Ammo",
      "Gun_Attachments_Military",
      "Gun_Attachments_Civilian",
      "Explosives",
      "Clothing_Head_Military",
      "Clothing_Head_Civilian",
      "Clothing_Top_Military",
      "Clothing_Top_Civilian",
      "Clothing_Bottom_Military",
      "Clothing_Bottom_Civilian",
      "Clothing_Back_Military",
      "Clothing_Back_Civilian",
      "Clothing_Misc_Military",
      "Clothing_Misc_Civilian",
      "Ghillies",
      "Consumables",
      "Medical",
      "Base_Building",
      "Utility",
      "Tools_And_Melee",
    ],
  },
  {
    fileName: "Vehicle",
    displayName: "Vehicle Dealer",
    icon: "Car",
    // No Boats - no navigable water anywhere near this trader city (see
    // src/market.ts's Vehicles merge - Boats is deliberately excluded).
    categories: ["Vehicles_Cars", "Vehicles_Helicopters", "Vehicle_Parts", "Batteries"],
  },
];

interface CustomTraderNpc {
  entity: string;
  traderFile: string;
  /** Offset in meters from CUSTOM_POSITION, so only one coordinate needs scouting. */
  offset: [number, number, number];
  orientation: [number, number, number];
  gear?: string;
}

interface GearSlot {
  slot: string;
  className: string;
}

// Converted from the user's DayZ-Editor-exported outfit preset
// (Editor/trader-blue.json - schema: attachmentSlotItemSets/discreteItemSets,
// one itemType per slot) into DayZ-Expansion-Core's own, unrelated "loadout"
// schema (ExpansionPrefabObject/InventoryAttachments - see
// ensureCustomTraderGear() below). Only the single itemType from each of the
// editor preset's slots was kept; the editor's spawnWeight/health/quantity
// fields don't carry over 1:1 to this format and aren't needed for a fixed
// NPC outfit anyway.
const TRADER_BLUE_GEAR: GearSlot[] = [
  { slot: "Headgear", className: "BaseballCap_Blue" },
  { slot: "Gloves", className: "LeatherGloves_Natural" },
  { slot: "Armband", className: "Armband_Blue" },
  { slot: "Back", className: "BaseRadio" },
  { slot: "Body", className: "Hoodie_Blue" },
  { slot: "Feet", className: "AthleticShoes_Blue" },
  { slot: "Hips", className: "HipPack_Black" },
  { slot: "Legs", className: "CanvasPants_Blue" },
  { slot: "Vest", className: "PressVest_Blue" },
  { slot: "Melee", className: "Izh18Shotgun" },
];

// Vehicle Dealer's own outfit: same idea (blue armband, per request), but
// distinct dark colorway plus a different weapon so the two NPCs don't look
// identical at a glance. No "Back" slot here (unlike the general trader's
// BaseRadio) since that read as a duplicate backpack on both NPCs. Every
// classname below double-checked against db/types.xml - "CanvasPants_Black"
// and "PressVest_Black"/"FireAxe" (first draft) don't actually exist as
// items, which is why the pants silently failed to spawn in-game.
const TRADER_VEHICLE_GEAR: GearSlot[] = [
  { slot: "Headgear", className: "BaseballCap_Black" },
  { slot: "Gloves", className: "LeatherGloves_Black" },
  { slot: "Armband", className: "Armband_Blue" },
  { slot: "Body", className: "Hoodie_Black" },
  { slot: "Feet", className: "AthleticShoes_Black" },
  { slot: "Hips", className: "HipPack_Black" },
  { slot: "Legs", className: "CanvasPants_Grey" },
  { slot: "Vest", className: "LeatherStorageVest_Black" },
  { slot: "Melee", className: "FirefighterAxe_Black" },
];

const CUSTOM_LOADOUTS: { name: string; gear: GearSlot[] }[] = [
  { name: "TraderBlueLoadout", gear: TRADER_BLUE_GEAR },
  { name: "TraderVehicleLoadout", gear: TRADER_VEHICLE_GEAR },
];

// Small starting roster - one general trader, one vehicle trader. More
// specific/themed NPCs (referencing the untouched default trader files
// under profiles/ExpansionMod/Traders/) can be added here later.
const CUSTOM_NPCS: CustomTraderNpc[] = [
  {
    entity: "ExpansionTraderDenis",
    traderFile: "Everything",
    offset: [0, 0, 0],
    orientation: [176, 0, 0],
    gear: "loadout:TraderBlueLoadout",
  },
  {
    entity: "ExpansionTraderCyril",
    traderFile: "Vehicle",
    offset: [34.46, -5.34, -6.1],
    orientation: [-171.359, 0, 0],
    gear: "loadout:TraderVehicleLoadout",
  },
];

interface VehicleSpawnPoint {
  /** Offset in meters from CUSTOM_POSITION, same convention as CUSTOM_NPCS. */
  offset: [number, number, number];
  orientation: [number, number, number];
}

// DayZ-Expansion-Market vehicle purchases can ONLY spawn at a position
// listed in MarketSettings.json's LandSpawnPositions/AirSpawnPositions -
// confirmed via ExpansionTraderBase.HasVehicleSpawnPosition() (unpacked
// from market_scripts.pbo): it searches those lists for a *clear* spot
// within MaxVehicleDistanceToTrader (120m by default) of the buying
// trader's own NPC, and fails with "no [air/land] spawn space" if none
// qualify. The 5-6 shipped default entries are all clustered near the
// vanilla trader city (nowhere near this custom one), which is exactly why
// that error shows up here.
//
// TODO: fill these in with real, scouted positions - same workflow as
// CUSTOM_POSITION itself (COT free cam + position readout, see MODS.md's
// Admin tools section), but this time looking for genuinely CLEAR, flat
// ground within ~100m of the Vehicle Dealer NPC (CUSTOM_POSITION + the
// "Vehicle" CUSTOM_NPCS entry's offset above - i.e. around
// [34.46, -5.34, -6.1] from CUSTOM_POSITION). Land vehicles need enough
// flat space for the vehicle's own footprint; air vehicles (helicopters)
// need the same, just typically a more open area with nothing overhead.
// Add at least 2-3 points per type so a purchase still works if one spot is
// already occupied by a previously-bought vehicle. Left empty until
// scouted - ensureCustomVehicleSpawnPositions() below no-ops (with a
// warning) rather than guessing at real-world clearance.
// 3 scouted flat/clear car spots near the Vehicle Dealer NPC (absolute
// positions converted to CUSTOM_POSITION-relative offsets; orientation is
// [yaw, pitch, roll], matching CUSTOM_NPCS/MarketSettings.json's own
// convention - these have nonzero pitch/roll since the ground here isn't
// perfectly flat).
const CUSTOM_LAND_VEHICLE_SPAWN_POINTS: VehicleSpawnPoint[] = [
  { offset: [45.933, -8.234, -23.132], orientation: [90.03, -11.09, 6.56] },
  { offset: [45.518, -8.663, -29.127], orientation: [90.03, -11.09, 6.56] },
  { offset: [44.929, -8.807, -34.954], orientation: [90.09, -10.57, -0.17] },
];
// 3 scouted helipads near the Vehicle Dealer NPC (absolute positions
// converted to CUSTOM_POSITION-relative offsets; orientation left at 0 to
// match the scouted heading).
const CUSTOM_AIR_VEHICLE_SPAWN_POINTS: VehicleSpawnPoint[] = [
  { offset: [50.68, -2.23, -2.2], orientation: [0, 0, 0] },
  { offset: [68.12, -6.057, 5.5], orientation: [0, 0, 0] },
  { offset: [76.78, -7.993, -14.5], orientation: [0, 0, 0] },
];

async function removeDefaultZones(): Promise<void> {
  if (!(await exists(TRADERZONES_DIR))) {
    log(
      `${TRADERZONES_DIR} not generated yet - DayZ-Expansion-Market will create it on first ` +
        "server start, nothing to remove yet",
    );
    return;
  }

  let removed = 0;
  for (const file of DEFAULT_ZONE_FILES) {
    const path = `${TRADERZONES_DIR}/${file}`;
    if (await exists(path)) {
      await Deno.remove(path);
      removed++;
    }
  }
  if (removed > 0) {
    ok(`Removed ${removed} default DayZ-Expansion-Market trader zone(s) from ${TRADERZONES_DIR}`);
  }
}

// A single, empty-slotted ExpansionPrefabObject - matches
// DayZ-Expansion-Core's own JsonFileLoader-serialized shape
// (ExpansionPrefabObject.c) so its JsonFileLoader<ExpansionLoadout> can
// parse these files back out with no further defaults needed.
function gearItemJson(className: string): Record<string, unknown> {
  return {
    ClassName: className,
    Include: "",
    Chance: 1.0,
    Quantity: { Min: 0, Max: 0 },
    Health: [],
    InventoryAttachments: [],
    InventoryCargo: [],
    ConstructionPartsBuilt: [],
    Sets: [],
  };
}

function loadoutJson(gear: GearSlot[]): string {
  return JSON.stringify(
    {
      ClassName: "",
      Include: "",
      Chance: 1.0,
      Quantity: { Min: 0, Max: 0 },
      Health: [],
      InventoryAttachments: gear.map((g) => ({
        SlotName: g.slot,
        Items: [gearItemJson(g.className)],
      })),
      InventoryCargo: [],
      ConstructionPartsBuilt: [],
      Sets: [],
    },
    null,
    4,
  );
}

async function ensureCustomTraderGear(): Promise<void> {
  await Deno.mkdir(EXPANSION_LOADOUTS_DIR, { recursive: true });

  let changed = 0;
  for (const loadout of CUSTOM_LOADOUTS) {
    const path = `${EXPANSION_LOADOUTS_DIR}/${loadout.name}.json`;
    const body = loadoutJson(loadout.gear);
    const existing = (await exists(path)) ? await Deno.readTextFile(path) : null;
    if (existing !== body) {
      await Deno.writeTextFile(path, body);
      changed++;
    }
  }
  if (changed > 0) {
    ok(`Wrote ${changed} custom trader gear loadout(s) to ${EXPANSION_LOADOUTS_DIR}`);
  }
}

async function ensureCustomTraderIdentities(): Promise<void> {
  if (!(await exists(EXPANSION_TRADERS_DIR))) {
    log(
      `${EXPANSION_TRADERS_DIR} not generated yet - DayZ-Expansion-Market will create it on ` +
        "first server start, nothing to add yet",
    );
    return;
  }

  let changed = 0;
  for (const identity of CUSTOM_TRADER_IDENTITIES) {
    const path = `${EXPANSION_TRADERS_DIR}/${identity.fileName}.json`;
    const body = JSON.stringify(
      {
        m_Version: 13,
        DisplayName: identity.displayName,
        MinRequiredReputation: 0,
        MaxRequiredReputation: 2147483647,
        RequiredFaction: "",
        RequiredCompletedQuestID: -1,
        TraderIcon: identity.icon,
        // Real, physical currency (see GOLD_CURRENCY_CLASSNAME/
        // ensureGoldCoinCurrency() below) - DayZ-Expansion-Core ships this
        // item out of the box (core_objects_currencies.pbo, confirmed via
        // its own wiki: "gold/silver bars and nuggets we provide by default
        // with the Expansion Core mod"), so no extra mod/risk was needed.
        // Matches MarketSettings.json's own CurrencyIcon, a gold coin stack
        // graphic (coinstack2_64x64.edds).
        Currencies: [GOLD_CURRENCY_CLASSNAME],
        DisplayCurrencyValue: 1,
        DisplayCurrencyName: "Gold Coin",
        UseCategoryOrder: 0,
        Categories: identity.categories,
        Items: {},
      },
      null,
      4,
    );
    const existing = (await exists(path)) ? await Deno.readTextFile(path) : null;
    if (existing !== body) {
      await Deno.writeTextFile(path, body);
      changed++;
    }
  }
  if (changed > 0) {
    ok(`Wrote ${changed} custom trader identity file(s) to ${EXPANSION_TRADERS_DIR}`);
  }
}

function traderMapLine(npc: CustomTraderNpc, origin: [number, number, number]): string {
  const pos = origin.map((v, i) => v + npc.offset[i]).map((n) => n.toFixed(3)).join(" ");
  const orientation = npc.orientation.join(" ");
  return `${npc.entity}.${npc.traderFile}|${pos}|${orientation}|${npc.gear ?? ""}`;
}

// Shape of the zone file this CLI owns. Only m_DisplayName/Position/Radius/
// BuyPricePercent/SellPricePercent are ever written by this CLI - Stock is
// the *live*, real running per-item stock map, populated and persisted
// entirely by the game itself (ExpansionMarketTraderZone.Save()) as players
// buy/sell - confirmed live (1800+ real entries accumulate here during
// normal play). m_Version is left untouched too in case the game bumps it.
interface CustomZoneFile {
  m_Version: number;
  m_DisplayName: string;
  Position: [number, number, number];
  Radius: number;
  BuyPricePercent: number;
  SellPricePercent: number;
  Stock: Record<string, number>;
  [key: string]: unknown;
}

async function ensureCustomZone(): Promise<void> {
  if (!CUSTOM_POSITION) {
    warn(
      "Custom trader position not set yet (CUSTOM_POSITION in src/traders.ts) - skipping custom " +
        "trader zone/NPC setup. Scout a real position in-game as admin (see MODS.md's Admin tools " +
        "section: COT's free cam/`INSERT` + position readout), fill it in, then re-run.",
    );
    return;
  }

  await Deno.mkdir(TRADERZONES_DIR, { recursive: true });
  const zonePath = `${TRADERZONES_DIR}/${CUSTOM_ZONE_NAME}.json`;

  const existing: CustomZoneFile | null = (await exists(zonePath))
    ? JSON.parse(await Deno.readTextFile(zonePath))
    : null;

  // IMPORTANT: never rebuild this object from scratch once it exists - only
  // ever patch the specific fields this CLI actually owns onto the existing
  // object, preserving Stock (and anything else the game itself may have
  // added) untouched. Rebuilding unconditionally with a hardcoded `Stock: {}`
  // was a real, confirmed bug: since this runs on every server start (via
  // ensureCustomTrader()), it silently wiped every player's sold-in trader
  // stock back to empty on every single restart.
  const zone: CustomZoneFile = existing ?? {
    m_Version: 6,
    m_DisplayName: "Custom Trading Zone",
    Position: CUSTOM_POSITION,
    Radius: CUSTOM_RADIUS,
    BuyPricePercent: 100.0,
    SellPricePercent: -1.0,
    Stock: {},
  };

  let changed = !existing;
  if (zone.m_DisplayName !== "Custom Trading Zone") {
    zone.m_DisplayName = "Custom Trading Zone";
    changed = true;
  }
  if (JSON.stringify(zone.Position) !== JSON.stringify(CUSTOM_POSITION)) {
    zone.Position = CUSTOM_POSITION;
    changed = true;
  }
  if (zone.Radius !== CUSTOM_RADIUS) {
    zone.Radius = CUSTOM_RADIUS;
    changed = true;
  }
  if (zone.BuyPricePercent !== 100.0) {
    zone.BuyPricePercent = 100.0;
    changed = true;
  }
  if (zone.SellPricePercent !== -1.0) {
    zone.SellPricePercent = -1.0;
    changed = true;
  }
  if (!zone.Stock) {
    zone.Stock = {};
    changed = true;
  }

  if (changed) {
    await Deno.writeTextFile(zonePath, JSON.stringify(zone, null, 4));
    ok(`Wrote ${zonePath}`);
  }

  await Deno.mkdir(TRADERS_DIR, { recursive: true });
  const mapPath = `${TRADERS_DIR}/${CUSTOM_ZONE_NAME}.map`;
  const mapBody = CUSTOM_NPCS.map((npc) => traderMapLine(npc, CUSTOM_POSITION)).join("\n") + "\n";
  const existingMap = (await exists(mapPath)) ? await Deno.readTextFile(mapPath) : null;
  if (existingMap !== mapBody) {
    await Deno.writeTextFile(mapPath, mapBody);
    ok(`Wrote ${mapPath} (${CUSTOM_NPCS.length} trader NPCs)`);
  }
}

// DayZ-Expansion-Core's own SafeZoneSettings.json schema (confirmed live -
// see server/mpmissions/dayzOffline.chernarusplus/expansion/settings/
// SafeZoneSettings.json, self-generated with Chernarus' default city safe
// zones already in CircleZones). Only the fields this reads/writes are
// typed; everything else round-trips untouched via the index signature.
interface SafeZoneCircleZone {
  Center: [number, number, number];
  Radius: number;
}

interface SafeZoneSettings {
  CircleZones: SafeZoneCircleZone[];
  [key: string]: unknown;
}

async function ensureCustomTraderSafeZone(): Promise<void> {
  if (!CUSTOM_POSITION) return; // same guard as ensureCustomZone() above

  if (!(await exists(SAFE_ZONE_SETTINGS))) {
    log(
      `${SAFE_ZONE_SETTINGS} not generated yet - DayZ-Expansion-Core will create it on first ` +
        "server start, nothing to add yet",
    );
    return;
  }

  const settings: SafeZoneSettings = JSON.parse(await Deno.readTextFile(SAFE_ZONE_SETTINGS));
  const existing = settings.CircleZones.find(
    (z) =>
      Math.abs(z.Center[0] - CUSTOM_POSITION[0]) < 1 &&
      Math.abs(z.Center[2] - CUSTOM_POSITION[2]) < 1,
  );

  if (existing) {
    if (existing.Radius === CUSTOM_SAFE_ZONE_RADIUS) return;
    const oldRadius = existing.Radius;
    existing.Radius = CUSTOM_SAFE_ZONE_RADIUS;
    await Deno.writeTextFile(SAFE_ZONE_SETTINGS, JSON.stringify(settings, null, 4));
    ok(
      `Updated the custom trader city safe zone radius from ${oldRadius}m to ` +
        `${CUSTOM_SAFE_ZONE_RADIUS}m in ${SAFE_ZONE_SETTINGS}`,
    );
    return;
  }

  settings.CircleZones.push({ Center: CUSTOM_POSITION, Radius: CUSTOM_SAFE_ZONE_RADIUS });
  await Deno.writeTextFile(SAFE_ZONE_SETTINGS, JSON.stringify(settings, null, 4));
  ok(
    `Added a ${CUSTOM_SAFE_ZONE_RADIUS}m safe zone at the custom trader city to ` +
      SAFE_ZONE_SETTINGS,
  );
}

// DayZ-Expansion-Market's global vehicle-spawn registry (self-generated the
// first time the mission loads, with 5-6 default entries all clustered near
// the vanilla trader city). Only the fields this reads/writes are typed;
// everything else (WaterSpawnPositions, distance settings, etc.) round-trips
// untouched via the index signature.
interface MarketSpawnPosition {
  Position: [number, number, number];
  Orientation: [number, number, number];
}

interface MarketSettings {
  LandSpawnPositions: MarketSpawnPosition[];
  AirSpawnPositions: MarketSpawnPosition[];
  [key: string]: unknown;
}

function ensureVehicleSpawnPositionList(
  list: MarketSpawnPosition[],
  points: VehicleSpawnPoint[],
  customPosition: [number, number, number],
  label: string,
): number {
  let added = 0;
  for (const point of points) {
    const absolute: [number, number, number] = [
      customPosition[0] + point.offset[0],
      customPosition[1] + point.offset[1],
      customPosition[2] + point.offset[2],
    ];
    const alreadyThere = list.some(
      (p) => Math.abs(p.Position[0] - absolute[0]) < 1 && Math.abs(p.Position[2] - absolute[2]) < 1,
    );
    if (alreadyThere) continue;
    list.push({ Position: absolute, Orientation: point.orientation });
    added++;
  }
  if (added > 0) {
    ok(`Added ${added} ${label} vehicle spawn position(s) near the custom trader city`);
  }
  return added;
}

async function ensureCustomVehicleSpawnPositions(): Promise<void> {
  if (!CUSTOM_POSITION) return; // same guard as ensureCustomZone() above
  const customPosition = CUSTOM_POSITION;

  if (
    CUSTOM_LAND_VEHICLE_SPAWN_POINTS.length === 0 &&
    CUSTOM_AIR_VEHICLE_SPAWN_POINTS.length === 0
  ) {
    warn(
      "CUSTOM_LAND_VEHICLE_SPAWN_POINTS/CUSTOM_AIR_VEHICLE_SPAWN_POINTS are both empty - " +
        "vehicle purchases at the custom trader city will fail with 'no air/land spawn space' " +
        "until you scout real, clear positions near the Vehicle Dealer NPC and fill them in " +
        "(see the TODO comment above those constants in src/traders.ts)",
    );
    return;
  }

  if (!(await exists(MARKET_SETTINGS))) {
    log(
      `${MARKET_SETTINGS} not generated yet - DayZ-Expansion-Market will create it on first ` +
        "server start, nothing to add yet",
    );
    return;
  }

  const settings: MarketSettings = JSON.parse(await Deno.readTextFile(MARKET_SETTINGS));
  const addedLand = ensureVehicleSpawnPositionList(
    settings.LandSpawnPositions,
    CUSTOM_LAND_VEHICLE_SPAWN_POINTS,
    customPosition,
    "land",
  );
  const addedAir = ensureVehicleSpawnPositionList(
    settings.AirSpawnPositions,
    CUSTOM_AIR_VEHICLE_SPAWN_POINTS,
    customPosition,
    "air",
  );

  if (addedLand > 0 || addedAir > 0) {
    await Deno.writeTextFile(MARKET_SETTINGS, JSON.stringify(settings, null, 4));
  }
}

// Exchange.json (profiles/ExpansionMod/Market/) is DayZ-Expansion-Market's
// dedicated currency category (IsExchange: 1 - see market.ts's
// writeMergedCategory(), which always sets IsExchange: 0 for every *other*
// managed category, deliberately leaving this one alone) - self-generated
// with expansionbanknotehryvnia as its sole item on first server start,
// same timing as everything else under EXPANSION_MARKET_DIR/MARKET_SETTINGS
// (see tuneExpansionMarket()/ensureCustomVehicleSpawnPositions()).
interface ExchangeCategory {
  m_Version: number;
  DisplayName: string;
  Icon: string;
  Color: string;
  IsExchange: number;
  InitStockPercent: number;
  Items: {
    ClassName: string;
    MaxPriceThreshold: number;
    MinPriceThreshold: number;
    SellPricePercent: number;
    MaxStockThreshold: number;
    MinStockThreshold: number;
    QuantityPercent: number;
    SpawnAttachments: unknown[];
    Variants: unknown[];
  }[];
}

const EXCHANGE_FILE = `${EXPANSION_MARKET_DIR}/Exchange.json`;

// Makes GOLD_CURRENCY_CLASSNAME the one and only currency, both at the
// trader (Exchange.json - what the market system will mint/accept as
// change) and at the ATM (MarketSettings.json's own separate Currencies
// list - confirmed via DayZ-Expansion-Scripts' own wiki, "[Server Hosting]
// Setting up Custom Market Currencies": trader currency and ATM currency are
// two independently-configured lists, not derived from each other).
async function ensureGoldCoinCurrency(): Promise<void> {
  if (await exists(EXCHANGE_FILE)) {
    const data: ExchangeCategory = JSON.parse(await Deno.readTextFile(EXCHANGE_FILE));
    const alreadyGold = data.Items.length === 1 &&
      data.Items[0].ClassName === GOLD_CURRENCY_CLASSNAME;
    if (!alreadyGold) {
      data.Items = [
        {
          ClassName: GOLD_CURRENCY_CLASSNAME,
          MaxPriceThreshold: 1,
          MinPriceThreshold: 1,
          SellPricePercent: -1,
          MaxStockThreshold: 1,
          MinStockThreshold: 1,
          QuantityPercent: -1,
          SpawnAttachments: [],
          Variants: [],
        },
      ];
      await Deno.writeTextFile(EXCHANGE_FILE, JSON.stringify(data, null, 4));
      ok(`Switched trader currency to ${GOLD_CURRENCY_CLASSNAME} in ${EXCHANGE_FILE}`);
    }
  } else {
    log(
      `${EXCHANGE_FILE} not generated yet - DayZ-Expansion-Market will create it (with its ` +
        `own defaults) on first server start; re-run after that to switch it to ` +
        `${GOLD_CURRENCY_CLASSNAME}`,
    );
  }

  if (await exists(MARKET_SETTINGS)) {
    const settings: MarketSettings = JSON.parse(await Deno.readTextFile(MARKET_SETTINGS));
    const currencies = Array.isArray(settings.Currencies) ? settings.Currencies as string[] : [];
    const alreadyGold = currencies.length === 1 && currencies[0] === GOLD_CURRENCY_CLASSNAME;
    if (!alreadyGold) {
      settings.Currencies = [GOLD_CURRENCY_CLASSNAME];
      await Deno.writeTextFile(MARKET_SETTINGS, JSON.stringify(settings, null, 4));
      ok(`Switched ATM currency to ${GOLD_CURRENCY_CLASSNAME} in ${MARKET_SETTINGS}`);
    }
  }
}

// How much of an item's sale price a player actually gets when selling to
// the trader (ExpansionMarketModule.c's sell path multiplies the
// stock-interpolated price by this / 100 - confirmed via unpacking
// market_scripts.pbo). Buying is completely unaffected by this setting (the
// buy path always uses a fixed 1.0 modifier) - so this is the "earning
// money should be hard" lever, paired with market.ts's BUY_PRICE_MULTIPLIER
// for the "spending money should be hard" side. DayZ-Expansion-Market's own
// default is 75 (sell for 75% of value); dropped to 20 for the 2026-08
// hardcore-survival pass - see serverpack/README.md. (A later pass briefly
// tried 12, but the project owner asked to keep this at 20 and instead
// raise rarer items' sell percentage individually - see market.ts's
// SELL_PRICE_PERCENT_OVERRIDE, which layers on top of this global value
// via DayZ-Expansion-Market's own item > zone > global fallback chain.)
const HARDCORE_SELL_PRICE_PERCENT = 20;

async function ensureHardcoreSellPricePercent(): Promise<void> {
  if (!(await exists(MARKET_SETTINGS))) return;

  const settings: MarketSettings = JSON.parse(await Deno.readTextFile(MARKET_SETTINGS));
  if (settings.SellPricePercent === HARDCORE_SELL_PRICE_PERCENT) return;

  settings.SellPricePercent = HARDCORE_SELL_PRICE_PERCENT;
  await Deno.writeTextFile(MARKET_SETTINGS, JSON.stringify(settings, null, 4));
  ok(`Set global SellPricePercent to ${HARDCORE_SELL_PRICE_PERCENT} in ${MARKET_SETTINGS}`);
}

export async function ensureCustomTrader(): Promise<void> {
  await removeDefaultZones();
  await ensureCustomTraderIdentities();
  await ensureCustomTraderGear();
  await ensureCustomZone();
  await ensureCustomTraderSafeZone();
  await ensureCustomVehicleSpawnPositions();
  await ensureGoldCoinCurrency();
  await ensureHardcoreSellPricePercent();
  await clampTraderStockToMarketCaps();
}

// Safety net for a real, confirmed data-integrity bug (2026-08 follow-up
// audit): every rebalance of src/market.ts's tier caps (TIER_MAX_STOCK) only
// ever changes the *cap* going forward - it never touches the *live* Stock
// numbers already sitting in this zone file, because those are the game's
// own persisted, real per-item quantities (see CustomZoneFile's own comment
// above - never rebuilt from scratch on purpose). Confirmed live: after this
// project tightened Common-tier stock from an old, higher default down to
// 25, 1,002 out of 2,717 managed items (37%) were still sitting at their
// old value (mostly 75) - e.g. `deersteakmeat`/`porkcan`/`tunacan` capped at
// 25 but still showing a live stock of 75. DayZ-Expansion-Market's own
// trader UI has no defined behavior for stock exceeding its own configured
// cap (that state should never arise from the mod's own normal operation -
// restocking always caps at MaxStockThreshold, only a purchase/sale ever
// changes it otherwise), and in practice this leaves those items looking
// broken/unavailable to buy in-game, while newly-added, properly-in-bounds
// items (e.g. the `Old_*` variants) display normally - exactly matching a
// report of "plenty of Old_ food, but no regular canned food or meat", even
// though the regular items were never actually removed from the trader.
// Runs after ensureCustomZone() (so the zone file/Stock map already exists)
// on every server start, clamping any classname whose live stock exceeds
// its *current* MaxStockThreshold (found by scanning only the 21 real
// merged categories, MANAGED_MARKET_CATEGORIES from market.ts - never a
// raw per-slot source file's own, unrelated stale default) down to that
// cap - a cheap, idempotent no-op once nothing is over-cap, and a
// permanent guard against this recurring after any future tier rebalance.
async function clampTraderStockToMarketCaps(): Promise<void> {
  if (!(await exists(EXPANSION_MARKET_DIR))) return;

  const zonePath = `${TRADERZONES_DIR}/${CUSTOM_ZONE_NAME}.json`;
  if (!(await exists(zonePath))) return;

  const zone: CustomZoneFile = JSON.parse(await Deno.readTextFile(zonePath));
  if (!zone.Stock || Object.keys(zone.Stock).length === 0) return;

  const caps = new Map<string, number>(); // lowercased classname -> current MaxStockThreshold
  for (const categoryName of MANAGED_MARKET_CATEGORIES) {
    const path = `${EXPANSION_MARKET_DIR}/${categoryName}.json`;
    if (!(await exists(path))) continue;
    const data: { Items?: { ClassName?: string; MaxStockThreshold?: number }[] } = JSON.parse(
      await Deno.readTextFile(path),
    );
    for (const item of data.Items ?? []) {
      if (!item.ClassName || item.MaxStockThreshold === undefined) continue;
      // Only these 21 real, merged categories are authoritative (see
      // MANAGED_MARKET_CATEGORIES comment) - deliberately NOT scanning every
      // file under EXPANSION_MARKET_DIR, since the ~50 raw per-slot source
      // files DayZ-Expansion-Market ships (e.g. Meat.json) keep their own,
      // unrelated stale default MaxStockThreshold for the same classname
      // (confirmed: Meat.json's own `deersteakmeat` entry still says 30,
      // completely unconnected to Consumables.json's real, tuned cap of 25)
      // - using those would clamp to the wrong number entirely.
      caps.set(item.ClassName.toLowerCase(), item.MaxStockThreshold);
    }
  }

  let clamped = 0;
  for (const [key, stock] of Object.entries(zone.Stock)) {
    const cap = caps.get(key);
    if (cap !== undefined && stock > cap) {
      zone.Stock[key] = cap;
      clamped++;
    }
  }

  if (clamped > 0) {
    await Deno.writeTextFile(zonePath, JSON.stringify(zone, null, 4));
    ok(`Clamped ${clamped} trader item(s) whose live stock exceeded their current cap`);
  }
}
